### ISSUE TITLE
Double-install would mess up libraries

### ISSUE THREAD

**Issue by ypnos** [miurahr/aqtinstall#132]
Installing over existing installation breaks so files.

System: Archlinux

Steps to reproduce:
```sh
sudo pip install aqtinstall
sudo aqt install --outputdir /opt 5.11.3 linux desktop
sudo aqt install --outputdir /opt 5.11.3 linux desktop -m qtcharts
```

Expected: A working installation in /opt/5.11.3
Actual result: Library files are missing, instead they are symlinks to themselves, e.g.:

> libQt5Core.so -> libQt5Core.so.5.11.3
  libQt5Core.so.5 -> libQt5Core.so.5.11.3
  libQt5Core.so.5.11 -> libQt5Core.so.5.11.3
  **libQt5Core.so.5.11.3 -> libQt5Core.so.5.11.3**

**Comment by miurahr** [comment]
aptinstall does not guarantee double install working. Actually it breaks installation because it does not clean before install.

```
sudo pip install aqtinstall
sudo aqt install --outputdir /opt 5.11.3 linux desktop -m qtcharts
```
It should works.

**Comment by ypnos** [comment]
Maybe the application could give a warning if the target directory already exists and is not empty?

**Comment by miurahr** [comment]
PR is welcome.

**Comment by miurahr** [comment]
A dependent library py7zr changes its behavior to creation of symlink on extraction. It might help the issue.
