### ISSUE TITLE
download qt5_xxxx_src_doc_examples

### ISSUE THREAD

**Issue by afarcat** [miurahr/aqtinstall#137]
can add feature to download: qt5_xxxx_src_doc_examples
thanks a lot.

**Comment by miurahr** [comment]
How is it as command line interface?

Now  'install' sub-command is used  for Qt library, 'tool' sub-command for tools such as  an installation framework.

Is it OK for sub-command  to be 'src' and rest of argument is same as 'install' sub command?

**Comment by afarcat** [comment]
According to the currently defined interface, I think you can provide three subcommands "src/doc/examples" to download the corresponding data, so that users can choose to download data to their needs. 

The rest of argument can be same as 'tool' sub command, it depends on how fast and simple you can implement it.

**Comment by miurahr** [comment]
When looking into Qt download site,
https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5150_src_doc_examples/
```
 qt.qt5.5150/	17-May-2020 16:39	-	 
 qt.qt5.5150.src/	17-May-2020 16:39	-	 
 qt.qt5.5150.examples/	17-May-2020 16:39	-	 
 qt.qt5.5150.examples.qtwebengine/	17-May-2020 16:38	-	 
 qt.qt5.5150.examples.qtvirtualkeyboard/	17-May-2020 16:39	-	 
 qt.qt5.5150.examples.qtscript/	17-May-2020 16:39	-	 
 qt.qt5.5150.examples.qtquicktimeline/	17-May-2020 16:39	-	 
 qt.qt5.5150.examples.qtquick3d/	17-May-2020 16:39	-	 
 qt.qt5.5150.examples.qtpurchasing/	17-May-2020 16:39	-	 
 qt.qt5.5150.examples.qtnetworkauth/	17-May-2020 16:39	-	 
 qt.qt5.5150.examples.qtlottie/	17-May-2020 16:39	-	 
 qt.qt5.5150.examples.qtdatavis3d/	17-May-2020 16:38	-	 
 qt.qt5.5150.examples.qtcharts/	17-May-2020 16:39	-	 
 qt.qt5.5150.doc/	17-May-2020 16:38	-	 
 qt.qt5.5150.doc.qtwebengine/	17-May-2020 16:39	-	 
 qt.qt5.5150.doc.qtvirtualkeyboard/	17-May-2020 16:38	-	 
 qt.qt5.5150.doc.qtscript/	17-May-2020 16:39	-	 
 qt.qt5.5150.doc.qtquicktimeline/	17-May-2020 16:39	-	 
 qt.qt5.5150.doc.qtquick3d/	17-May-2020 16:39	-	 
 qt.qt5.5150.doc.qtpurchasing/	17-May-2020 16:39	-	 
 qt.qt5.5150.doc.qtnetworkauth/	17-May-2020 16:38	-	 
 qt.qt5.5150.doc.qtlottie/	17-May-2020 16:38	-	 
 qt.qt5.5150.doc.qtdatavis3d/	17-May-2020 16:39	-	 
 qt.qt5.5150.doc.qtcharts/	17-May-2020 16:39	-	 
```
There are many directories.
It may indicate that we need a command interface like '-m module , module ...' for documents and examples.

When checking meta data database
https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5150_src_doc_examples/Updates.xml

We should specify tag names such as 

* qt.qt5.5150.doc
* qt.qt5.5150.doc.qtcharts
* qt.qt5.5150.examples

**Comment by miurahr** [comment]
https://github.com/miurahr/aqtinstall/tree/topic-doc-src-example
Working here now.

**Comment by miurahr** [comment]
@afarcat  you can try it with  commands

```
aqt doc 5.15.0 linux desktop -m qtcharts
aqt examples 5.15.0 linux desktop -m qtcharts
aqt src 5.15.0 linux desktop
```

**Comment by miurahr** [comment]
v0.9.0 released with the doc/examples/src feature.

**Comment by afarcat** [comment]
@miurahr 
I tested the doc/examples/src feature commands. They work very well and the command parameters are easy to use. 
thank you.
