### ISSUE TITLE
aqt can not install Qt 6

### ISSUE THREAD

**Issue by hunger** [miurahr/aqtinstall#144]
I tried to download and install the Qt 6 snapshots using

> aqt install 6.0.0 linux desktop

That failed since no information on qt5_600 could be found.

**Comment by miurahr** [comment]
#145

**Comment by miurahr** [comment]
v0.9.2 is out. @hunger could you give a feedback?

**Comment by hunger** [comment]
Sorry, I am not much of a python user, so it took a while to figure out how to test the newest version:-)

It works, thank you for the quick response and fix! It does seem to install fine -- as fine as with the official installer.
