### ISSUE TITLE
Armv7 options

### ISSUE THREAD

**Issue by evan-swinney** [miurahr/aqtinstall#147]
More of a question rather than a problem, unless this doesn't support it: but what about the armv7 or armv8 architecture that you may find on a Raspberry Pi 3 or Raspberry Pi 4? Is there a set of options that would support this? I do not mean Android either, just a normal Linux Desktop build, but for armv7. I know you can do that from the sources easily enough, but this would speed that process up considerably.

**Comment by miurahr** [comment]
This seems a question about Qt itself not installer.
The Qt Company does not provide binary package, so installer does not support it.

https://wiki.qt.io/Raspberry_Pi_Beginners_Guide
Here is a document you can install Qt from source onto Raspberry Pi.

Good luck!

**Comment by evan-swinney** [comment]
Yeah, I've been compiling from source for quite a while for a CI/CD pipeline, and your tool looked very promising. Perhaps I will use it for an x86 CI/CD image. Figured I'd ask! Thanks for the quick reply.

Closing.
