### ISSUE TITLE
Qt 4 support

### ISSUE THREAD

**Issue by Vampire** [miurahr/aqtinstall#148]
Am I right, that aqt does not support Qt 4?
Would it be feasible to add support for QT 4? :-)

**Comment by miurahr** [comment]
Yes it does not support Qt4.
As usual, PR is welcome.

**Comment by katutxakurra** [comment]
Could you please give an example of a command to install QT 4.8.6 or 4.8.7? The default repository doesn't include qt 4 versions and I don't know what base should I use.

**Comment by miurahr** [comment]
>  it does not support Qt4.
