### ISSUE TITLE
Qt5.7 installation failed: Download error: decompression get wrong: no output data

### ISSUE THREAD

**Issue by pbek** [miurahr/aqtinstall#149]
I was sent over from https://github.com/jurplel/install-qt-action/issues/50 with an install problem:

I'm currently having issues with the Qt 5.7  installation on Windows (some still are using Windows XP) with `win32_mingw53`.

Config: https://github.com/pbek/QOwnNotes/blob/48f5b73e1b0a200b88c93d82ef6192f7d80fbe03/.github/workflows/build.yml#L61-L69
Build log: https://github.com/pbek/QOwnNotes/runs/880829548?check_suite_focus=true

I always get the error `Download error: decompression get wrong: no output data.` for all packages:

```
2020-07-17 06:56:23,560 - aqt - INFO - Downloading qtsvg...
2020-07-17 06:56:23,560 - aqt - DEBUG - Download URL: http://mirrors.ocf.berkeley.edu/qt//online/qtsdkrepository/windows_x86/desktop/qt5_57/qt.57.win32_mingw53/5.7.1-0qtsvg-Windows-Windows_7-Mingw53-Windows-Windows_7-X86.7z
2020-07-17 06:56:24,064 - aqt - ERROR - Download error: decompression get wrong: no output data.
```

- I tried with and without mirror
- Qt 5.14.2 works great, only Qt 5.7 doesn't seem to work
- When I download the file on my computer it decompresses fine

Has anyone seen something like that?

**Comment by miurahr** [comment]
This caused by dependency project py7zr's fixed bug
https://github.com/miurahr/py7zr/issues/178
https://github.com/miurahr/py7zr/releases/tag/v0.9.0b1


Could you specify py7zr version `py7zrversion` as v0.9.0b3 in install-qt-action?

**Comment by pbek** [comment]
> Could you specify py7zr version py7zrversion as v0.9.0b3 in install-qt-action?

Thank you for your quick answer, I'll ask back!

**Comment by pbek** [comment]
py7zr 0.9 was installed: https://github.com/pbek/QOwnNotes/runs/930611080?check_suite_focus=true#step:4:29

But I still get the same error: https://github.com/pbek/QOwnNotes/runs/930611080?check_suite_focus=true#step:4:80

**Comment by miurahr** [comment]
py7zr v0.9 was installed,  but uninstalled and intalled again v0.7 later.
```
Installing collected packages: six, pyparsing, packaging, certifi, urllib3, idna, chardet, requests, py7zr, aqtinstall
  Attempting uninstall: py7zr
    Found existing installation: py7zr 0.9.0b3
    Uninstalling py7zr-0.9.0b3:
      Successfully uninstalled py7zr-0.9.0b3
Successfully installed aqtinstall-0.9.0 certifi-2020.6.20 chardet-3.0.4 idna-2.10 packaging-20.4 py7zr-0.7.4 pyparsing-2.4.7 requests-2.24.0 six-1.15.0 urllib3-1.25.10
```

**Comment by miurahr** [comment]
aqtinstall has a version dependency configuration as `    py7zr>=0.7.0,<0.8.0` so it happend.
It is aqtinstall issue.

**Comment by pbek** [comment]
Thank you for your concern and your fix! So should I wait until the fix is released?

**Comment by miurahr** [comment]
Fix released.

**Comment by pbek** [comment]
@miurahr, great, thank you! Which version is it released under? The release said 0.9.3, but pip didn't find that one (and 0.9.0b3 still will be downgraded like before).

**Comment by pbek** [comment]
(Sorry, about the 0.9.3, that is aptinstall). I tried `py7zrversion: '==0.9.0'`, but still got `Download error: decompression get wrong: no output data.`on https://github.com/pbek/QOwnNotes/runs/934552523?check_suite_focus=true#step:4:84.

**Comment by pbek** [comment]
Of course I also need to set `aqtversion: '==0.9.3'`, now Qt downloads for Qt 5.7 under Windows. Thank you very much!

**Comment by pbek** [comment]
Oh, but now I get errors like `Download error: CRC32 error on archived file 5.7/mingw53_32/bin/qmake.exe.`. 😬 
https://github.com/pbek/QOwnNotes/runs/934564323?check_suite_focus=true#step:4:154

**Comment by miurahr** [comment]
There seems to be three issues on Qt5.7 installation on windows.

1. no output data - this is fixed with py7zr v0.9.0
2. CRC32 error
3. Unfinished extraction

The latter  2 and 3 errors are also related to py7zr. These errors are new for py7zr project and very difficult to fix.

We need to take another way to escape it.
Could you please use external command to extract  Qt 5.7 installation?

 aqtinstall has a command line option: `[-E | --external <7zip command>]`

For windows, adding option such as `-E "c:\Program Files\7-zip\bin\7z.exe"`

**Comment by miurahr** [comment]
Fix is pushed as aqtinstall v0.9.4

**Comment by miurahr** [comment]
Does your problem resolved? @pbek

**Comment by pbek** [comment]
Thank you very much! The installation now went through! 🥳
