### ISSUE TITLE
Bug: Installing tool tools_openssl_src fails because of unsplittable None

### ISSUE THREAD

**Issue by MasterQ32** [miurahr/aqtinstall#153]
When i tried installing the tool `tools_openssl_src`, i got a error that some code was trying to split `None`. I tracked down the issue to the following line of code:
https://github.com/miurahr/aqtinstall/blob/5227044bbfa36eb4398521b28eef2c80caca2eb8/aqt/archives.py#L230

Not every tool has downloadable archives, so a fix would be this:

```py
__archives = packageupdate.find("DownloadableArchives").text
if __archives != None:
    downloadable_archives = __archives.split(", ")
else:
    downloadable_archives = []
```

Command line to reproduce the issue:
```sh
python -m aqt tool -O qtstuff windows tools_openssl_src win64_mingw81 qt.tools.openssl.src
```

For reference: The Update.xml file: https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_openssl_src/Updates.xml

**Comment by miurahr** [comment]
v0.9.5 with fix is out.
