### ISSUE TITLE
Python 3 - old system

### ISSUE THREAD

**Issue by Ti-R** [miurahr/aqtinstall#157]
Hello,
Great project !
A minor upgrade could be to use Shebang Python3
Using `#!/usr/bin/env python3` instead of `#!/usr/bin/env python` will enable to use it on 'older' system where python 3 is not the default one.
What do you think ?
Ti-R

**Comment by miurahr** [comment]
Good point! As usual, PR is welcome.

**Comment by miurahr** [comment]
@Ti-R  You may want to ask a change on  [setuptools](https://pypi.org/project/setuptools/) project, because an executable script `py7zr` is generated by python standard [setuptools](https://pypi.org/project/setuptools/).

**Comment by miurahr** [comment]
v0.9.6 now explicitly configured setup.cfg as minimum python version is 3.6.

When you run `python2 -m pip install  aqtinstall`, you will see `aqtinstall requires Python '>=3.6' but the running Python is 2.7.13`

**Comment by miurahr** [comment]
Now python2 user cannot install aqtinstall, which prevent a issue.
