### ISSUE TITLE
qtenv.bat

### ISSUE THREAD

**Issue by petersteneteg** [miurahr/aqtinstall#160]
Hi

I seem to be missing the `bin/qtenv.bat`file. It is there when I run the regular GUI installer. 
but not when I do 
`python.exe -m aqt install -O C:/Qt 5.15.0 windows desktop win64_msvc2019_64`

Am I missing some step? Or is the file missing for some other reason? 

Thanks for a great utility!!!

**Comment by miurahr** [comment]
Could you @petersteneteg  help me to look for archive file which hold qtenv.bat file?

Here is a list of archives for win64_msvc2019_64 installation;
https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5150/qt.qt5.5150.win64_msvc2019_64/

**Comment by miurahr** [comment]
I found it in https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5150/qt.qt5.5150.win64_msvc2019_64/5.15.0-0-202005150700meta.7z

The genuine installer has an engine to interpret and execute Qt installer script, installscript.qs, which aqtinstall does not and won't have.

The script has a part to create batch command

```
function createShortcuts()
{
    var qtStringVersion = "5.15.0";
    var linkPostfix = qtStringVersion + " (MSVC 2019 64-bit)";
    // Create a batch file with the development environment
    var component_root_path = installer.value("TargetDir") + "/5.15.0/msvc2019_64";
    component_root_path = component_root_path.replace(/\//g, "\\");

    var batchFileName = component_root_path + "\\" + "bin" + "\\" + "qtenv2.bat";
    var contentString = "@echo off\r\n";
    contentString += "echo Setting up environment for Qt usage...\r\n";
    contentString += "set PATH="  + component_root_path + "\\bin;%PATH%\r\n";
    contentString += "cd /D " + component_root_path + "\r\n";
    contentString += "echo Remember to call vcvarsall.bat to complete environment setup!\r\n";
    // Dump batch file
    component.addOperation("AppendFile", batchFileName, contentString);

    var windir = installer.environmentVariable("WINDIR");
    if (windir == "") {
        QMessageBox["warning"]( "Error" , "Error", "Could not find windows installation directory");
        return;
    }

    var cmdLocation = windir + "\\system32\\cmd.exe";
    component.addOperation( "CreateShortcut",
                            cmdLocation,
                            "@StartMenuDir@/" + qtStringVersion + "/MSVC 2019 (64-bit)/Qt " + linkPostfix + ".lnk",
                            "/A /Q /K " + batchFileName);
    // Assistant
    component.addOperation( "CreateShortcut",
                            component_root_path + "/bin/assistant.exe",
                            "@StartMenuDir@/" + qtStringVersion + "/MSVC 2019 (64-bit)/Assistant " + linkPostfix + ".lnk");

    // Designer
    component.addOperation( "CreateShortcut",
                            component_root_path + "/bin/designer.exe",
                            "@StartMenuDir@/" + qtStringVersion + "/MSVC 2019 (64-bit)/Designer " + linkPostfix + ".lnk");


    // Linguist
    component.addOperation( "CreateShortcut",
                            component_root_path + "/bin/linguist.exe",
                            "@StartMenuDir@/" + qtStringVersion + "/MSVC 2019 (64-bit)/Linguist " + linkPostfix + ".lnk");
}

```

**Comment by petersteneteg** [comment]
Thanks for finding out! After some discussion, I figured out we called that bat file our selfs when we ran windeployqt (https://doc.qt.io/qt-5/windows-deployment.html) as a post build step. I think I can work around doing that. 
Anyway since it is there in the official installer it might be good to include it...

**Comment by miurahr** [comment]
You can create bat file by yourself, which just set PATH environment and change current directory to a directory where you specified to install.
