### ISSUE TITLE
CRC32 errors on a specific download package

### ISSUE THREAD

**Issue by cocus** [miurahr/aqtinstall#162]
Hi! I'm using this tool inside the jurplel/install-qt-action's action.

When running it on a windows host, I get the following error:
`2020-09-16 15:14:52,247 - aqt - ERROR - Download error: CRC32 error on archived file 5.6/msvc2015_64/bin/icudt54.dll.`

My command line is
`python -m aqt install -O D:\a\testing/Qt 5.6 windows desktop win64_msvc2015_64 -b http://mirrors.ocf.berkeley.edu/qt/`

Is this something that's caused because of the mirror I'm using? Or is this file corrupted and it's distributed like that?

I've tried multiple times, and it's always the same file with a CRC32 error.

Thanks!

**Comment by miurahr** [comment]
There is a known problem in aqtinstall < 0.9.4 , to fails with CRC32 error to install Qt5.7 and before.
It is a problem in 7-zip extraction library,  py7zr < 0.9.1.
aqtinstall ver. 0.9.4 and after ask to install py7zr>=0.9.1. Please use recent version of aqtinstall and recent version of py7zr.

**Comment by miurahr** [comment]
I've reproduce CRC32 error with  [a package file](https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_56/qt.56.win64_msvc2015_64/5.6.2-0icu-win-msvc2013-Windows8.1-x64.7z) on py7zr project.

Please use `--external 7z` option of action-qt-install.

**Comment by miurahr** [comment]
The issue is reproduced at https://github.com/miurahr/py7zr/pull/250

**Comment by miurahr** [comment]
Fix is released on py7zr project as v0.9.9.

Please use py7zrversion== 0.9.9  option on install-qt-action project.
