### ISSUE TITLE
WARNING - Specified target combination is not valid: linux tools_ifw

### ISSUE THREAD

**Issue by EndrII** [miurahr/aqtinstall#170]
Hi 
updated QIF (IFW) and came across a problem.
```
aqt tool linux tools_ifw 3.2.2 qt.tools.ifw.32
```
or 
```
aqt tool linux tools_ifw 4.0.0 " "
```
I get a warning and the installation is aborted.
```
2020-11-04 13:51:01,137 - aqt - INFO - aqtinstall(aqt) v0.9.7 on Python 3.8.6 [CPython GCC 10.2.0]
2020-11-04 13:51:01,137 - aqt - WARNING - Specified target combination is not valid: linux tools_ifw qt.tools.ifw.32
2020-11-04 13:51:01,336 - aqt - INFO - Finished installation
2020-11-04 13:51:01,337 - aqt - INFO - Time elasped: 0.20086125 second

```
what has changed?

### P.S 
the same problem in Windows

**Comment by EndrII** [comment]
PR #171 should fix the warning, but this issue will probably not be fixed. I couldn't figure out why it doesn't load ifw.

**Comment by miurahr** [comment]
> I get a warning and the installation is aborted.
This part is just check known combination and show warning,  but the process is continues.
If installation was aborted, there may be an another issue.

**Comment by miurahr** [comment]
There seems that ifw 3.2.2 is removed from Qt download site.

 https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/Updates.xml

```
<Name>qt.tools.ifw.40</Name>
<DisplayName>Qt Installer Framework 4.0</DisplayName>
<Description>The Qt Installer Framework provides a set of tools and utilities to create installers for the supported desktop Qt platforms: Linux, Microsoft Windows, and macOS.</Description>
<Version>4.0</Version>
```
so 
```
aqt  tool linux tools_ifw 4.0 qt.tools.ifw.40
```
may be a correct command line.

**Comment by EndrII** [comment]
```
aqt  tool linux tools_ifw 4.0 qt.tools.ifw.40
```
Yes this is work. Thanks you
