### ISSUE TITLE
Suggestion: Add modules to existing install

### ISSUE THREAD

**Issue by bothorsen** [miurahr/aqtinstall#174]
First: Thank you for this package. It's great for creating docker images with Qt :) We use it at Viking Software to create the Windows images for our gitlab CI builds.

This may be a feature that already exists. If so, then you should treat it as a request to add a bit of info to the documentation.

I would like to have a way to add a module to an existing installation. For example, I have run "aqt install --outputdir c:\Qt 5.15.1 windows desktop win64_msvc2019_64" and now I would like to add the qtwebengine module in a later command. I haven't been able to find this anywhere.

The background for this is that we have a generic Qt base image. Most of the various projects we have in gitlab have their own docker image to build in. In the generic image, we run the above command, and now we would like to be able to add modules in the project specific image.

**Comment by miurahr** [comment]
There is advanced option '--archives' that limit installation of mandatory core packages, specify just  minimum packages user want. You or contributors can easily extend the code to install *nothing* of core packages.
And aqt modify a qt configuration after extraction of packages. It should be skipped.

It would be a good first issue.

**Comment by miurahr** [comment]
Does #204 work for you? @bothorsen

**Comment by miurahr** [comment]
out as v1.0.0b3

**Comment by bothorsen** [comment]
Looks great, thank you :)
