### ISSUE TITLE
Possible unwanted interaction between `--archives` and `-m qtwebengine` (or perhaps just documentation needed)

### ISSUE THREAD

**Issue by pestophagous** [miurahr/aqtinstall#175]
Much like other users have said: **Thank you** for this fantastic tool. You have supplied a very helpful way to achieve unattended continuous integration workflows with Qt right now.

For several weeks, I have been successfully using the following syntax [here](https://github.com/219-design/qt-qml-project-template-with-ci/blob/8f5511d425ec3279b/tools/ci/get_qt_libs.sh#L20):

```
  # https://github.com/miurahr/aqtinstall/issues/126 "Installing smaller subset of the libraries"
  python3 -m aqt install --outputdir $DL_FOLDER/Qt_desktop 5.15.0 linux desktop --archives \
   icu \
   qtbase \
   qtconnectivity \
   qtdeclarative \
   qtgraphicaleffects \
   qtimageformats \
   qtquickcontrols \
   qtquickcontrols2 \
   qtsvg \
   qttools
```

Today, I started experimenting with adding `qtwebengine` to the download, and it took me several tries to get it right.

### My local environment

The commands below were tested on Ubuntu "bionic" 18.04.5 LTS.

The below tests were done with `aqtinstall-0.9.8` installed via `pip3`

### What did I expect?

I would expect that all 3 of the below attempts would download the set of {qtbase, qtsvg, qtwebengine}.

```
# (1)
python3 -m aqt install --outputdir $DL_FOLDER/Qt_desktop 5.15.0 linux desktop --archives qtbase qtsvg qtwebengine

# (2)
python3 -m aqt install --outputdir $DL_FOLDER/Qt_desktop 5.15.0 linux desktop --archives qtbase qtsvg  -m qtwebengine

# (3)
python3 -m aqt install --outputdir $DL_FOLDER/Qt_desktop 5.15.0 linux desktop --archives qtbase qtsvg qtwebengine -m qtwebengine
```

### What did I observe instead?

Only attempt (3) downloaded the set {qtbase, qtsvg, qtwebengine}.  The other attempts seem to ignore my request for `qtwebengine`.

### Next steps

Because I was able to find a command that works, I am not seeking any bug-fix unless you think it is necessary.

I am curious to know whether this behavior is expected.

**Comment by miurahr** [comment]
`--archive` is misunderstanding for its usage. I'd like to change the option name to '--limit-package-to-only' or similar.

When specified `-m`, it can be  multiple packages defined. `--archive` limit individual package to be installed from base and modules.

**Comment by pestophagous** [comment]
Thank you for clarifying.

Even if `--archives` is dangerous, please keep that option.  I enjoy using `--archives` to limit the overall amount of what is downloaded. I usually just want `qtbase` and `qtdeclarative`, and not much more. (Of course, I do not object at all to a renaming of the option to make it more clear.)

Some follow-up questions:

- "from base and modules"
    - When you say "base", which Qt binaries are part of "base" in your understanding?
    - When you say "modules", which Qt binaries are the "modules"?

I tried to make a guess by reading this Qt page: https://doc.qt.io/qt-5/qtmodules.html

Does `aqtinstall` consider the following to be "base", and everything else a "module"(?) ---->

- Qt Core
- Qt GUI
- Qt Multimedia
- Qt Multimedia Widgets
- Qt Network
- Qt QML
- Qt Quick
- Qt Quick Controls
- Qt Quick Dialogs
- Qt Quick Layouts
- Qt Quick Test
- Qt SQL
- Qt Test
- Qt Widgets

I appreciate your time and your excellent work!

**Comment by miurahr** [comment]
All the packages are defined on XML file at download.qt.io site.

ex. https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_600/Updates.xml

The module name of base is `<Name>qt.qt6.600.gcc_64</Name>` and package names are defined as `<DownloadableArchives>qtbase-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtsvg-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtdeclarative-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qttools-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtquickcontrols2-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qttranslations-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtwayland-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, icu-linux-Rhel7.2-x64.7z</DownloadableArchives>`

so we can specify `qtbase, qtsvg`..etc as `--archive` parameter.

When specifying `qt5compat` as module(-m) then it is defined as follows:

```
<Dependencies>qt.qt6.600.gcc_64</Dependencies>
<DownloadableArchives>qt5compat-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z</DownloadableArchives>
```

so `qt5compat` from string `qt5compat-Linux...` is also a name of package which can be specified to `--archive` parameter.

**Comment by pestophagous** [comment]
Thank you for your help!  The format of `Updates.xml` is still confusing to me, but that is not your fault! 

I will close this, since this was not a bug and you have added a lot of helpful discussion.

**Comment by miurahr** [comment]
#204 change behavior. It add -m  argument into archives list.
