### ISSUE TITLE
Qt 6 support

### ISSUE THREAD

**Issue by kelteseth** [miurahr/aqtinstall#176]
Hi!

Because qdoc now ships with the latest Qt beta, and is vastly better the the 5.x version, I wanted to install Qt6 via aqt but was unable to do so.

`
- PS C:\aqt> aqt install --outputdir c:\aqt 6.0 windows desktop win64_msvc2019_64
- 2020-11-14 19:11:49,190 - aqt - INFO - aqtinstall(aqt) v0.9.8 on Python 3.9.0 [CPython MSC v.1927 64 bit (AMD64)]
- 2020-11-14 19:11:49,402 - aqt - ERROR - Download error when access to https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt6_60/Updates.xml
- Server response code: 404, reason: Not Found

`

**Comment by miurahr** [comment]
The Qt Company changes Qt6 version scheme to 6.0.0 from 6.0 in 13, Nov.

**Comment by kelteseth** [comment]
Yes this does work, thanks! Maybe add this to the readme? 👏👍

**Comment by miurahr** [comment]
@kelteseth You are welcome to add it to README through Pull-Request as usual.

**Comment by miurahr** [comment]
Repository is updated
