### ISSUE TITLE
5.12.10 not recognized as a Qt release

### ISSUE THREAD

**Issue by vadi2** [miurahr/aqtinstall#186]
> 2020-12-10 11:26:50,121 - aqt - INFO - aqtinstall(aqt) v0.10.0 on Python 3.9.0 [CPython MSC v.1927 64 bit (AMD64)]
> 2020-12-10 11:26:50,130 - aqt - WARNING - Specified Qt version is unknown: 5.12.10.

**Comment by miurahr** [comment]
Versions are maintained by hand.

https://github.com/miurahr/aqtinstall/blob/master/aqt/combinations.json#L103-L111

You are welcome to propose Pull-Request to add '5.12.10' in the list.

**Comment by vadi2** [comment]
https://github.com/miurahr/aqtinstall/pull/188
