### ISSUE TITLE
IOS install seems not working.

### ISSUE THREAD

**Issue by zimml** [miurahr/aqtinstall#197]
Hi, 

I'm trying to install Qt for IOS

```
python3 -m aqt install 5.15.2 mac ios -O /Users/runner/work/estimator/Qt -b http://mirrors.ocf.berkeley.edu/qt/
2021-01-21 11:01:39,767 - aqt - INFO - aqtinstall(aqt) v0.10.0 on Python 3.9.1 [CPython Clang 11.0.0 (clang-1100.0.33.17)]
```

The process seems hang forever and never goes further than that.

Note I switched to a mirror as Qt download servers seems down now.

**Comment by miurahr** [comment]
Could you try v0.11.0? 

in v0.10.0, downloading metadata from download.qt.io that is down.
in 0.11.0, when main site down, it automatically switch to mirror site.
#198 add timeout for metadata download.

**Comment by miurahr** [comment]
v0.11.1 is out with timeout option.
