### ISSUE TITLE
Test Qt android SDK installation on CI

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#20]

**Comment by nelsonjchen** [comment]
I didn't find your fork until I had made my own but I made this script to generate an `azure-pipelines.yml` for my fork with all known QT options:

https://github.com/nelsonjchen/qli-installer/blob/master/.azure-pipelines/generate_azure_pipelines_yml.py

Output: https://github.com/nelsonjchen/qli-installer/blob/master/azure-pipelines.yml

Maybe this might be a good reference.

**Comment by nelsonjchen** [comment]
Ooh, you are looking at my script! Cool! 

You should know, it does this and makes a ton of jobs:

https://dev.azure.com/nelsonjchen/QLI-Installer/_build/results?buildId=329

**Comment by miurahr** [comment]
Because generator script is written with some python 3.7 features, I've modified to be able to run by older one.

**Comment by nelsonjchen** [comment]
😅 ah yeah, I made it for 3.7 because I didn't intend for the script to be run by end-users but just developers to regenerate `azure-pipelines.yml` in rare instances.

**Comment by nelsonjchen** [comment]
It is interesting to see that the Windows SDK jobs aren't completing due to some connectivity issue with a QT mirror in China.

**Comment by nelsonjchen** [comment]
"根据相关法律法规，本站不对欧盟用户提供服务。"

Google Translated: "According to relevant laws and regulations, this site does not provide services to EU users."

This is taken from the legal text stuff at the bottom of the HTTP directory listing at https://mirrors.tuna.tsinghua.edu.cn/qt/archive/qt/5.9/5.9.8/single/.

I wonder if those jobs are running from the EU or something. Azure Pipelines has an overflow system where [if a region has too many jobs running, it'll use capacity from other regions](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#agent-ip-ranges). However, this only documented for the Brazil South or West Europe regions. That said, maybe they might not have documented Southeast Asia's overflow, if any.

If you want to "trust, but verify" that, perhaps you can throw in a call to some GeoIP thing and log to STDOUT where the VM running the job.

**Comment by nelsonjchen** [comment]
Actually, nevermind that. If it was in the EU, the chances of the mirror system giving that mirror's address should be not much, if at all. But still, maybe worth verifying.

**Comment by nelsonjchen** [comment]
Hmm, I hit that same issue just recently even in the US region. Maybe a retry option should be added.

**Comment by miurahr** [comment]
Thank you for investigation. We can take workaround for check geoip and handling redirects through python http subsystem. here is a mirror list: https://download.qt.io/static/mirrorlist/

**Comment by miurahr** [comment]
feature is committed
