### ISSUE TITLE
Android installs are (apparently) borked

### ISSUE THREAD

**Issue by LorenDB** [miurahr/aqtinstall#207]
First of all, please note that I'm using jurplel's install-qt-action to execute these commands through GitHub Actions, so this isn't actually happening on my computer.

Running `python3 -m aqt install -O /home/runner/work/QCalc/Qt 6.0.0 linux android android_armv7` produces the error `FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/QCalc/Qt/6.0.0/android_armv7/bin/qt.conf'`. This also has been happening with 5.15.2 and 5.15.1. Full output logs are available [here](https://github.com/LorenDB/QCalc/runs/1827149494).

**Comment by miurahr** [comment]
Oh, I found android toolkit distribution don't have a `qt.conf`  as in desktop Qt, but there is `target_qt.conf`.
So aqtinstall may need to touch `target_qt.conf`?

@LorenDB  do you know how `target_qt.conf` should be?

**Comment by miurahr** [comment]
The log said
```
python3 -m aqt install -O /home/runner/work/QCalc/Qt 6.0.0 linux android android_armv7
2021-02-04 00:44:29,476 - aqt - INFO - aqtinstall(aqt) v0.9.7 on Python 3.6.9 [CPython GCC 8.4.0]
362
2021-02-04 00:44:29,477 - aqt - WARNING - Specified Qt version is unknown: 6.0.0.
363
2021-02-04 00:44:30,372 - aqt - ERROR - Specified packages are not found while parsing XML of package information!
```

Than means 6.0.0 android_armv7 for linux don't exist.

**Comment by miurahr** [comment]
A crach has already reported at #206

**Comment by LorenDB** [comment]
OK, I see. Thanks!
