### ISSUE TITLE
Patched version of Qt5Core cannot be signed for MacOS

### ISSUE THREAD

**Issue by Aksem** [miurahr/aqtinstall#211]
From version 1.0.0b3 (1.0.0b1 works, 1.0.2b2 not tested) Qt5Core cannot be signed using macdeployqt for MacOS. I assume it's because of patching as I see the changelog and history of the repository.

Error:
```
ERROR: "/Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: the __LINKEDIT segment does not cover the end of the file (can't be processed) in: /bin/App.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore\n"
```

Command used: `macdeployqt App.app -hardened-runtime`
Qt Version: `5.14.2`
macOS: 10.14
XCode: 11.3.1

**Comment by miurahr** [comment]
On discussions at  https://github.com/miurahr/aqtinstall/issues/100#issuecomment-623913628 `patching` QtCore is introduced. After 1.0.0b2, patching is done for all platforms.
The discussion tell us Qt version 5.14.0 and later are relocatable.  https://www.qt.io/blog/qt-is-relocatable

Should not be Qt 5.14.2 on Mac  patched?

**Comment by miurahr** [comment]
It seems regression that patching QtCore is necessary for < 5.14.0 but v1.0.0b2 and later do it for all versions.

**Comment by miurahr** [comment]
#212 handle the case.
@Aksem could you help us to produce a regression test case to detect same regression?

**Comment by Aksem** [comment]
@miurahr , yes it works again!

What info do you need for a regression test case or how can I help with it?

**Comment by miurahr** [comment]
There are github actions test cases.
You may be able to add some command to it to reproduce the case, for example,  running macdeployqt.

**Comment by vadi2** [comment]
This also manifested itself as:

> ./Mudlet-4.10.1-testing-pr4746-c87b784c.app: main executable failed strict validation
In subcomponent: /Users/runner/work/Mudlet/b/ninja/Mudlet-4.10.1-testing-pr4746-c87b784c.app/Contents/Frameworks/QtCore.framework

Thanks for fixing it!
