### ISSUE TITLE
Some modules are not installed

### ISSUE THREAD

**Issue by paulo-coutinho** [miurahr/aqtinstall#219]
Hi,

Im trying install and compile mine project:

```
aqt install -O qt 6.0.1 mac desktop
```

Error:

```
Project ERROR: Unknown module(s) in QT: multimedia multimediawidgets
```

In my qtproject i have:

```
QT += core gui multimedia multimediawidgets qml quick
```

So i tried install current version 5 (5.14.1). From qtcreator it run, but from command line i got same error on qt5.

```
aqt install -O qt 5.14.1 mac desktop
or
aqt install -O qt 5.14.1 mac desktop --archives icu qtbase qtconnectivity qtdeclarative qtgraphicaleffects qtimageformats qtquickcontrols qtquickcontrols2 qtsvg qttools multimedia multimediawidgets
```

```
Project ERROR: Unknown module(s) in QT: multimedia multimediawidgets
```

**Comment by vadi2** [comment]
multimedia for certain isn't available in Qt 6.x yet, but I can't comment on 5.14.1.

**Comment by paulo-coutinho** [comment]
Solved.

Only need use:
```
aqt install -O qt 5.14.1 mac desktop
```

For Qt 6 it was removed and i don't know how it will work there:
https://doc.qt.io/qt-6/whatsnew60.html#removed-modules-in-qt-6-0

Thanks.
