### ISSUE TITLE
How to use aqtinstall with a paid Qt License?

### ISSUE THREAD

**Issue by forlayo** [miurahr/aqtinstall#227]
I am using Qt with a paid license then I need to build my artifacts with that license, I am wondering how this could be specified to aqtinstall.

do I need to put the licence somewhere? Is enough with that? Or the installers are different from community than licensed one? 

Mine has the name.. "qt-unified-windows-x86-4.0.1-1-online.exe"

**Comment by miurahr** [comment]
Because aqtinstall is unofficial installer, it always install Qt as OSS license.
Please ask your paid support desk, because you have rights.
