### ISSUE TITLE
Support for KDE Patch collection

### ISSUE THREAD

**Issue by vadi2** [miurahr/aqtinstall#231]
KDE have announced that they're going to [keep patching Qt 5](https://dot.kde.org/2021/04/06/announcing-kdes-qt-5-patch-collection) which is great news for us Qt users. KDE-specific patches won't be in there either.

Could aqtinstall support installing Qt from this repo as well? I understand it's quite a different architecture and concept since Qt would have to be compiled on-demand... or pre-compiled in github actions and downloaded as artifacts. Nonetheless, `aqtinstall` supporting this would be a great boon to many of the Qt projects that depend on it.

See https://community.kde.org/Qt5PatchCollection for the FAQ and https://invent.kde.org/qt/qt/qtbase for the repo.

**Comment by miurahr** [comment]
@vadi2 Thanks for sharing the news.

aqtinstall is an *installer*, so compiling and packaging is an out of scope.
When you, or someone, are ready to start a packaging and distribution site, I'd like to help it.

**Comment by miurahr** [comment]
@vadi2  You can download Qt source from Qt download package,  and patch it with KDE patch collection with `--kde` option by PR #274 
Then you can compile Qt from source.

for example;
```
aqt src -O Qt 5.15.2 linux desktop --kde --archives qtbase
mkdir build
cd build
../Qt/5.15.2/Src/qtbase/configure -opensource -confirm-license  -sysroot  ../Qt/5.15.2/gcc_64
make -j3
```

**Comment by miurahr** [comment]
Implemented.
