### ISSUE TITLE
[QUESTION] Isn't QtCretaor bunduled?

### ISSUE THREAD

**Issue by Godnyx** [miurahr/aqtinstall#232]
Actually I'm really wondering, isn't qt creator bundled with the other qt components? I downloaded Qt version 6.0.1

**Comment by pzhlkj6612** [comment]
Hi. Qt Creator is a tool and you can install it in this way:

```console
$ # For example, on linux.
$ aqt tool  linux  tools_qtcreator 4.14.2-0-202103191039 qt.tools.qtcreator
$ # params: <host> <tool_name>     <tool-version>        <arch>
```

The version number `4.14.2-0-202103191039` comes from https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_qtcreator/Updates.xml . The third parameter "arch" is a directory name, you can find it from https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_qtcreator/ .

You can read the doc for more details: [README.rst § Installing tool and utility (Experimental)](https://github.com/miurahr/aqtinstall/blob/a577555a6b20a20383f684cc08fa1b342b8747c6/README.rst#installing-tool-and-utility-experimental)

**Comment by Godnyx** [comment]
After all this days I was finally able to test this out and make this work! Thanks a lot for your great work!
