### ISSUE TITLE
Installation of Qt IFW tools doesn't give working IFW tools

### ISSUE THREAD

**Issue by sionhughes** [miurahr/aqtinstall#233]
Within Gitlab CI pipeline on multiple projects, I've witnessed installation of Qt IFW tools resulting in an invalid set of tools available on the build platform. The tools are used to build an installer via `cpack` of a Windows based Qt project. 

Error output via cpack as it can't find all parts of IFW toolset:
```
CPack Error: Cannot find QtIFW compiler "binarycreator": likely it is not installed, or not in your PATH
CPack Error: Cannot initialize the generator IFW
```

Installation of Qt IFW tools is done using the following command:
```
aqt tool --outputdir C:\Qt windows tools_ifw 4.0 qt.tools.ifw.40
```

On 13/04/21 @ 04:03 UTC, the installation took `9.16696960 second` (working state, installer built OK) 
On 13/04/21 @20:32 UTC, the installation took `1.10179330 second` (non-working state, running `cpack` results in error)

What could have changed for the installation? Change of sources from the Qt server?

**Comment by sionhughes** [comment]
Just looking a little further in, looks like Qt IFW tools 4.1.0 was released today:

![image](https://user-images.githubusercontent.com/7159235/114620324-5edbd680-9ca3-11eb-8cb7-4ef8fa4ac073.png)

Could that have broken things?

**Comment by sionhughes** [comment]
Right.... some more digging. 

Is this because the `qt.tools.ifw.40` dir is no longer present, and replaced by `qt.tools.ifw.41` at https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/ ?

Installing version 4.1 using `aqt tool --outputdir C:\Qt windows tools_ifw 4.1 qt.tools.ifw.41` locally on my laptop results in tools being installed. Made changes to CI pipelines now kicking them off to prove this change. Will report back in the morning as I'm not waiting for them to run now.

**Comment by pzhlkj6612** [comment]
> Is this because the qt.tools.ifw.40 dir is no longer present, and replaced by qt.tools.ifw.41 at https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/ ?

Yes, it is. You can open [Updates.xml (linux_x64)](https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/Updates.xml) to see what package(s) can be installed.

**Comment by miurahr** [comment]
There are many space to improve for the tools installation.
If you know the tools well, could you help me/us to improve it?

- Automatically detect an available version and its URL.
- CLI interface to list available tools and versions

**Comment by sionhughes** [comment]
> > Is this because the qt.tools.ifw.40 dir is no longer present, and replaced by qt.tools.ifw.41 at https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/ ?
> 
> Yes, it is. You can open [Updates.xml (linux_x64)](https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/Updates.xml) to see what package(s) can be installed.

Thanks for confirming what I thought I'd found.

**Comment by sionhughes** [comment]
> There are many space to improve for the tools installation.
> If you know the tools well, could you help me/us to improve it?
> 
> * Automatically detect an available version and its URL.
> * CLI interface to list available tools and versions

I'm not a Python expert, but if there's anyway I can help, please let me know.

**Comment by miurahr** [comment]
>  if there's anyway I can help, please let me know.
Thank you.

I have not been still confused with versioning rule for the tools.

For example, [Update.xml](https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/Updates.xml) indicate a version "4.1.0-202104091029" but directory where package stored named "qt.tools.ifw.41/" then file is " 4.1.0-202104091029ifw-linux-x64.7z"

For openSSL things are different,  version "1.1.1-4"  folder "qt.tools.openssl.gcc_64/" and filename is " 1.1.1-4openssl-1.1.1d_prebuild_rhel7_6.7z"

I'm not sure what logic can be used to construct these version, folder name and filename, that is information for making correct URLs,  from keyword such as "IFW" or "OpenSSL".

It seems inconsistent and ad-hoc, and I don't want to maintain these data in installer application by hand.

Any ideas?

**Comment by ddalcino** [comment]
> I'm not sure what logic can be used to construct these version, folder name and filename, that is information for making correct URLs, from keyword such as "IFW" or "OpenSSL".

I think I might be able to help with this. In both of the cases you mention here, the filenames can be composed from elements from the XML file.

Here's an example XML file, abridged just to show the important stuff:
```xml
<Updates>
  <PackageUpdate>
    <Name>qt.tools.ifw.41</Name>
    <Version>4.1.0-202104091029</Version>
    <DownloadableArchives>ifw-linux-x64.7z</DownloadableArchives>
  </PackageUpdate>
</Updates>
```

The link to the downloadable file is `qt.tools.ifw.41/4.1.0-202104091029ifw-linux-x64.7z`. That's the same as `f"{Name}/{Version}{DownloadableArchives[0]}`. Keep in mind that DownloadableArchives is actually a list of strings, separated by commas.

For openSSL, we have:

```xml
<Updates>
  <PackageUpdate>
    <Name>qt.tools.openssl.gcc_64</Name>
    <Version>1.1.1-4</Version>
    <DownloadableArchives>openssl-1.1.1d_prebuild_rhel7_6.7z</DownloadableArchives>
  </PackageUpdate>
</Updates>
```
The link to the downloadable file is `qt.tools.openssl.gcc_64/1.1.1-4openssl-1.1.1d_prebuild_rhel7_6.7z`. That's also `f"{Name}/{Version}{DownloadableArchives[0]}`.

Each folder ('qt.tools.openssl.gcc_64', 'qt.tools.ifw.41', etc) always contains the file `f"{Version}meta.7z"`, and `.sha1` files that correspond to each download.

I agree, it definitely looks ad-hoc and confusing, but I think that's mostly because many of these projects are maintained by different groups and use different naming/versioning schemes. However, it appears that the XML files are sufficient to determine what the URLs should be.

**Comment by ddalcino** [comment]
> There are many space to improve for the tools installation.
> If you know the tools well, could you help me/us to improve it?
> 
> * Automatically detect an available version and its URL.
> * CLI interface to list available tools and versions

I might be able to help with this, as long as the user can tell me what directory within https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/ they want to look at (or windows, or mac, etc). The 'Updates.xml' files within those directories look like they can tell you everything you need to know.

https://download.qt.io/online/qtsdkrepository/linux_x64/root/qt/Updates.xml appears to contain a directory of all the contents within https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/, as well as the 'android' directory, but the file is missing several directories, and it lists several directories that don't exist. 

If you need to list all the directories within https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/, I think I could scrape the webpage with BeautifulSoup, but that will only work until the Qt devs redesign the webpage. They haven't done so in the 5 years I've been using Qt, and I doubt that they ever will, but that's a pretty big assumption on my part.

**Comment by miurahr** [comment]
Improvement is progressed on #235
