### ISSUE TITLE
Allow setting a different base URL 

### ISSUE THREAD

**Issue by nelsonjchen** [miurahr/aqtinstall#24]
As seen in #22, and seen in https://github.com/miurahr/aqtinstall/issues/20#issuecomment-495966340, there seems to be intermittent issues with the `https://download.qt.io/online/qtsdkrepository/` URL that's currently hardcoded in. 

I'm not sure what's going on, but it might be worth allowing an option or environment variable to set this to a different URL. Setting this to UC Berkeley's mirror at http://mirrors.ocf.berkeley.edu/qt/online/qtsdkrepository/ seems to be more reliable for me. It shouldn't be the default though, but it might be worth having an option to set it to that if the user desires so.

**Comment by miurahr** [comment]
`https://download.qt.io/` uses [MirrorBrain](http://mirrorbrain.org/) to control mirror selection. Recent modification is depends on mirrorbrains feature that is metalink that provide mirror URLs in XML format.
https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5130/Updates.xml.meta4 is a example how it works.
Mirror sites such as UC Berkleys site does not provide such information.

We can use `download.qt.io`  as a default reference and a metalink source,  and then allowing users to specify mirror URL to fetch.

**Comment by miurahr** [comment]
I've pushed an implementation. Cloud @nelsonjchen  test it? 
And could you add CI test for mirror as test yaml generator?

**Comment by nelsonjchen** [comment]
Sure thing.

**Comment by miurahr** [comment]
Added
