### ISSUE TITLE
bad version comparison

### ISSUE THREAD

**Issue by tsteven4** [miurahr/aqtinstall#260]
The compare at L86 will not give the desired result for some versions, e.g. 5.12.10.  That is 51210 is >= 5130.

https://github.com/miurahr/aqtinstall/blob/bffc4b81a7c528779a42a082306274523f65ff9b/aqt/archives.py#L78-L86

As a result the list command can fail:
```
tsteven4@focal:~/.local/lib/python3.8/site-packages$ aqt list 5.12.10 linux desktop
2021-06-09 09:44:21,765 - aqt - INFO - aqtinstall(aqt) vunknown on Python 3.8.5 [CPython GCC 9.3.0]
Traceback (most recent call last):
  File "/home/tsteven4/.local/bin/aqt", line 8, in <module>
    sys.exit(main())
  File "/home/tsteven4/.local/lib/python3.8/site-packages/aqt/__init__.py", line 38, in main
    return cli.run()
  File "/home/tsteven4/.local/lib/python3.8/site-packages/aqt/installer.py", line 675, in run
    return args.func(args)
  File "/home/tsteven4/.local/lib/python3.8/site-packages/aqt/installer.py", line 482, in run_list
    pl = PackagesList(qt_version, host, target, BASE_URL)
  File "/home/tsteven4/.local/lib/python3.8/site-packages/aqt/archives.py", line 92, in __init__
    self._get_archives()
  File "/home/tsteven4/.local/lib/python3.8/site-packages/aqt/archives.py", line 119, in _get_archives
    self.update_xml = ElementTree.fromstring(r.text)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 49
```
In addition, 5.12.11 needs to be added to combinations.json.

**Comment by ddalcino** [comment]
I noticed this earlier as well. Thank you for making this issue, I probably would have forgotten to do so.

This comparison cannot be done safely as an integer; I think it should be done using a Version class that supports comparisons. I wound up using Version objects from [the semantic-version library](https://pypi.org/project/semantic-version/) in #235, but I didn't realize that the project already uses the Version class in [the packaging library](https://packaging.pypa.io/en/latest/version.html), in [`Cli._set_arch()`](https://github.com/miurahr/aqtinstall/blob/master/aqt/installer.py#L147). I don't know which library is better for this purpose.

I think it would make a lot of sense to change `self.version` from a string to an actual Version object in the PackagesList constructor.

**Comment by miurahr** [comment]
> aqt - INFO - aqtinstall(aqt) vunknown on Python 3.8.5 [CPython GCC 9.3.0]

Self version is also broken, so it said unknown version.

**Comment by miurahr** [comment]
When using packaging.version for tool version

```
 v = Version("4.15.1-0-202106081224")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/miurahr/.virtualenvs/aqtinstall/lib/python3.8/site-packages/packaging/version.py", line 277, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
packaging.version.InvalidVersion: Invalid version: '4.15.1-0-202106081224'
```

it does not recongnized as version string.

**Comment by ddalcino** [comment]
I was just thinking about using a Version object to store versions of Qt, which are not as complicated as "4.15.1-0-202106081224". But you are right; it would probably be useful to use Version objects for the tools as well.

The [semantic-version library](https://pypi.org/project/semantic-version/) would automatically parse that string into:
```python
Version(
  major=4,
  minor=15,
  patch=1,
  prerelease=('0-202106081224',)
)
```

Maybe it would be worth it to check all the version numbers in the tools, and see if there are any that semantic-version can't handle?

**Comment by miurahr** [comment]
Does #263 solve the case? @tsteven4

**Comment by miurahr** [comment]
> Version("5.12.10") < Version("5.13.0")
True

**Comment by miurahr** [comment]
It seems to better to use semantic_version rather than packaging.version.
> The semantic-version library would automatically parse that string into:

**Comment by miurahr** [comment]
@ddalcino could you review #263 ?

**Comment by miurahr** [comment]
Merged
