### ISSUE TITLE
"invalid header data" and timeout

### ISSUE THREAD

**Issue by Saviq** [miurahr/aqtinstall#277]
Some mirror health checks not working well, we're seeing this in CI:

```
$ python3 -m aqt install 5.15.2 mac desktop -O /Users/cibot/actions-runner/_work/multipass-private/multipass-private/build/Qt
2021-06-22 02:18:49,274 - aqt - INFO - aqtinstall(aqt.installer) vunknown on Python 3.9.1 [CPython Clang 11.0.0 (clang-1100.0.33.17)]
Download error: invalid header data
```

The job then times out as `aqtinstall` is stuck in this case.

**Comment by miurahr** [comment]
The error happened when extraction of archive in installer.in:727
```
        with py7zr.SevenZipFile(archive, "r") as szf:
            szf.extractall(path=base_dir)
```

You seems to use aqtinstall version that has a logging bug and version print bug.
Could you try to use v1.2.0 released recently?

**Comment by Saviq** [comment]
Indeed, that seems to work, thanks!
