### ISSUE TITLE
How to install Qt libraries for  linux Armx64 and ix64 and WindowsIoTx64 versions?

### ISSUE THREAD

**Issue by vishnucool220** [miurahr/aqtinstall#284]
right now i sue `python3 -m aqt install --outputdir /mnt/c/QtforLinux 5.15.2 linux desktop -m qtcore qtxml qtnetworkauth qtnetwork` for linux desktop. How can i build/ Qt for linux Armx64 and ix64 and WindowsIoTx64 versions?

**Comment by ddalcino** [comment]
> How can i build/ Qt for linux Armx64 and ix64 and WindowsIoTx64 versions?

Can you please clarify what you mean by this? aqt downloads archives from https://download.qt.io/online/qtsdkrepository/; if you can find an archive somewhere at that URL that you're trying to install, then we can help you. As far as I know, "Armx64", "ix64", and "WindowsIoTx64" are not supported platforms. You might need to build Qt from source.

**Comment by miurahr** [comment]
There is no clarification for the original question.
