### ISSUE TITLE
`aqt/combinations.json` can be generated using `aqt list`

### ISSUE THREAD

**Issue by ddalcino** [miurahr/aqtinstall#307]
I've noticed that over time, `aqt/combinations.json` loses sync with the Qt repository, and needs to be updated manually. I think that it should be possible, using `aqt list`, to re-generate/update the whole file using a program. I think that I could do this, but I have some questions before I start:

1. Is this something that we want to add to the project?
2. Would it be a separate program, or would we add it as a subcommand to aqt, like `python -m aqt update-combos`?
3. Should it run in CI, and cause the build to fail if the current `aqt/combinations.json` file is not up to date?

Keep in mind that this command would necessarily make a whole lot of GET requests to the Qt repo:
```
3 hosts * 3 targets * (1 html page + N Updates.xml files)
```

I think it would make sense for the aqt developers to run this command periodically, but it might be a big problem if everyone who uses aqt decides to run it in their CI. The Qt people won't be happy if we use up an excessive amount of their bandwidth.

**Comment by miurahr** [comment]
It would be good to run with CI(github actions), that run periodically,  weekly or monthly.
When running check, it can retrieve data from the site, and generate json file, then compare it with current one.
If it need to be updated, job will be failed and show recommended updates in log, or upload to artifact storage.
Maintainer can copy and paste, or download json from github actions storage.

A program should be separate one, because only maintainer should run.

**Comment by ddalcino** [comment]
Maybe the script could be run by a bot, like the Github dependabot checks your dependencies have CVEs, and opens a PR that updates the dependency?

**Comment by miurahr** [comment]
@ddalcino  you can use PyGithub for the purpose.
It also allow us to make PR.

https://pygithub.readthedocs.io/en/latest/examples/PullRequest.html#create-a-new-pull-request

**Comment by miurahr** [comment]
It is relatively easy to post a comment to an issue ticket.

```
        body = "comment comment comment"
        body += "\n   Posted from [the action](https://github.com/{}/actions/runs/{})\n".format(self.repository, self.run_id)
        token = os.getenv("GITHUB_TOKEN")
        g = github.Github(token)
        repo = g.get_repo(self.repository)
        issue = repo.get_issue(number=123)
        issue.create_comment(body)
```
