### ISSUE TITLE
Ctrl-C during install does not work on windows

### ISSUE THREAD

**Issue by nikitalita** [miurahr/aqtinstall#336]
On linux, ctrl-c works during install, albeit with a fatal error:
```
KeyboardInterrupt
Exception in thread Thread-1:
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0xcbb520)

Thread 0x00007fa8ad7f5700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 1202 in invoke_excepthook
  File "/usr/lib/python3.8/threading.py", line 934 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007fa8b21eb740 (most recent call first):
<no Python frame>
Aborted
```

Due to the way that aqt uses multiprocessing to start multiple processes on windows (i.e. no fork, just starting multiple instances) means that ctrl-c does not terminate all the processes on windows, and results in aqt hanging after a certain point in the downloads. The processes respawn after you end them, so you will have to kill all of them at the same time in order to terminate them.

I recommend implementing something like this solution here to fix this:
https://stackoverflow.com/questions/11312525/catch-ctrlc-sigint-and-exit-multiprocesses-gracefully-in-python

**Comment by miurahr** [comment]
@nikitalita does #337 works for you?

**Comment by miurahr** [comment]
#337 is merged.
