### ISSUE TITLE
Feature:  QtCreator installation

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#34]

**Comment by miurahr** [comment]
The tool is for unattended installation. QtCreator is a tool for GUI operation for developer, where developer can run GUI installer.
I wont install QtCreator package.

**Comment by mardy** [comment]
But QtCreator is also used to install qbs, so it would be nice if we could install it via aqt too.

**Comment by miurahr** [comment]
qbs package is [here](https://download.qt.io/official_releases/qbs/1.17.0/) that may not require QtCreator.

**Comment by mardy** [comment]
Nice, thanks! :-)
