### ISSUE TITLE
Exception Specified 7zip command executable does not exist:

### ISSUE THREAD

**Issue by billpriest** [miurahr/aqtinstall#347]
Trying the following command on Chromebook crostini (debian buster)
aqt --external /usr/bin/7z install 5.15.2 linux desktop

Traceback (most recent call last):
  File "/usr/local/bin/aqt", line 5, in <module>
    from aqt.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/aqt/__init__.py", line 25, in <module>
    from aqt.cli import Cli
  File "/usr/local/lib/python2.7/dist-packages/aqt/cli.py", line 83
    raise Exception('Specified 7zip command executable does not exist: {!r}'.format(sevenzip)) from e

I verified that /usr/bin/7z exists and runs

**Comment by ddalcino** [comment]
Can you show us the output for `aqt --version`? That looks like an out-of-date version of aqt.

Also, it may help if you run it using python3. aqt is not expected to work with python2.7.

**Comment by billpriest** [comment]
Ok. installed python3 version and python3 -m aqt version gives
aqtinstall(aqt) v1.2.4 on Python 3.7.3 [CPython GCC 8.3.0]
Ok after playing around I got it to work; but not w/ the above cmd (which I saw on the wiki, IIRC)

python3 -m aqt install -E /usr/bin/7z 5.15.2 linux desktop

**Comment by billpriest** [comment]
I could not get python2.7 w/ the same cmd line to work (same error as originally); might want to "strongly suggest" people use python3.

**Comment by ddalcino** [comment]
Python 3 is required: https://github.com/miurahr/aqtinstall#requirements

You have a fair point though. Modern linux systems symlink `python` to some version of python 3, but older systems often symlink it to python 2.7. Perhaps the readme could suggest that you run aqt with `python3 -m aqt`?

**Comment by miurahr** [comment]
This is duplicated with #184

I've set `python_requires` version to minimum 3.6.

https://github.com/miurahr/aqtinstall/blob/ab823596dce3be90bb3e245fc35a63acc43cd9a8/setup.cfg#L33

It should failed when installing on  older  python versions,  except when users using too older `pip` command(< [pip v9.0.0](https://pip.pypa.io/en/stable/news/#v9-0-0) ).

It would be better to check python version in main function.
