### ISSUE TITLE
Question: Can aqt install qtcreator?

### ISSUE THREAD

**Issue by billpriest** [miurahr/aqtinstall#348]
I was trying to install the latest qtcreator w/o the "online/offline" installer both of which have issues w/ the platform plugin.

**Comment by ddalcino** [comment]
The prerelease versions of aqt (v2.0.0b5) can install qtcreator using this command:

``` bash
    $ aqt tool <host> <target> tools_qtcreator
```

The stable release of aqt (v1.2.4) has an older version of the `aqt tool` subcommand; using it will require that you read some Updates.xml files at https://download.qt.io/online/qtsdkrepository/ to find out the version and PackageUpdate that you want to install; I do not recommend this.

However, you mentioned before that you were running debian buster on a Chromebook. In my experience, Debian runs in a VM on Chromebooks, and it cannot launch GUI apps. Be aware that this might be a problem.

**Comment by billpriest** [comment]
Hi David,
  Thanks for the info.  I'll give it a shot.  It seems crostini has come a long way, I can run all kinds of GUI apps (gitkraken, emacs, qtcreator, etc.) w/o any serious issue.  There are some visual quirks in qtcreator (pop-up windows that don't stay in the viewable area if you click too near the top of the editor window; I mostly use shortcuts so it is doesn't bother me much).  There is an issue using the debugger where I try to click on a set breakpoint that it pops up the complete list of breakpoints which I really dislike (tooltips on steroids).  I'll provide feedback.  What is it looking for <target>?

**Comment by billpriest** [comment]
In case someone else tries qtcreator on debian, there is a missing liib libxcb-util.so.1 which can be fixed by making a sym link to libxcb-util.so.  QtCreator 4.15.2 works like a charm w/o the obnoxious "breakpoint popup".
