### ISSUE TITLE
Docs: remember to update the version number in conf.py

### ISSUE THREAD

**Issue by pzhlkj6612** [miurahr/aqtinstall#380]
Hi.

On https://aqtinstall.readthedocs.io/en/latest/ , I got "aqtinstall 1.0.0b2 documentation" from its title; in the PDF file downloaded from https://aqtinstall.readthedocs.io/_/downloads/en/latest/pdf/ , I got "Release 1.0.0b2" from its cover and header. The version number of "1.0.0b2" does not match the version I selected.

This version number is defined in /docs/conf.py. It seems that it has not been updated for a long time:

https://github.com/miurahr/aqtinstall/blob/4f0d92dc977ca9255f7ac912e1fd4fc303e953c1/docs/conf.py#L59-L67

I think we need to update it before releasing each version, otherwise it may confuse the user.

The docs of Sphinx: https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

**Comment by ddalcino** [comment]
Good point.

Would it be possible to pull that information in automatically in some way? The file `aqt/version.py` contains a version number, and it appears to be generated automatically, by the root-level `setup.py`; maybe we could leverage the code that generates that version number to update the number in `docs/conf.py`. Another possibility would be a CI script that checks the version numbers in `docs/conf.py`, and maybe even the latest changelog entry.

It's hard to remember to update those numbers without a tool to remind you.

**Comment by pzhlkj6612** [comment]
> It's hard to remember to update those numbers without a tool to remind you.

I agree with you.

> Would it be possible to pull that information in automatically in some way? The file `aqt/version.py` contains a version number, and it appears to be generated automatically, by the root-level `setup.py`;

Yes, it is possible.

In this repository, I cannot find any CI scripts for publishing documents, so I guess @miurahr has configured a [webhook](https://docs.readthedocs.io/en/stable/webhooks.html) to let GitHub notify Read The Docs to fetch the latest content. To use the version information defined in the "/aqt/version.py" file, I think we need to do the following things:

1. Remove the webhook.
2. Use the generated version number. Add `from aqt.version import __version__` to "/docs/conf.py" and replace the values of `version` and `release` fields with `__version__` .
3. Create a series CI steps in "/.github/workflows/publish-to-test-pypi.yml" for building and publishing documents. These steps must be placed after the step used to build aqtinstall.

It is also feasible to overwrite the value defined in "/docs/conf.py" by passing the [`-D setting=value`](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-D) parameter when building documents, but we need to manually obtain the version number defined in "/aqt/version.py" first.

> ... Another possibility would be a CI script that checks the version numbers in `docs/conf.py`, and maybe even the latest changelog entry.

Hmm, I think it might be harder.

**Comment by miurahr** [comment]
>  I guess @miurahr has configured a webhook to let GitHub notify Read The Docs to fetch the latest content. 
Yes the webhook is configured.

**Comment by pzhlkj6612** [comment]
> Document is built on readthedocs for each master branch and release tags.
> https://readthedocs.org/projects/aqtinstall/

> > I guess **miurahr** has configured a webhook to let GitHub notify Read The Docs to fetch the latest content.
> 
> Yes the webhook is configured.

Yes. Due to the existence of the webhook, Read The Docs will automatically fetch and build the documents when we update the "master" branch of the GitHub repository.

To use the version number that is generated by setuptools_scm, we have to build the documents, and then upload it to Read The Docs by ourselves; to keep the documents up to date all the time, we need to configure some CI steps to perform these operations (as I said in the [previous comment](https://github.com/miurahr/aqtinstall/issues/380#issuecomment-912172278)).

It seems that you didn't fully understand what I said; please let me know if anything is unclear.

**Comment by miurahr** [comment]
Thank you for suggestions.  Now [latest document](https://aqtinstall.readthedocs.io/en/latest/) has version and release number as same as version.py `version.__version__`  by provisioning readthedocs build configuration in #389.
