### ISSUE TITLE
download subset of Qt archives

### ISSUE THREAD

**Issue by christian-rauch** [miurahr/aqtinstall#382]
Installing Qt 5 via `aqt install-qt linux desktop 5.15.0 -O /tmp/qt5` installs all Qt modules:
```
Finished installation of qtx11extras-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.71937164
Finished installation of qtgraphicaleffects-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.77704628
Finished installation of qtmultimedia-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 1.01185634
Finished installation of qtwebchannel-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.70400073
Finished installation of qtsvg-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.78706911
Finished installation of qtimageformats-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.83330416
Finished installation of qttranslations-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 2.18718076
Finished installation of qtxmlpatterns-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 1.50350368
Finished installation of qtsensors-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 1.02667443
Finished installation of qtserialport-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.76764962
Finished installation of qtdeclarative-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 5.43281253
Finished installation of qtwebsockets-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.84494731
Finished installation of qtlocation-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 1.50010507
Finished installation of qtquickcontrols-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.86891522
Finished installation of qttools-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 6.61603144
Finished installation of qtquickcontrols2-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 1.06033469
Finished installation of qtserialbus-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.72838429
Finished installation of qt3d-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 1.82034966
Finished installation of qtgamepad-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.57711037
Finished installation of qtwebview-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.69777803
Finished installation of qtscxml-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.85858923
Finished installation of qtspeech-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.73382153
Finished installation of qtwayland-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.96721451
Finished installation of qtremoteobjects-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.76588981
Finished installation of icu-linux-Rhel7.2-x64.7z in 3.02323434
Finished installation of qtbase-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 14.54454740
Finished installation of qtconnectivity-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z in 0.96517617
Finished installation of qt-5.15.0-linux.7z in 3.66924698
```

There is no way to select only a subset of these modules, e.g. {qtbase, qtdeclarative, icu}. An option to download only a subset would greatly improve the space and bandwidth efficiency for automated build tasks. These modules are not listed amongst the additional modules `aqt list-qt linux desktop --modules 5.15.0`.

**Comment by ddalcino** [comment]
Check the `PackageUpdate.DownloadableArchives` from https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_5150/Updates.xml:

```xml
<PackageUpdate>
  <Name>qt.qt5.5150.gcc_64</Name>
  <DisplayName>Desktop gcc 64-bit</DisplayName>
  ...
  <DownloadableArchives>
    qtbase-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtconnectivity-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtx11extras-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtwebchannel-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtmultimedia-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qttranslations-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtgraphicaleffects-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtsvg-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtdeclarative-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtwebsockets-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtimageformats-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qttools-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtxmlpatterns-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtsensors-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtserialport-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtlocation-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtquickcontrols-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtquickcontrols2-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qt3d-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtwebview-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtserialbus-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtscxml-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtgamepad-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtspeech-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtwayland-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, qtremoteobjects-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z, icu-linux-Rhel7.2-x64.7z, qt-5.15.0-linux.7z
  </DownloadableArchives>
  ...
</PackageUpdate>
```

These archives are all part of the base Qt-gcc_64 package; they are not 'modules' as defined by `aqt`. Modules are encapsulated in other PackageUpdates. 

It would is possible to filter the archives, but I'm not sure you can guarantee that you'd have a working Qt after removing some of these. If you want to hack on this, the relevant code is at: 

https://github.com/miurahr/aqtinstall/blob/master/aqt/archives.py#L240-L250

The `archive` variable will hold something like `qtbase-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z`, and `archive_name` would be `qtbase` in that case.

**Comment by pzhlkj6612** [comment]
Hi.

> There is no way to select only a subset of these modules... These modules are not listed amongst the additional modules `aqt list-qt linux desktop --modules 5.15.0`.

Copied from https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_5150/Updates.xml :

```xml
<Updates>
    <PackageUpdate>
        <Name>qt.qt5.5150.gcc_64</Name>
        <DisplayName>Desktop gcc 64-bit</DisplayName>
        <Description>Qt 5.15.0 Prebuilt Components for Desktop gcc 64-bit</Description>
        <Version>5.15.0-0-202005140804</Version>
        ...
        <DownloadableArchives>qtbase-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z... qtdeclarative-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z... icu-linux-Rhel7.2-x64.7z...</DownloadableArchives>
        ...
```

The *modules* you mentioned are **required** components of the "qt.qt5.5150.gcc_64" package. In the context of aqtinstall, the name "modules" do not refer to these components, but qtcharts, qtwebengine, and so on. In normal installation, the "modules" are **optional**.

> An option to download only a subset would greatly improve the space and bandwidth efficiency for automated build tasks.

Yes, I would agree with you, but I don't know whether it is feasible to install a "partial" Qt. You can try it yourself by downloading the package you are interested in from https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_5150/qt.qt5.5150.gcc_64/ .

**Comment by pzhlkj6612** [comment]
Oops, @ddalcino .

**Comment by christian-rauch** [comment]
It is definitely possible to use only submodules. Before considering `aqtinstall`, I was using a custom bash script to download these three submodules and compiled a Qt Creator plugin with them.

Some Linux distributions (Ubuntu, ...) also separate these packages, e.g. [`qtbase5-dev`](https://packages.ubuntu.com/hirsute/qtbase5-dev) and [`qtdeclarative5-dev`](https://packages.ubuntu.com/hirsute/qtdeclarative5-dev) to not install all of Qt.

**Comment by ddalcino** [comment]
> It is definitely possible to use only submodules. Before considering `aqtinstall`, I was using a custom bash script to download these three submodules and compiled a Qt Creator plugin with them.
> 
> Some Linux distributions (Ubuntu, ...) also separate these packages, e.g. [`qtbase5-dev`](https://packages.ubuntu.com/hirsute/qtbase5-dev) and [`qtdeclarative5-dev`](https://packages.ubuntu.com/hirsute/qtdeclarative5-dev) to not install all of Qt.

OK, that's very interesting. You are right, some of these archives are very large and unnecessary.

What kind of command line interface would you expect for this feature, in `aqt install-qt` and `aqt list-qt`? 

It might be nice to give people a 'minimal' option that gives them a the minimal set of submodules required for a working Qt installation. Would that just be `qtbase`, or are some of the others required for a working install?

Does anyone know what `qt-5.15.0-linux.7z` is supposed to be? I downloaded it because it looked important, but it just contains empty folders.

**Comment by christian-rauch** [comment]
> What kind of command line interface would you expect for this feature, in `aqt install-qt` and `aqt list-qt`?

I would expect that they are handled like the other Qt modules. I.e. `list-qt` should list `qtbase`, `qtdeclarative` and `icu` next to the "extension" modules that are already listed and that they can also be passed via the `-m` argument.

> Would that just be qtbase, or are some of the others required for a working install?

Yes, I think `qtbase` gives you a minimal Qt installation. But this will only contain the base classes. I don't know if that is sufficient to build a basic GUI application.
I personally would still prefer if a user can choose the subset of modules as most of the modules will not be used by a particular project. The default behaviour could still be to download all of the "standard" modules.

**Comment by ddalcino** [comment]
Just so we can quantify the savings in bandwidth that we're talking about, here are some numbers, as reported by the repo and the xml file:

* qtbase: 17M
* icu: 7.5M
* qttools: 5.3M
* qt3d: 3.8M
* qtdeclarative: 3.7M
* qtlocation: 2.2M
* qtquickcontrols: 1.7M
* Everything else is 1.1M or less
* The total for all submodules in the qt.qt5.5100.gcc_64 module: 47.8M

By using this feature, if you only wanted the qtbase.7z archive, you would save 30.8M in bandwidth, or ~64% of what you would have used by downloading the whole PackageUpdate.

**Comment by ddalcino** [comment]
> I would expect that they are handled like the other Qt modules. I.e. `list-qt` should list `qtbase`, `qtdeclarative` and `icu` next to the "extension" modules that are already listed and that they can also be passed via the `-m` argument.

I think you are still conflating 'modules' with '7z archive files'. I don't want to start mixing up the meanings of these words; that will make a needlessly confusing command line interface. In fact, I think it would be helpful to us if you changed the title of this issue to something more like 'download subset of base qt 7z archives`, just so we can track this issue appropriately.

 Many of the other 'modules', as defined by aqt, include multiple '7z archive files'; for an example, see `qt.qt6.620.debug_info.gcc_64` in https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_620/Updates.xml. `qt.qt6.620.debug_info.gcc_64` is 964M if you don't split it up. If we give users the ability to split the base Qt PackageUpdate into 7z archives, why would we not do the same for the modules?

One option would be to replace the whole 'modules' system with one long list of '7z archive files' that users can pick and choose from.

**Comment by christian-rauch** [comment]
I don't know what the terminology here is (there seem to be "packages" and "archives"). At the lowest level, those are all separate archives and you cannot split further than this. I change the title accordingly to "archives".

Some of the modules are split into library, documentation, examples, and debug info. But the Qt default installation further splits these libraries into `qtbase`, `qtdeclarative`, `icu` etc. I don't know what the best approach for the command-line interface is.

**Comment by christian-rauch** [comment]
I totally missed that command line option. From the interface, I probably expected that those are just part of the modules.

From a technical perspective, modules and archives are different since they refer to different parts of the XML metadata. But from a user perspective, this does not matter in my opinion as the user should not care about the structure of the repository. The user is just interested in the individual parts that make up the Qt installation.

Other than merging `--modules` and `--archives`, I don't have good advice on how to make this better visible in the user interface and the manual.

**Comment by ddalcino** [comment]
> But from a user perspective, this does not matter in my opinion as the user should not care about the structure of the repository. The user is just interested in the individual parts that make up the Qt installation.

I think I understand where you're coming from. 

Unfortunately, if we merge modules and archives, that would be a huge breaking change in the interface, and it would break a lot of people's code. Currently, about 30 archives exist in the base module you get when you `aqt install-qt 5.15.0`.  By merging modules with archives, those 30 archives would necessarily become opt-in rather than opt-out. Any users that depend on those archives would need to change their CI code to specify which of those 30 archives they need.

The current behavior is modeled after the official Qt GUI installer, which only gives you the option to install the modules you can print using `aqt list-qt --modules`. That installer doesn't give you the option to filter out archives you don't need. 

> Other than merging `--modules` and `--archives`, I don't have good advice on how to make this better visible in the user interface and the manual.

I think we might be able to do it by adding options to `aqt list-qt` that let you see what archives are contained in the modules, and adding a short tutorial for the feature in the 'Getting Started' section.

**Comment by christian-rauch** [comment]
> By merging modules with archives, those 30 archives would necessarily become opt-in rather than opt-out. Any users that depend on those archives would need to change their CI code to specify which of those 30 archives they need.

The behaviour could be that by default, all "standard" archives are installed. Only when a user selects one of the archives from the "standard" package as a module to be installed, all other required archives also have to be passed as module.

Since my original issue (no way to install subset of Qt) has been resolved by the `--archives` flag, I am going to close this issue.

**Comment by miurahr** [comment]
> The behaviour could be that by default, all "standard" archives are installed. Only when a user selects one of the archives from the "standard" package as a module to be installed, all other required archives also have to be passed as module.

This is exactly what ``--archives`` flag doing, and it is not recommended to user who is **just** interested in installing Qt.
It is an *advanced* feature for developer who knows well like @christian-rauch 
It was discussed in #126 "Installing smaller subset of the libraries"
