### ISSUE TITLE
Link to document on PyPI project page

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#387]
It is better to have documentation link on PyPI project page.

Here is most recent dev version.
https://test.pypi.org/project/aqtinstall/2.0.0rc3.dev18/

It would be necessary to update metadata defined in setup.cfg

Here is an example pip command page, that have several project links.

![image](https://user-images.githubusercontent.com/123720/131778674-e6eb59cf-8cdb-4152-af11-d9973d35fe9c.png)

**Comment by miurahr** [comment]
Relevant configurations on metadata (on pip project) is:

```
    url="https://pip.pypa.io/",
    project_urls={
        "Documentation": "https://pip.pypa.io",
        "Source": "https://github.com/pypa/pip",
        "Changelog": "https://pip.pypa.io/en/stable/news/",
    },
```

**Comment by pzhlkj6612** [comment]
Relevant document: [project_urls § Packaging and distributing projects — Python Packaging User Guide](https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls)
