### ISSUE TITLE
All Windows Builds and All Mac Builds except one are currently failing.

### ISSUE THREAD

**Issue by nelsonjchen** [miurahr/aqtinstall#39]
https://dev.azure.com/miurahr/github/_build/results?buildId=797

The recent py7zr change seems to be related. The stack trace looks like it fails on setting file modification times on some output files.

**Comment by miurahr** [comment]
Errors happened with include/QtScript/qtscript-config.h that size is 0byte.
It seems to be a bug on py7zr.
