### ISSUE TITLE
Allow `list-qt` to print a list of archives for use with the `--archives` option

### ISSUE THREAD

**Issue by ddalcino** [miurahr/aqtinstall#394]
Let's say you want to install Qt 5.15.0 for linux desktop, but only install the 7z archives for {qtbase, qtdeclarative, icu}. You would use this command:

```
aqt install-qt linux desktop 5.15.0 --archives qtbase qtdeclarative icu
```

This feature is documented  at https://aqtinstall.readthedocs.io/en/latest/cli.html#cmdoption-list-tool-archives, and there's an example under https://aqtinstall.readthedocs.io/en/latest/cli.html#command-examples; it's the third example in the list. 

I think it would be useful to add an option that lists archives to `list-qt`, but I cannot do it without an idea of what the interface would look like. I would like to use this issue to figure out what that interface would look like.

_Originally posted by @ddalcino in https://github.com/miurahr/aqtinstall/issues/382#issuecomment-911653563_

**Comment by ddalcino** [comment]
Part of the problem here is that in order to print a list of the archives you can choose from, you need to know the version of Qt, the architecture (see #371; I think it really makes a difference here), and which modules the user wants. Most modules only include a single archive, but many of them include several. For instance, the `debug_info` module contains dozens of modules, and it's nearly 1GB if you try to install them all.

Here are some potential interfaces:
1. Use `--archives` flag to pass in a Qt version number and a list of modules, and then print all of the archives for those modules. This would print all of the archives as one long list, so you cannot easily tell which module each archive belongs to.
    ```bash
    aqt list-qt windows desktop --archives 5.15.2 win32_mingw81 qtcharts debug_info  # archives for base and modules
    aqt list-qt windows desktop --archives 5.15.2 win32_mingw81                      # archives just for base Qt
    ```
2. Add separate flags for the base and modules, and only print archives pertinent to one module at a time.
    ```bash
    aqt list-qt windows desktop --base-archives 5.15.2 win32_mingw81               # archives just for base Qt
    aqt list-qt windows desktop --module-archives 5.15.2 win32_mingw81 qtcharts    # archives just for qtcharts
    aqt list-qt windows desktop --module-archives 5.15.2 win32_mingw81 debug_info  # archives just for debug_info
    ```
3. Add a `--long-archives` flag that prints a table, just like the `--long` flag we used for `list-tool`.
    ```console
    $ aqt list-qt windows desktop --long-archives 5.15.2 win32_mingw81 qtcharts debug_info  # print a table
    Module       | Archives
    ===========================
    Base 5.15.2  | qtbase 
                 | qtdeclarative 
                 | icu
                 | ...
    qtcharts     | qtcharts
    debug_info   | ... all the archives for debug_info, on separate lines ...
    ```

**Comment by pzhlkj6612** [comment]
Or this?

```shell
aqt list-qt windows desktop --archives 5.15.2 win32_mingw81 qtcharts debug_info  # archives for modules only
aqt list-qt windows desktop --archives 5.15.2 win32_mingw81                      # archives for base Qt only
```

**Comment by ddalcino** [comment]
> Or this?
> 
> ```shell
> aqt list-qt windows desktop --archives 5.15.2 win32_mingw81 qtcharts debug_info  # archives for modules only
> aqt list-qt windows desktop --archives 5.15.2 win32_mingw81                      # archives for base Qt only
> ```

I think this proposal makes more sense to me than the three possibilities that I came up with, so unless anyone has any objections, I will plan on implementing this. Thank you @pzhlkj6612
