### ISSUE TITLE
Support of SQL plugins

### ISSUE THREAD

**Issue by Fettpet** [miurahr/aqtinstall#406]
At the moment the SQL plugins must be installed by hand from the sources. It would be nice if the aqtinstaller supports the installation of the plugins

**Comment by ddalcino** [comment]
Is there a repo of prebuilt SQL plugins for Qt somewhere? I haven't seen anything like that at download.qt.io.

Do you mean "built from source by hand"? If so, I think this would be out of scope for aqtinstall. We don't have any mechanism for building code, or for hosting qt binaries that we have built. Aqtinstall is simply a script that installs pre-existing binaries from a repository.

**Comment by Fettpet** [comment]
_Is there a repo of prebuilt SQL plugins for Qt somewhere?_ 

I think there is no prebuild SQL plugin. Since the reason for the plugins are complicated dependencies:
> Due to the practicalities of dealing with external dependencies, only the SQLite3 plugin is shipped with binary builds of Qt. To be able to add additional drivers to the Qt installation without re-building all of Qt, it is possible to configure and build the qtbase/src/plugins/sqldrivers directory outside of a full Qt build directory

_Do you mean "built from source by hand"?_

The plugins must be build with the path to the dependencies. For example the mysql plugin can be build like
```
cd %QTDIR%\qtbase\src\plugins\sqldrivers
qmake -- MYSQL_INCDIR="C:/Program Files/MySQL/MySQL Connector C 6.1/include" MYSQL_LIBDIR="C:/Program Files/MySQL/MySQL Connector C 6.1/lib"
nmake sub-mysql
nmake install
```

_We don't have any mechanism for building code_

Ok, I think in this case there is no way to install the sql plugins.

I cite from the qt documentation. See https://doc.qt.io/qt-5/sql-driver.html

**Comment by ddalcino** [comment]
If you're building the SQL drivers from source, aqtinstall can copy the source code to your machine: see [aqt install-src](https://aqtinstall.readthedocs.io/en/latest/cli.html#install-src-command).
