### ISSUE TITLE
CI: artifact upload of binary is failed

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#411]
An binary upload  to artifact repository is  failed.

https://github.com/miurahr/aqtinstall/runs/3738895772?check_suite_focus=true

```
With the provided path, there will be 1 file uploaded
A 503 status code has been received, will attempt to retry the upload
Exponential backoff for retry #1. Waiting for 6463.941065439385 milliseconds before continuing the upload at offset 8388608
Finished backoff for retry #1, continuing with upload
Error: Unexpected response. Unable to upload chunk to https://pipelines.actions.githubusercontent.com/mCosdxhYPMOehY7OSBtJ6QedFYQVaKsDvbWjeDud017vddi0mT/_apis/resources/Containers/24831821?itemPath=aqt-windows-latest-standalone%5Caqt.exe
##### Begin Diagnostic HTTP information #####
Status Code: 400
Status Message: Bad Request
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "transfer-encoding": "chunked",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "1ae62829-6524-4746-bcce-b4a51650f391",
  "activityid": "e24d0eb2-7dd0-408c-9868-2258221c85e0",
  "x-tfs-session": "e24d0eb2-7dd0-408c-9868-2258221c85e0",
  "x-vss-e2eid": "e24d0eb2-7dd0-408c-9868-2258221c85e0",
  "x-vss-senderdeploymentid": "d624195d-30e0-1768-06a5-b10a7879c7db",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: CD87654BF7384BA3B384812035D8885C Ref B: CO1EDGE1619 Ref C: 2021-09-29T00:26:16Z",
  "date": "Wed, 29 Sep 2021 00:26:16 GMT"
}
###### End Diagnostic HTTP information ######
Warning: Aborting upload for D:\a\aqtinstall\aqtinstall\.gravitybee\dist\latest\aqt.exe due to failure
Error: aborting artifact upload
```

**Comment by miurahr** [comment]
It seems an issue on server side not us.

To improve ci action further, there is an idea to add a retention period.
https://github.com/actions/upload-artifact#retention-period

**Comment by pzhlkj6612** [comment]
Well, I guess this is caused by repeated uploads because we have three Windows binary builds with **the same filename** in [test-install-qt.yml](https://github.com/miurahr/aqtinstall/blob/df0e1aff75d47ca5429d59971727e535e6fcb453/.github/workflows/test-install-qt.yml#L9-L26):

- test (windows-latest, 3.9, 5.9.9, binary)
- test (windows-latest, 3.9, 5.12.8, binary)
- test (windows-latest, 3.9, 6.1.0, binary)

The simplest fix, at [test-install-qt.yml#L166](https://github.com/miurahr/aqtinstall/blob/df0e1aff75d47ca5429d59971727e535e6fcb453/.github/workflows/test-install-qt.yml#L166), is:

```diff
- name: aqt-${{ matrix.os }}-standalone
+ name: aqt-${{ matrix.os }}-${{ matrix.qtver }}-standalone
```
The retention period may have nothing to do with this failure.

**Comment by miurahr** [comment]
These binaries are same because all case build on python 3.9.
It is better to change condition for uploading such as

```if: ${{ matrix.artifact == 'binary' && matrix.qtver == '5.9.9' }}```

https://docs.github.com/en/actions/learn-github-actions/expressions#operators

**Comment by miurahr** [comment]
Or

```
diff --git a/.github/workflows/test-install-qt.yml b/.github/workflows/test-install-qt.yml
index 0927a94..72dfe7e 100644
--- a/.github/workflows/test-install-qt.yml
+++ b/.github/workflows/test-install-qt.yml
@@ -10,20 +10,20 @@ jobs:
         os: [windows-latest, macOS-latest, ubuntu-latest]
         py: [3.9]
         qtver: [5.9.9, 5.12.8, 6.1.0]
-        artifact: [standard, binary]
+        artifact: [standard]
         include:
           - os: ubuntu-20.04
             py: 3.9
             qtver: 6.1.0
             artifact: standard
+          - os: windows-latest
+            py: 3.9
+            qtver: 6.1.0
+            artifact: binary
         exclude:
           - os: ubuntu-latest
             py: 3.9
             qtver: 6.1.0
-          - os: ubuntu-latest
-            artifact: binary
-          - os: macOS-latest
-            artifact: binary
     steps:
       - uses: actions/checkout@v1
         with:
```

**Comment by pzhlkj6612** [comment]
> These binaries are same because all case build on python 3.9.

OK, you're right. Those various versions of Qt (`matrix.qtver`) are only used for test the built program.

> ```yml
> artifact: [standard]
> include:
>   - os: windows-latest
>     py: 3.9
>     qtver: 6.1.0
>     artifact: binary
> ```

Nice. Including only one configuration to build the standalone exe is simplest.
