### ISSUE TITLE
Feature: specify the download location of 7z archives

### ISSUE THREAD

**Issue by pzhlkj6612** [miurahr/aqtinstall#421]
I am a little unclear on why we are downloading to the working directory in the first place. If the user happens to have files in the working directory with the same names as the archives downloaded, these files will be overwritten and then deleted. Additionally, if `aqt` fails before finishing this process, the working directory will be littered with `.7z` files that may or may not be partially downloaded. 

I think it might be more respectful of the user's disk space to use a temporary directory to download these files. A temp directory would delete itself automatically when the program ends, whether an error occurs of not. However, this would make it more difficult to attempt to recover an unfinished installation.

Originally posted by @ddalcino in https://github.com/miurahr/aqtinstall/pull/420#discussion_r721494482

**Comment by ddalcino** [comment]
This is now implemented in #458. @pzhlkj6612, does this work the way you wanted it to?
