### ISSUE TITLE
Cannot install qtcreator tool (any version)

### ISSUE THREAD

**Issue by richbai90** [miurahr/aqtinstall#442]
I have been trying for several hours different variations of commands to install the qtcreator ide. These are the results:

### Simple install
```sh
$ aqt install-tool linux desktop tools_qtcreator 
```
Error: The package 'qt.tools.qtcreator' has the version '5.0.2-0-202109300244', not the requested '0.0.1'.

### Specify the variant
```sh
$ aqt install-tool linux desktop tools_qtcreator qt.tools.qtcreator
```
Error: The package 'qt.tools.qtcreator' has the version '5.0.2-0-202109300244', not the requested '0.0.1'.

### Using the version number
```
$ aqt install-tool linux desktop 5.2
```
Error: Specified target combination is not valid: linux 5.2 tools_qtcreator
Failed to locate XML data for the tool '5.2'.

What is the right way to do this?

**Comment by ddalcino** [comment]
> I have been trying for **several hours**

:fearful:

> ### Simple install
> 
> ```shell
> $ aqt install-tool linux desktop tools_qtcreator 
> ```
> Error: The package 'qt.tools.qtcreator' has the version '5.0.2-0-202109300244', not the requested '0.0.1'.

This usage is correct; there should not be an error.

> ### Specify the variant
> 
> ```shell
> $ aqt install-tool linux desktop tools_qtcreator qt.tools.qtcreator
> ```
> 
> Error: The package 'qt.tools.qtcreator' has the version '5.0.2-0-202109300244', not the requested '0.0.1'.

This usage is also correct; there should not be an error.

You have my apologies for this. I wrote the code that broke this in #414; I thought that this function was being tested adequately, but it is not. I have attempted to fix it in #443. It works on my machine; I will be attempting to get a unit test and a CI test running soon.

I am very confident that #443 will work for you. If you want to try it, please let me know if it works.

**Comment by richbai90** [comment]
I will try this evening. Thank you for the swift reply

**Comment by richbai90** [comment]
I am sure this is not a surprise, but the fix worked perfectly. Thank you again!
