### ISSUE TITLE
Reqest for Enhancement: Installation of  Qt IFW

### ISSUE THREAD

**Issue by skypjack** [miurahr/aqtinstall#45]
First of all, thank you for this project. If you want to add a note to the README, I've tested it successfully with GH actions. :+1:
That said, is there any way to install Qt IFW other than the Qt libraries?

**Comment by miurahr** [comment]
Thank you for utilize. I'd like to add use cases on README.
And good question here. I'd like to extend the tool to support Qt Tools.

**Comment by skypjack** [comment]
>I'd like to extend the tool to support Qt Tools.

Do you mean that it doesn't support them yet?
That was my guess actually.

**Comment by miurahr** [comment]
Here is a quite experimental implementation for installation for IFW

https://github.com/miurahr/aqtinstall/tree/topic-tools

Feedback is welcome.

**Comment by miurahr** [comment]
README said Tools installation is not supported yet.

**Comment by miurahr** [comment]
now branch is degraded and lost code. pls wait a re implementation.

**Comment by miurahr** [comment]
https://github.com/miurahr/aqtinstall/tree/topic-tools

command line
python -m aqt tool tools windows 3.1.1 tools_ifw qt.tools.ifw.31

**Comment by skypjack** [comment]
>README said Tools installation has not been supported yet.

Yeah, I saw that part and switched to a manual download of the installer + a script to make it run as if it were headless.
I'm no longer using `aqtinstall`, I'm sorry.

**Comment by miurahr** [comment]
There is no request now for it.
