### ISSUE TITLE
enhancement request: cleanup when aborted via control c

### ISSUE THREAD

**Issue by tsteven4** [miurahr/aqtinstall#463]
If I abort an installation in progress a number of archive files are often left behind in the working directory.  can the signal be caught and  the archive files cleaned up (deleted)?

**Comment by ddalcino** [comment]
This should have been fixed in #458. Are you using v2.0.2, or the master branch? If the master branch still has this behavior, I’d like to know.

**Comment by tsteven4** [comment]
Excellent timing, you solved the issue 10 days before the request!
I agree it is fixed in 2.0.4.
