### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: webenginewidgets

### ISSUE THREAD

**Issue by dbron95** [miurahr/aqtinstall#467]
Installing all modules and archives for linux desktop gcc_64 5.15.2 and still not recognizing qtwebenginewidgets module.
aqtinstall(aqt) v2.0.4 on Python 3.8.10 [CPython GCC 9.3.0]

**Comment by ddalcino** [comment]
That's because there is no `qtwebenginewidgets` module for qt 5.15.2:
```console
$ python -m aqt list-qt linux desktop --modules 5.15.2 gcc_64
debug_info qtcharts qtdatavis3d qtlottie qtnetworkauth qtpurchasing qtquick3d qtquicktimeline qtscript
qtvirtualkeyboard qtwaylandcompositor qtwebengine qtwebglplugin
```

Please see https://aqtinstall.readthedocs.io/en/latest/getting_started.html#installing-modules for more explanation.

**Comment by miurahr** [comment]
@dbron95 can you solve your issue? any feedback or further questions?
