### ISSUE TITLE
Start the build process

### ISSUE THREAD

**Issue by Hunter2807** [miurahr/aqtinstall#468]
Hi there!

I have been looking through the docs since ages and I am not able to understand how to start the build process to convert the py files to a standalone apk file. Would be appreciated if the link for a tutorial for the same would be shared!

Thanks in advance!

**Comment by ddalcino** [comment]
Aqt is not capable of building apk files. What are you trying to do?

**Comment by Hunter2807** [comment]
Oh, I was just tryna compile my QT files made with PySide6 to apk

**Comment by ddalcino** [comment]
At https://doc.qt.io/qtforpython/gettingstarted.html#guides-per-platform:
```
Important
    Qt for Python does not yet support WebAssembly and the mobile operating systems (Android or iOS).
```

It looks like you can use PySide1 for android: https://wiki.qt.io/PySide_for_Android_guide

In either case, there's not much that `aqt` can help you with here.

**Comment by Hunter2807** [comment]
Oh, that's sad. Do u know how pyqtdeply packs the script then?

**Comment by ddalcino** [comment]
No, sorry I don't. I bet you could google it though.

**Comment by Hunter2807** [comment]
Ah cool. Thanks for the help! I'mma close this now.
