### ISSUE TITLE
library not loaded on local macOS GitHub runner

### ISSUE THREAD

**Issue by MichaelVoelkel** [miurahr/aqtinstall#469]
Hi,

I try to use my local macOS10.15 GitHub runner with the GitHub action that uses this plugin but it fails with:

```
Deleting Python 3.10.0
23
Create Python 3.10.0 folder
24
Copy Python binaries to hostedtoolcache folder
25
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
26
Upgrading pip...
27
Error: dyld: Library not loaded: /Users/runner/hostedtoolcache/Python/3.10.0/x64/lib/libpython3.10.dylib
28
  Referenced from: /Users/michael/actions-runner/_work/_tool/P
29
Error: ython/3.10.0/x64/bin/./python
29
  Reason: image not found
30
./setup.sh: line 52: 57988 Abort trap: 6           ./python -m ensurepip
31
Error: The process 'bash' failed with exit code 134
```

Any idea what could be the issue? My own environment clearly seems to be the issue but how to fix something like this?

It's a cross-post with https://github.com/jurplel/install-qt-action/issues/127 because I suspect they will tell me it's on aqtinstall side.

**Comment by MichaelVoelkel** [comment]
Why invalid? One sentence would be helpful

**Comment by ddalcino** [comment]
Did you read the error message you posted? This is output from a shell script called `setup.sh`, and it looks like it's trying (and failing) to set up Python and pip. This has nothing to do with `aqt` and it doesn't belong here.

**Comment by MichaelVoelkel** [comment]
I was not sure which part is done where to be honest, but yeah.. if aqtinstall starts when Python is set up (which makes kind of sense), then clear. Thanks for clarifying!
