### ISSUE TITLE
failure to install qtdesignstudio

### ISSUE THREAD

**Issue by tsteven4** [miurahr/aqtinstall#475]
**Describe the bug**
attempts to install tools_qtdesignstudio fail.  The failure seems to be a failure to parse the components required.  All the components are retrievable individually.

**To Reproduce**
1. install `aqt` using this command
2. run `aqt` with this command
 aqt install-tool linux desktop tools_qtdesignstudio
3. See error

**Expected behavior**
I expected the install to complete successfully

**`aqt` output**
Add program output to help explain your problem.

```
aqt install-tool linux desktop tools_qtdesignstudio
aqtinstall(aqt) v2.0.5 on Python 3.8.10 [CPython GCC 9.3.0]
Caught ArchiveDownloadError, terminating installer workers
Failed to retrieve file at https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_qtdesignstudio/qt.tools.qtdesignstudio/2.3.1-0-202112170942design_studio_extra_qt_docs.7z,designstudio_base.7z,plugin-telemetry.7z,qml2puppet.7z,qt5_design_studio_reduced_version.7z,qt6_design_studio_reduced_version.7z,qtcreator.7z,qtcreator_sdktool.7z,qtdesignviewer_arm64-v8a.7z,qtdesignviewer_armeabi-v7a.7z,qtdesignviewer_x86.7z,qtdesignviewer_x86_64.7z,content.7z.sha1
Server response code: 403, reason: Forbidden

```

**Desktop (please complete the following information):**
 - OS: ubuntu focal
 - Python version and build info [paste the output from the command `python -VV`]
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
 - `aqt` version [paste the output from the command `aqt --version` or `python -m aqt --version`]
aqtinstall(aqt) v2.0.5 on Python 3.8.10 [CPython GCC 9.3.0]

**Additional context**
$ cat aqtinstall.log 
2022-01-11 15:32:19,367 - aqt.main - INFO - installer 139681685116736 aqtinstall(aqt) v2.0.5 on Python 3.8.10 [CPython GCC 9.3.0]
2022-01-11 15:32:23,530 - aqt.installer - DEBUG - installer 140030396172096 Download URL: https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_qtdesignstudio/qt.tools.qtdesignstudio/2.3.1-0-202112170942design_studio_extra_qt_docs.7z,designstudio_base.7z,plugin-telemetry.7z,qml2puppet.7z,qt5_design_studio_reduced_version.7z,qt6_design_studio_reduced_version.7z,qtcreator.7z,qtcreator_sdktool.7z,qtdesignviewer_arm64-v8a.7z,qtdesignviewer_armeabi-v7a.7z,qtdesignviewer_x86.7z,qtdesignviewer_x86_64.7z,content.7z
2022-01-11 15:32:24,139 - aqt.installer - WARNING - installer 139681685116736 Caught ArchiveDownloadError, terminating installer workers
2022-01-11 15:32:24,198 - aqt.main - ERROR - installer 139681685116736 Failed to retrieve file at https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_qtdesignstudio/qt.tools.qtdesignstudio/2.3.1-0-202112170942design_studio_extra_qt_docs.7z,designstudio_base.7z,plugin-telemetry.7z,qml2puppet.7z,qt5_design_studio_reduced_version.7z,qt6_design_studio_reduced_version.7z,qtcreator.7z,qtcreator_sdktool.7z,qtdesignviewer_arm64-v8a.7z,qtdesignviewer_armeabi-v7a.7z,qtdesignviewer_x86.7z,qtdesignviewer_x86_64.7z,content.7z.sha1
Server response code: 403, reason: Forbidden

This script fetches all the components in the above log without any problems:
#!/bin/bash -ex
head='https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_qtdesignstudio/qt.tools.qtdesignstudio/'
tail=(
2.3.1-0-202112170942design_studio_extra_qt_docs.7z \
designstudio_base.7z \
plugin-telemetry.7z \
qml2puppet.7z \
qt5_design_studio_reduced_version.7z \
qt6_design_studio_reduced_version.7z \
qtcreator.7z \
qtcreator_sdktool.7z \
qtdesignviewer_arm64-v8a.7z \
qtdesignviewer_armeabi-v7a.7z \
qtdesignviewer_x86.7z \
qtdesignviewer_x86_64.7z \
content.7z.sha1 \
)

for file in ${tail[@]}
do
echo $head$tail
wget "$head$tail"
done

**Comment by ddalcino** [comment]
Oops! I think we are splitting on `', '`, but we are not accounting for the unusual case where we need to use `','` instead. There should be an easy fix for this ...

BTW, thanks for the bug report, @tsteven4!

**Comment by miurahr** [comment]
```
diff --git a/aqt/archives.py b/aqt/archives.py
index c5c9286..1779380 100644
--- a/aqt/archives.py
+++ b/aqt/archives.py
@@ -245,7 +245,8 @@ class QtArchives:
             full_version = packageupdate.find("Version").text
             package_desc = packageupdate.find("Description").text
 
-            for archive in downloads_text.split(", "):
+            for archive_raw in downloads_text.split(","):
+                archive: str = archive_raw.strip()
                 archive_name = archive.split("-", maxsplit=1)[0]
                 package_url = posixpath.join(
                     # https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_5150/
@@ -442,7 +443,8 @@ class ToolArchives(QtArchives):
         if not downloadable_archives:
             message = f"The package '{self.arch}' contains no downloadable archives!"
             raise NoPackageFound(message)
-        for archive in downloadable_archives.split(", "):
+        for archive_raw in downloadable_archives.split(","):
+            archive: str = archive_raw.strip()
             package_url = posixpath.join(
                 # https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/
                 archive_url,
```

This may fix a behavior.

**Comment by ddalcino** [comment]
Agreed. I think it would also be useful to add a test case to require the "split on single-quote" behavior, so that no one is tempted to remove this fix for performance purposes.

Also, maybe we can change the issue template so that we're not asking the user to copy-paste the result of `python-VV`; it looks redundant.

**Comment by tsteven4** [comment]
And please change the issue template so it doesn't refer to "aqt --version"
$ aqt --version
usage: aqt [-h] [-c CONFIG]
           {install-qt,install-tool,install-doc,install-example,install-src,list-qt,list-tool,list-doc,list-example,list-src,install,tool,doc,examples,src,help,version}
           ...
aqt: error: unrecognized arguments: --version

**Comment by tsteven4** [comment]
BTW, nice job.  aqt is much faster than qt installer scripts, and I don't have to spend hours maintaining the scripts.  We've been using it in for CI for https://github.com/gpsbabel/gpsbabel.
