### ISSUE TITLE
macOS M1 / Linux aarch64 support?

### ISSUE THREAD

**Issue by MichaelVoelkel** [miurahr/aqtinstall#496]
Trying to run a docker container on macOS M1, which has output `aarch64` from `uname -m` on `FROM ubuntu:latest`, will not enable me to install Qt with this plugin. E.g., asking `python3 -m aqt list-qt linux desktop --arch 5.15.2` only yields `clang_64`. Is support planned or am I doing anything wrong?

**Comment by miurahr** [comment]
aqtinstall is installer not provide Qt. You can see https://www.qt.io/blog/qt-on-apple-silicon
Qt recommend for you to build Qt from source.

You can use `aqt install-src ` command to install source to your platform.
see https://aqtinstall.readthedocs.io/en/latest/cli.html?highlight=source#install-src-command

**Comment by ddalcino** [comment]
Interesting. The blog post you linked makes it sounds like universal builds (both arm64 and x64 in one binary) are supported by Qt 6.2. If that's true, maybe we can add a build like that to our CI, and discuss it in our docs. That could be a 'planned for the future' kind of a goal.

I plan on getting an apple silicon MBP at the end of the month, so I will be able to investigate this then.

**Comment by MichaelVoelkel** [comment]
Well, so far did not manage to build Qt from source on aarch64... first, there are patches for 4-5 files needed because it uses `numeric_limits` in files where `#include <limits>` is missing. Second, even then it fails at some point, fun... will give up for now, but thanks for the hint

**Comment by ddalcino** [comment]
Compiling QT is not an easy thing to do, but you get points for trying. Is it not an option to use Qt 6.2+ instead?

**Comment by miurahr** [comment]
@MichaelVoelkel  Any comments for a suggestion from @ddalcino  ?

**Comment by MichaelVoelkel** [comment]
Just switching the version? Not really helpful for anyone who googles this and sadly not an option for me at the moment

**Comment by ddalcino** [comment]
I don’t have any useful suggestions to add. Building qt from source is not a trivial task, and it’s outside the scope of aqtinstall. We get all of our qt binaries from download.qt.io, and until they start building specific arm binaries, there’s nothing we can do.

There are plenty of guides that discuss how to cross-compile qt for arm from an x86 Linux environment, but I haven’t seen anything for an Arm host. @MichaelVoelkel, if you can figure out how to build qt from source from an Arm Linux container, I’m sure the world would like to know how you did it; it would make a great blog post.

**Comment by Garald-48rus** [comment]
aqt list-qt linux desktop
'NoneType' object has no attribute 'find_all'
Traceback (most recent call last):
  File "/home/garald/.local/lib/python3.8/site-packages/aqt/installer.py", line 108, in run
    args.func(args)
  File "/home/garald/.local/lib/python3.8/site-packages/aqt/installer.py", line 524, in run_list_qt
    show_list(meta)
  File "/home/garald/.local/lib/python3.8/site-packages/aqt/metadata.py", line 775, in show_list
    output = meta.getList()
  File "/home/garald/.local/lib/python3.8/site-packages/aqt/metadata.py", line 435, in getList
    return self._action()
  File "/home/garald/.local/lib/python3.8/site-packages/aqt/metadata.py", line 473, in fetch_versions
    versions = sorted(filter(None, map(get_version, filter(filter_by, versions_extensions))))
  File "/home/garald/.local/lib/python3.8/site-packages/aqt/metadata.py", line 600, in iterate_folders
    for row in soup.body.table.find_all("tr"):
AttributeError: 'NoneType' object has no attribute 'find_all'
aqtinstall(aqt) v2.1.0 on Python 3.8.10 [CPython GCC 9.4.0]
Working dir: `/home/garald`
Arguments: `['/home/garald/.local/bin/aqt', 'list-qt', 'linux', 'desktop']` Host: `uname_result(system='Linux', node='garald-H310M-S2-2-0', release='5.4.0-109-generic', version='#123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022', machine='x86_64', processor='x86_64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues.
Please remember to include a copy of this program's output in your report.

**Comment by miurahr** [comment]
There is no further suggestion. I'd like to close.
If anyone has a chance to share new insight or suggestion, feel free open here or new issue.
