### ISSUE TITLE
A way to install only Qt binaries

### ISSUE THREAD

**Issue by SirLynix** [miurahr/aqtinstall#497]
**Is your feature request related to a problem? Please describe.**
I'm working on Qt packages for [xmake](https://xmake.io) (see https://github.com/xmake-io/xmake-repo/pull/1031) and everything works pretty fine except for MinGW on Linux/macOS.

So I'm running `aqt install-qt -O <dir> windows desktop 5.15.2 mingw81` to get MinGW binaries, which works fine for building libs but we can't run moc and such, since they're windows executables, which means we can't build MinGW Qt apps from macOS (see [here](https://github.com/xmake-io/xmake-repo/runs/5426681921?check_suite_focus=true#step:5:197)

**Describe the solution you'd like**
A way to get Linux/macOS binaries (bin folder) only, or maybe a mingw target with linux/mac host?

**Describe alternatives you've considered**
Download whole Qt twice (windows then linux/macos), and override the windows bin folder with linux/macos binaries.

**Comment by ddalcino** [comment]
Have you seen https://aqtinstall.readthedocs.io/en/latest/getting_started.html#installing-qt ? When you run `aqt list-qt`, it should tell you that mingw doesn't exist as a supported architecture on Linux/Mac. aqtinstall can only provide binaries available on download.qt.io, and you're asking for something that isn't there.

**Comment by SirLynix** [comment]
Yes I did, but I'm afraid you didn't understand what I'm trying to do.

What I'm trying to do is to have support for cross-compilation for Windows from Linux and macOS using MinGW. In order to have that I'm downloading Windows library binaries for Qt (as they're will be used by MinGW and shipped with the application) but I also need Linux/macOS Qt tooling binaries (moc, quic and such) as they're needed to build applications.

**Comment by ddalcino** [comment]
I’m still not clear on what you’re asking for.

> **Describe alternatives you've considered**
Download whole Qt twice (windows then linux/macos), and override the windows bin folder with linux/macos binaries.

Did this approach work? If so, are you asking for a CLI command that does this?

**Comment by SirLynix** [comment]
I'm currently implementing this approach, so far it looks like it should work.

However the "issue" is that I see a lot of Qt packages being downloaded (qtwebsockets, qtquickcontrols, qt3d, qtspeech, etc.) that I won't need as I only need Qt tool binaries and their runtime, is there a way to download only qttools-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z or qtbase-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z?

**Comment by ddalcino** [comment]
You are looking for https://aqtinstall.readthedocs.io/en/latest/getting_started.html#installing-a-subset-of-qt-archives-advanced

**Comment by SirLynix** [comment]
Thanks a lot! That's exactly what I needed.

**Comment by ddalcino** [comment]
Actually, if this is a common use case, maybe we want to add something like a `--cross` option to the CLI, that overwrites the `bin` folder with the binaries for the host OS, as you have described. What do you think, @miurahr?

**Comment by miurahr** [comment]
> Actually, if this is a common use case, maybe we want to add something like a `--cross` option to the CLI, that overwrites the `bin` folder with the binaries for the host OS, as you have described. What do you think, @miurahr?

@SirLynix  give us an use case which we don't think ever. 
If I was developer to do it, I will install mingw/windows binaries to another directory and copy necessary libraries into a place it should be.

IMHO, `--cross` is not good option name, because we have already allowed extraction of binaries for another architecture, for example, install-qt windows on linux host.

@ddalcino what do you think if we can provide `--subset <filter.yml>` that allow install only files specified in `filter.yml` from package?
