### ISSUE TITLE
Feature: add prefixes to warnings and errors in output

### ISSUE THREAD

**Issue by pzhlkj6612** [miurahr/aqtinstall#513]
**Is your feature request related to a problem? Please describe.**

Some users might be misled by the output during the installation of Qt. For example, in jurplel/install-qt-action#143 , the following output led the OP to think that something went wrong:

```
Specified Qt version is unknown: 6.2.3.

```

**Describe the solution you'd like**

Add prefixes to warning and error messages. For example:

```
Warning: msg...
Error:   msg...

```

or,

```
[WARN] msg...
[ERR]  msg...

```

**Describe alternatives you've considered**

none.

**Additional context**

I didn't read the code, but I found that the "ci/logging.ini" file was set as the value of the environment variable `LOG_CFG` , and it seemed to take effect in the "Test on GH actions environment" workflow ("[.github/workflows/test-install-qt.yml](https://github.com/miurahr/aqtinstall/blob/c26cb871aee5d13a0568946ecb95d1199009ed7d/.github/workflows/test-install-qt.yml#L87)"). Since the variable `LOG_CFG` is **not** documented yet, I think that changing the default behavior of logging may not surprise too many people.

**Comment by miurahr** [comment]
If you find a better configuration for https://github.com/miurahr/aqtinstall/blob/master/ci/logging.ini  , it is great.

**Comment by miurahr** [comment]
There is a document: https://docs.python.org/3/howto/logging.html#configuring-logging

**Comment by miurahr** [comment]
Default configuration is set in https://github.com/miurahr/aqtinstall/blob/master/aqt/logging.ini

There is 
```
[formatter_verbose]
format=%(asctime)s - %(name)s - %(levelname)s - %(module)s %(thread)d %(message)s
class=logging.Formatter

[formatter_simple]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
class=logging.Formatter

[formatter_brief]
format=%(message)s
class=logging.Formatter

[handlers]
keys=console,file

[handler_console]
level=INFO
class=logging.StreamHandler
formatter=brief
args=(sys.stderr,)

[handler_file]
level=DEBUG
class=logging.FileHandler
formatter=verbose
args=('aqtinstall.log', 'a')
```

And you may see console logging which is configured to use `brief` formatter defined as `%(messages)s`

**Comment by miurahr** [comment]
@pzhlkj6612 whether #529 is your intended change?

**Comment by miurahr** [comment]
@pzhlkj6612  you can easily add your custom logging configuration by giving environment variable such as `LOG_CFG=/home/your/favorite/logging.ini`

**Comment by miurahr** [comment]
There is no feedback form reporter so I won't change anything and closed.

**Comment by pzhlkj6612** [comment]
Hi @miurahr  , I'm sorry I didn't reply in time. 

> @pzhlkj6612 whether #529 is your intended change?

I tried that, but I think left aligning the level name may be more eye-catching. I sent a PR #539 , please check that.
