### ISSUE TITLE
Qt 6.3 support

### ISSUE THREAD

**Issue by ElderOrb** [miurahr/aqtinstall#522]
Please add Qt 6.3 support. At the moment attempt to install 6.3.0 results in the following: 

Specified Qt version is unknown: 6.3.0.
Specified target combination is not valid or unknown: windows desktop win64_mingw81
Some of specified modules are unknown.

**Comment by ddalcino** [comment]
Qt 6.3.0 is already fully supported.

That's not a valid architecture for 6.3.0; try using `aqt list-qt` for valid architectures. Perhaps you're looking for win64_mingw?
