### ISSUE TITLE
Feature: Add support for installing the WASM packages

### ISSUE THREAD

**Issue by Skycoder42** [miurahr/aqtinstall#53]
With Qt 5.13, the Qt company officially ships precompiled binaries for WebAssembly. As far as I can tell, it is currently not possible to install those via aqtinstall. It would be awesome if the could be added.

Please note that wasm archives are in a different subfolder: https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_5132_wasm/ . I personally think it would be best to add `wasm` as a new `<target>`, as that fits best with aqinstalls current semantics.

**Comment by miurahr** [comment]
you are welcome to add a component for known list
https://github.com/miurahr/aqtinstall/blob/master/aqt/combinations.json

**Comment by miurahr** [comment]
It is not enough to add a entry to known component list, but need more logic to do things.

**Comment by miurahr** [comment]
working on #55

**Comment by Skycoder42** [comment]
Thanks for adding the support!
