### ISSUE TITLE
libicu libraries not installed

### ISSUE THREAD

**Issue by vervaekejonathan** [miurahr/aqtinstall#532]
Used the following command to install Qt

`
aqt install-qt  linux desktop 5.12.8 gcc_64 --archives qtbase qtdeclarative qtquickcontrols qtgraphicaleffects qtquickcontrols2 qttranslations qtwebsockets qtmultimedia qttools
`

When compiling my application, it cannot find libicu

```
/usr/bin/ld: warning: libicui18n.so.56, needed by ~/Qt/5.12.8/gcc_64/lib/libQt5Core.so.5.12.8, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicuuc.so.56, needed by ~/Qt/5.12.8/gcc_64/lib/libQt5Core.so.5.12.8, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicudata.so.56, needed by ~/Qt/5.12.8/gcc_64/lib/libQt5Core.so.5.12.8, not found (try using -rpath or -rpath-link)
```

It is available in the folder installed via the official Qt installer:
```
/opt/Qt5.12.8/5.12.8/gcc_64/lib: ll libicudata.so.56.1 
-rwxr-xr-x 1 root root 24M sep 26  2016 libicudata.so.56.1
```

But not in the one installed via aqt:

```
~/Qt/5.12.8/gcc_64/lib:ll libicu*
zsh: no matches found: libicu*
```

**Comment by miurahr** [comment]
Because you @vervaekejonathan  don't specify icu as `--archives` option, that limit  target package as you specified exactly.

**Comment by vervaekejonathan** [comment]
@miurahr I see.. I matched the install list to what was required via apt, probably this is bundled somewhere when you install via apt

**Comment by miurahr** [comment]
Please try
`aqt install-qt linux desktop 5.12.8 gcc_64 --archives qtbase qtdeclarative qtquickcontrols qtgraphicaleffects qtquickcontrols2 qttranslations qtwebsockets qtmultimedia qttools icu`

**Comment by miurahr** [comment]
When you are not expert of Qt packages, you are recommended to use ``--modules`` option instead of ``--archives``
https://aqtinstall.readthedocs.io/en/latest/cli.html#cmdoption-list-tool-modules

``--archives`` is an option for expert and no guarantee a result of installation.

**Comment by miurahr** [comment]
question answered.
