### ISSUE TITLE
Allow specifying `latest` as a Qt version

### ISSUE THREAD

**Issue by LorenDB** [miurahr/aqtinstall#549]
Sometimes (e.g. in CI runners, but also in general use) it would be nice to be able to install the latest version of Qt without having to look up what that version is. Therefore, I'd like to propose that aqt gains the ability to recognize `latest` as a Qt version. If `latest` is used instead of, say, `6.3.1`, aqt could ping the Qt download servers to find out what the latest released version is (like is done in `aqt list-qt`). Then that version would be installed.

:+1: for the great tool!

**Comment by ddalcino** [comment]
Have you tried using the SimpleSpec feature instead of a version? It’s documented here: https://aqtinstall.readthedocs.io/en/latest/cli.html#install-qt-command

You can approximate the effect of `latest` with this command:

    aqt install-qt linux desktop “*” gcc_64

**Comment by LorenDB** [comment]
Oh, I see. That will work fine! Thanks!
