### ISSUE TITLE
Link with QT (qtcreator)

### ISSUE THREAD

**Issue by rhd** [miurahr/aqtinstall#593]
**Describe the bug**
I've installed QT Creator externally to aqtinstall. I'm trying to add the installed version of QT to QT Creator using the "Link with QT" feature as documented [here](https://doc.qt.io/qtcreator/creator-project-qmake.html).

Unfortunatly, QT Creator is not recognizing the path.

I've installed QT with aqtinstall to `~/AppData/Local/QT`. Inside of this directory is `6.4.0/mingw_64`.

I'm not sure what path QT Creator is looking for, but I've tried all the variables that I could think of.

**To Reproduce**
1. `aqt install-qt --outputdir c:\users\<username>\AppData\Local\QT windows desktop 6.4.0 win64_mingw`
2. install QT Creator

**Expected behavior**
I expected QT Creator to pick up the QT installation.

**`aqt` output**

`aqt` is acting normally

**Desktop (please complete the following information):**
 - OS: windows
 - `aqt` version: `aqtinstall(aqt) v3.0.1 on Python 3.10.7 [CPython MSC v.1933 64 bit (AMD64)]`

**Additional context**

None.

**Comment by miurahr** [comment]
duplicated with #448

**Comment by rhd** [comment]
@miurahr Forgot to say - thanks. I got it up and running with a manual configuration.

**Comment by miurahr** [comment]
If @rhd wanna  help development, there is topic branch in #474 that wait further enhancement.
Always welcome.
