### ISSUE TITLE
Specified path is bad: 5.9.9/msvc2017_64/mkspecs/modules/qt_lib_axcontainer.pri

### ISSUE THREAD

**Issue by EtlamGit** [miurahr/aqtinstall#604]
Fails while installing Qt 5.9.9 and says I should file a bug report here...
(The link to file the bug report is also wrong: trailing dot should be removed)

* [github workflow that was used](https://github.com/mrkite/minutor/blob/master/.github/workflows/cpp-qt-windows.yml)
* [error log](https://github.com/mrkite/minutor/actions/runs/3380043667/jobs/5612368860)

Expected behavior:
About 2 weeks ago, the same workflow was running fine.
You should be able to see the old logs on project Actions page.

Automatic build pipeline running on Windows via github Actions
trying to install Qt 5.9.9 (now failing) and Qt 5.12.12 (still working).

(all other information can be derived from the links)

**Comment by miurahr** [comment]
Please check your actions configuration.

We plan to move minimum py7zr version as >=0.20.2
see https://github.com/miurahr/aqtinstall/blob/master/docs/CHANGELOG.rst#changed

Py7zr v0.19.1 has been yanked which has a critical bug. 
https://pypi.org/project/py7zr/#history

**Comment by EtlamGit** [comment]
Really strange is, that it worked 30 minutes earlier and some hour later.
Therefore I would assume that some GitHub hiccup has caused this error.

When you think that there is nothing you can take/learn from the logs, feel free to close this issue.
