### ISSUE TITLE
CI: Enable mypy type check

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#616]
**Is your feature request related to a problem? Please describe.**
We have test cases with good coverage, and the code has good type hinting.
Now we can enable mypy type check on CI process

**Describe the solution you'd like**
Add tox mypy config on `pyproject.toml` and enable it on github actions `check`

#615 implement it.

**Comment by ddalcino** [comment]
#615 looks like a welcome improvement. Mypy shows a lot of errors in metadata.py; I’ll open a separate PR to address these, if that helps.

The errors in installer.py look like they’re related to the ArgumentParser. This stackoverflow question suggests several ways to handle this problem, liked NamedTuples and the [TAP](https://pypi.org/project/typed-argument-parser/1.7.2/ ) library: https://stackoverflow.com/questions/42279063/python-typehints-for-argparse-namespace-objects. It’s not clear to me which would be the best solution for us.

**Comment by miurahr** [comment]
We can control how strict we check typing
You can find a `pyproject.toml` change to configure mypy.

```
[tool.mypy]
check_untyped_defs = false
disallow_incomplete_defs = false
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_untyped_decorators = false
ignore_missing_imports = true
namespace_packages = false
no_implicit_optional = true
pretty = false
sqlite_cache = true
show_error_context = false
show_column_numbers = true
strict_optional = true
warn_no_return = false
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true
```

I disables some checks and make it relaxed.

I set low warning verbosity , such as `pretty`, and `show_error_context` to be `false`.

**Comment by miurahr** [comment]
> The errors in installer.py look like they’re related to the ArgumentParser. This stackoverflow question suggests several ways to handle this problem, liked NamedTuples and the [TAP](https://pypi.org/project/typed-argument-parser/1.7.2/) library: https://stackoverflow.com/questions/42279063/python-typehints-for-argparse-namespace-objects. It’s not clear to me which would be the best solution for us.

I try TAP and know that it asks big changes.

I think it is better to suppress mypy warnings for argparse. We can update Cli class when we remove deprecated old command syntax.

**Comment by miurahr** [comment]
There is alternative solution [typed-argparse](https://pypi.org/project/typed-argparse/) that takes similar way with our approach to define `CustomArgParse` class. I've tried and satisfied with it.
Let's take it for our solution.

**Comment by ddalcino** [comment]
Since #620 was merged, does this need to stay open? Is there anything else to do for this one?

**Comment by miurahr** [comment]
Yes now it has been checked on CI.
