### ISSUE TITLE
aqt installs wrong archive versions for Android

### ISSUE THREAD

**Issue by danryu** [miurahr/aqtinstall#621]
aqt installs Windows or macOS versions of archives, instead of expected Linux-RHEL, when installing for Android.

Running below on Ubuntu 22.04:

```
$ aqt install-qt  linux android 6.4.1 android_armv7  --archives qtbase qtdeclarative qtsvg qttools             --modules qtwebview
INFO    : aqtinstall(aqt) v3.0.2 on Python 3.8.10 [CPython GCC 9.4.0]
WARNING : You are installing the android version of Qt, which requires that the desktop version of Qt is also installed. You can install it with the following command:
          `aqt install-qt linux desktop 6.4.1 gcc_64`
WARNING : Specified Qt version is unknown: 6.4.1.
INFO    : Downloading qtbase...
INFO    : Downloading qtsvg...
INFO    : Downloading qtwebview...
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Downloading qtdeclarative...
INFO    : Finished installation of qtsvg-Windows-Windows_10_21H2-Clang-Android-Android_ANY-ARMv7.7z in 4.70239495
INFO    : Finished installation of qtwebview-Windows-Windows_10_21H2-Clang-Android-Android_ANY-ARMv7.7z in 4.82297651
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Downloading qttools...
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Finished installation of qttools-Windows-Windows_10_21H2-Clang-Android-Android_ANY-ARMv7.7z in 16.33704408
INFO    : Finished installation of qtdeclarative-Windows-Windows_10_21H2-Clang-Android-Android_ANY-ARMv7.7z in 84.48235241
INFO    : Finished installation of qtbase-Windows-Windows_10_21H2-Clang-Android-Android_ANY-ARMv7.7z in 92.03991162
INFO    : Patching /mnt/c/Users/danzv/code/6.4.1/android_arm64_v8a/bin/6.4.1/android_armv7/bin/qmake
INFO    : Finished installation
INFO    : Time elapsed: 95.69257085 second
```

or for android_arm64_v8a:
```
$ cd ..; aqt install-qt  linux android 6.4.1 android_arm64_v8a  --archives qtbase qtdeclarative qtsvg qttools             --modules qtwebview
INFO    : aqtinstall(aqt) v3.0.2 on Python 3.8.10 [CPython GCC 9.4.0]
WARNING : You are installing the android version of Qt, which requires that the desktop version of Qt is also installed. You can install it with the following command:
          `aqt install-qt linux desktop 6.4.1 gcc_64`
WARNING : Specified Qt version is unknown: 6.4.1.
INFO    : Downloading qtsvg...
INFO    : Downloading qtwebview...
INFO    : Downloading qtbase...
INFO    : Downloading qtdeclarative...
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Finished installation of qtwebview-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 8.91114430
INFO    : Finished installation of qtsvg-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 8.87464106
INFO    : Downloading qttools...
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Finished installation of qttools-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 16.88082671
INFO    : Finished installation of qtdeclarative-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 87.06333792
INFO    : Finished installation of qtbase-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 93.44883074
INFO    : Patching /mnt/c/Users/danzv/code/6.4.1/android_arm64_v8a/bin/qmake
INFO    : Finished installation
INFO    : Time elapsed: 97.13789190 second
```

**To Reproduce**
1. using aqt 3.0.2 installed via pip
2. Execute eg: `aqt install-qt  linux android 6.4.1 android_arm64_v8a  --archives qtbase qtdeclarative qtsvg qttools             --modules qtwebview`

**Expected behavior**
Install Linux-RHEL versions rather than randomly selecting macOS and Windows packages.

**`aqt` output**
See above

**Desktop (please complete the following information):**
 - OS: Ubuntu targeting android
 - `aqt` version 3.0.2

**Comment by ddalcino** [comment]
This behavior is unusual, but it has nothing to do with aqt. Check the updates.xml file at https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_641_armv7/Updates.xml. You will see that the `DownloadableArchives` tags in every PackageUpdate mention `Windows` and `MacOS`. Aqt is only capable of installing what the updates.xml file tells it to. If the Qt repository maintainers uploaded the wrong files to the repository, please file a bug report with them.

Have you tried using the copies of Qt that you installed? Are they any less functional than the ones that the official installer installs? If they aren’t working, it is likely that the official versions won’t work either.

**Comment by danryu** [comment]
Ok sure enough
https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_641_armv7/Updates.xml
lists only Windows packages
and https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt6_641_arm64_v8a/Updates.xml 
lists only macOS packages.

As qttools macOS gets installed in my Ubuntu CI process, it is of course totally unusable as even `qmake` is not executable.
So this is a hard blocker for 6.4.1 aqt Android installations.

If you can tell me where/how best to log this with the Qt repo maintainers I will do so to try an expedite a fix.

**Comment by ddalcino** [comment]
I’ve never done it before, but I would start here: https://wiki.qt.io/Reporting_Bugs

I would also make an attempt to install Qt on desktop Ubuntu and see if it makes a working installation. That would also be helpful if the Qt developers have questions for you.

**Comment by danryu** [comment]
created bug here https://bugreports.qt.io/browse/QTBUG-108707

**Comment by danryu** [comment]
The bug has been rejected as Invalid by Qt, and closed with this comment:

"Actually this is correct; we are building android packages only in one host & use those in other ones:
    android armv7 is build only in windows
    android arm64 is build only in mac
    android x86 and android x86_64 are build only in linux"

I'm really confused by this. Why would it change between 6.4.0 and 6.4.1? And does this mean I cannot build for Android ARM anymore on Linux?

**Comment by danryu** [comment]
Still mystified by Qt closing the above issue - why would they make arm7 and arm64 be build-only in either Mac or Windows?
In any case, it means that `aqt` is no longer usable for Android arm* builds on my normal Linux-based Github CI.

I am now building Qt for Android from source, and will have to deprecate use of `aqt`.

I assume this issue is "Won't Fix" - you can go ahead and close it out if so.

**Comment by ddalcino** [comment]
> I assume this issue is "Won't Fix" - you can go ahead and close it out if so.

I don't think this is a "Won't fix"; it is a question of how much we are actually able to fix. `aqtinstall` claims to be able to install 4 different Android architectures on all platforms; this is clearly no longer true for Qt 6.4.1.

I think that at the very least, we need to update `aqt list-qt` to only print architectures that we can actually install successfully, ie: `aqt list-qt windows android --arch 6.4.1` should only print `android_armv7`, etc.

> I'm really confused by this. Why would it change between 6.4.0 and 6.4.1?

This makes no sense to me either. However, I have noticed big changes happening between patch releases, a lot like this, and we have to code around them in `aqt`. I don't think that Qt is using semantic versioning.

> I am now building Qt for Android from source, and will have to deprecate use of `aqt`.

I'm glad you found a solution.

Building Qt from source is definitely beyond the scope of `aqt`, but in many use cases, it seems to be the best solution. We frequently get requests for Qt binaries that are not available on download.qt.io, and I'm not sure what to tell them because I don't know anything about building Qt. Would you mind sharing a link to your Github workflow here? I'm sure it will be useful to anyone having with this problem.

**Comment by danryu** [comment]
> Would you mind sharing a link to your Github workflow here? I'm sure it will be useful to anyone having with this problem.

Sure. 
I build Android for all ABIs (x86, x86_64, armeabi-v7a, arm64-v8a) on Ubuntu like this: 
https://github.com/koord-live/koord-app/blob/main/.github/autobuild/qt_android.sh

Which is triggered by this Github Action yaml: 
https://github.com/koord-live/koord-app/blob/main/.github/workflows/qt_android_build.yml 

(This follows the advice given in Qt docs: https://doc.qt.io/qt-6/android-building.html)

**Comment by ddalcino** [comment]
FYI, there has been some progress with #626. #627 should make it possible to build for android arm64_v8a on linux in CI, if you want to try it. Don't forget to set `ANDROID_NDK_HOST="linux-x86_64"` in your environment variables if you want to try it though.

`android_armv7` on non-Windows hosts is proving difficult for me though, and I'm not sure I'll be able to get it working.
