### ISSUE TITLE
Cannot add Qt 6.4.1 Android Arm64_v8a as a Qt Kit into QtCreator

### ISSUE THREAD

**Issue by vkuznetsovgn** [miurahr/aqtinstall#626]
**Description**
When trying to add Qt 6.4.1 Android Arm64_v8a as a Qt Version for Kit into QtCreator, I am getting an error:

The qmake executable /opt/Qt/6.4.1/android_arm64_v8a/bin/qmake could not be added: "/opt/Qt/6.4.1/android_arm64_v8a/bin/qmake" produced no output: /opt/Qt/6.4.1/android_arm64_v8a/bin/qmake: 7: /Users/qt/work/install/bin/qmake: not found

However, via an official installer I can add this Qt version without any issues and I can compile and deploy everything as usual.

**To Reproduce**
1. aqt install-qt -O /opt/Qt linux android 6.4.1 android_arm64_v8a --autodesktop
2. Open QtCreator 8.0.2, add /opt/Qt/6.4.1/android_arm64_v8a/bin/qmake as Qt Version.
3. See the error.

**Expected behavior**
Works the same as for the official installer.

**Desktop:**
 - OS: Ubuntu 22.04
 - `aqt` version: aqtinstall(aqt) v3.0.2 on Python 3.10.6 [CPython GCC 11.3.0]

UPD:
I don't have such problem with Qt 6.4.0 installed via aqtinstall.

**Comment by miurahr** [comment]
Duplicated with #621

**Comment by vkuznetsovgn** [comment]
@miurahr 
It's not a duplicate.
This is the aqt bug, because the behavior differs from the official installer.

**Comment by miurahr** [comment]
#621 report  installation of  android_arm64_v8a with --autodesktop installs  "windows" binary because The Qt foundation published android binary with metadata only with windows SDK, and they close its issue ticket as won't fix.

It is why QtCreator on linux failed to  execute qmake,  but it is windows binary qmake.exe.

**Comment by vkuznetsovgn** [comment]
> #621 report installation of android_arm64_v8a with --autodesktop installs "windows" binary because The Qt foundation published android binary with metadata only with windows SDK, and they close its issue ticket as won't fix.
> 
> It is why QtCreator on linux failed to execute qmake, but it is windows binary qmake.exe.

What I am missing here is that why then Qt 6.4.1 android_arm64_v8a from the official installer works in QtCreator but from aqt not?

> You can do work around in a way that previous versions.

I completely removed Qt 6.4.1 installed with aqt and reinstalled it using 2 commands:

$ aqt install-qt -O /opt/Qt linux desktop 6.4.1
$ aqt install-qt -O /opt/Qt linux android 6.4.1 android_arm64_v8a

It did not help. I'm still getting the same error in QtCreator.
if I check `cat /opt/Qt/6.4.1/android_arm64_v8a/bin/qmake` , I see it's using some strange location to execute qmake `/Users/qt/work/install/bin/qmake` , while qmake from Qt installer points to the correct desktop qmake.

**Comment by vkuznetsovgn** [comment]
Upd:
I just manually replaced non-existent `/Users/qt/work/install/bin/qmake` with `/opt/Qt/6.4.1/gcc_64/bin/qmake` and it does work perfectly fine now.

**Comment by miurahr** [comment]
@vkuznetsovgn Thank you. Now I understand a report.

when running command I observed
```
$ aqt install-qt  linux android 6.4.1 android_arm64_v8a --autodesktop
INFO    : aqtinstall(aqt) v3.0.2.dev11 on Python 3.10.6 [CPython GCC 11.3.0]
INFO    : You are installing the android version of Qt, which requires that the desktop version of Qt is also installed. Now installing Qt: desktop 6.4.1 gcc_64
WARNING : Specified Qt version is unknown: 6.4.1.
INFO    : Downloading qttools...
INFO    : Downloading qtbase...
INFO    : Downloading qtdeclarative...
INFO    : Downloading qtsvg...
INFO    : Redirected: ftp.yz.yamagata-u.ac.jp
INFO    : Redirected: ftp.yz.yamagata-u.ac.jp
INFO    : Redirected: ftp.yz.yamagata-u.ac.jp
INFO    : Redirected: ftp.yz.yamagata-u.ac.jp
INFO    : Finished installation of qtsvg-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 3.58569239
INFO    : Downloading qttranslations...
INFO    : Finished installation of qttools-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 5.86575145
INFO    : Redirected: ftp.yz.yamagata-u.ac.jp
INFO    : Downloading qtbase...
INFO    : Finished installation of qtbase-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 10.55020444
INFO    : Redirected: ftp.yz.yamagata-u.ac.jp
INFO    : Downloading qtsvg...
INFO    : Finished installation of qttranslations-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 10.60716895
INFO    : Redirected: ftp.yz.yamagata-u.ac.jp
INFO    : Finished installation of qtdeclarative-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 15.21983997
INFO    : Finished installation of qtsvg-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z in 4.99439451
INFO    : Downloading qtdeclarative...
INFO    : Downloading qttools...
INFO    : Downloading qttranslations...
INFO    : Redirected: ftp.yz.yamagata-u.ac.jp
INFO    : Redirected: ftp.yz.yamagata-u.ac.jp
INFO    : Redirected: ftp.yz.yamagata-u.ac.jp
INFO    : Finished installation of qtbase-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z in 13.91680251
INFO    : Finished installation of qttranslations-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z in 8.86879561
INFO    : Downloading qtwayland...
INFO    : Downloading icu...
INFO    : Redirected: ftp.yz.yamagata-u.ac.jp
INFO    : Redirected: ftp.yz.yamagata-u.ac.jp
INFO    : Finished installation of qttools-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z in 25.95157577
INFO    : Finished installation of qtwayland-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z in 21.82308230
INFO    : Finished installation of icu-linux-Rhel7.2-x64.7z in 19.52644032
INFO    : Finished installation of qtdeclarative-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z in 33.75186424
INFO    : Patching Qt/6.4.1/android_arm64_v8a/bin/qmake
INFO    : Patching Qt/6.4.1/gcc_64/bin/qmake
... (continues)
```

then 

```
$ strings 6.4.1/android_arm64_v8a/bin/qmake|grep work
/Users/qt/work/install/bin/qmake -qtconf "$script_dir_path/target_qt.conf" $*
```

Here should be some thing like

```
/opt/Qt/6.4.1/gcc_64/bin/qmake -qtconf "$script_dir_path/target_qt.conf" $*
```

It may need to patch  android qmake binary, it is not necessary for Qt 6.4.0 and before

**Comment by ddalcino** [comment]
I think the logic that needs to change is here:

https://github.com/miurahr/aqtinstall/blob/2c8b23d649a0c856dd575cf376438b3e9edf4beb/aqt/updater.py#L38-L39

On Linux, before Qt 6.4.1, the path that we needed to patch was `/home/qt/work/install`. Now, the qmake file looks a lot more like the Mac version, in which we need to patch the patch `/Users/qt/work/install/bin/qmake`.

Personally, I think it makes sense to just patch both paths on all OSes, so we are not affected by strange choices by the Qt devs like this.

**Comment by ddalcino** [comment]
@vkuznetsovgn Can you please try #627, and let us know if it fixes the problem for you with `android_arm64_v8a`?

OT: I'm having some difficulty with `android_armv7`, and right now it looks like it might not work anywhere other than Windows.
