### ISSUE TITLE
cannot open input file Qt5WinExtras.lib

### ISSUE THREAD

**Issue by jmpoep** [miurahr/aqtinstall#629]
LINK : fatal error LNK1181: cannot open input file 'D:\a\RpcView\RpcView\Qt\5.15.2\msvc2019_64\lib\Qt5WinExtras.lib' [D:\a\RpcView\RpcView\build\RpcView\RpcView.vcxproj]

When I tried to compile the project, I found that the static library Qt5WinExtras.lib was not found
The configuration is as follows：
version: '5.15.2'
host: 'windows'
target: 'desktop'
arch: 'win64_msvc2019_64'
aqtversion: '==3.1.0'
py7zrversion: '==0.20.2'

**Comment by miurahr** [comment]
command line?

**Comment by ddalcino** [comment]
@jmpoep Please try using this command to install qt:

```bash
python -m aqt install-qt windows desktop 5.15.2 win64_msvc2019_64
```

When I use this command, I see that the file you're looking for is installed in the expected location:

```console
$ ls -alh ./5.15.2/msvc2019_64/lib/Qt5WinExtras.lib
Permissions Size User Date Modified Name
.rw-r--r--   93k dave  6 Nov  2020  5.15.2/msvc2019_64/lib/Qt5WinExtras.lib
```

Maybe your linker is looking for libs in the wrong directory?

**Comment by jmpoep** [comment]
Requirement already satisfied: cffi>=1.14.0 in c:\hostedtoolcache\windows\python\3.11.0\x64\lib\site-packages (from bcj-cffi<0.6.0,>=0.5.1->py7zr>=0.15.1->aqtinstall==1.2.5) (1.15.1)
Requirement already satisfied: pycparser in c:\hostedtoolcache\windows\python\3.11.0\x64\lib\site-packages (from cffi>=1.14.0->bcj-cffi<0.6.0,>=0.5.1->py7zr>=0.15.1->aqtinstall==1.2.5) (2.21)
Building wheels for collected packages: patch
  Building wheel for patch (setup.py): started
  Building wheel for patch (setup.py): finished with status 'done'
  Created wheel for patch: filename=patch-1.16-py3-none-any.whl size=12393 sha256=6c324a6eb344b138fde3566ad5ce79e76ba3dce11a2a73b40ad4027627d509b2
  Stored in directory: c:\users\runneradmin\appdata\local\pip\cache\wheels\2a\77\09\4b1d894d9a37a3f65f360d69c737e1ef95af0cb343cae9b6ae
Successfully built patch
Installing collected packages: patch, urllib3, semantic-version, idna, charset-normalizer, certifi, requests, aqtinstall
Successfully installed aqtinstall-1.2.5 certifi-2022.12.7 charset-normalizer-2.1.1 idna-3.4 patch-1.16 requests-2.28.1 semantic-version-2.10.0 urllib3-1.26.13
python -m aqt install 5.15.2 windows desktop win64_msvc2019_64 -O D:\a\RpcView/Qt
aqtinstall(aqt) v1.2.5 on Python 3.11.0 [CPython MSC v.1933 64 bit (AMD64)]
Downloading qtbase...
Downloading qtsvg...
Downloading qttranslations...
Downloading qtactiveqt...
Redirected: mirrors.ocf.berkeley.edu
Redirected: mirrors.ocf.berkeley.edu
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtsvg-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.62843690
Downloading qtdeclarative...
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtactiveqt-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.87948610
Downloading qtmultimedia...
Finished installation of qttranslations-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 2.18324410
Downloading qtgraphicaleffects...
Redirected: mirrors.ocf.berkeley.edu
Redirected: mirrors.ocf.berkeley.edu
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtgraphicaleffects-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.45887910
Downloading qtwinextras...
Finished installation of qtmultimedia-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.89623040
Downloading qttools...
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtwinextras-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.52692740
Downloading qtimageformats...
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtdeclarative-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 4.22270250
Downloading qtsensors...
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtimageformats-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.51731650
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtsensors-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.59241790
Downloading qtwebsockets...
Downloading qtwebchannel...
Redirected: mirrors.ocf.berkeley.edu
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtwebchannel-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.77739850
Downloading qtlocation...
Finished installation of qtwebsockets-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.48170330
Downloading qtserialport...
Finished installation of qttools-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 5.84134630
Downloading qtxmlpatterns...
Redirected: mirrors.ocf.berkeley.edu
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtserialport-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.43659680
Downloading qtquickcontrols...
Finished installation of qtbase-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 10.83547300
Downloading qtconnectivity...
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtlocation-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 2.13955000
Downloading qtquickcontrols2...
Finished installation of qtxmlpatterns-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 2.05756570
Downloading qtwebview...
Redirected: mirrors.ocf.berkeley.edu
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtconnectivity-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.90725850
Redirected: mirrors.ocf.berkeley.edu
Downloading qtscxml...
Finished installation of qtquickcontrols-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 2.06674790
Downloading qtspeech...
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtwebview-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.46834690
Downloading qtserialbus...
Finished installation of qtquickcontrols2-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 2.20256060
Downloading qt3d...
Redirected: mirrors.ocf.berkeley.edu
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtspeech-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.43789240
Downloading qtremoteobjects...
Finished installation of qtscxml-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.625[117](https://github.com/jmpoep/RpcView/actions/runs/3647406297/jobs/6159599269#step:3:118)10
Downloading qtgamepad...
Redirected: mirrors.ocf.berkeley.edu
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtserialbus-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.52966590
Downloading d3dcompiler_47...
Redirected: mirrors.ocf.berkeley.edu
Redirected: mirrors.ocf.berkeley.edu
Finished installation of qtremoteobjects-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.56423630
Finished installation of qtgamepad-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 1.47346680
Redirected: mirrors.ocf.berkeley.edu
Finished installation of d3dcompiler_47-x64.7z in 1.5955[135](https://github.com/jmpoep/RpcView/actions/runs/3647406297/jobs/6159599269#step:3:136)0
Downloading opengl32sw...
Finished installation of qt3d-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z in 3.34653630
Redirected: mirrors.ocf.berkeley.edu
Finished installation of opengl32sw-64-mesa_12_0_rc2.7z in 2.18427780
Patching D:\a\RpcView\Qt\5.15.2\msvc2019_64\bin\qmake.exe
Finished installation
Time elapsed: 21.[142](https://github.com/jmpoep/RpcView/actions/runs/3647406297/jobs/6159599269#step:3:143)00610 second

**Comment by jmpoep** [comment]
LINK : fatal error LNK1181: cannot open input file 'D:\a\RpcView\RpcView\Qt\5.15.2\msvc2019_64\lib\Qt5WinExtras.lib' [D:\a\RpcView\RpcView\build\RpcView\RpcView.vcxproj]
Error: Process completed with exit code 1.

**Comment by ddalcino** [comment]
> python -m aqt install 5.15.2 windows desktop win64_msvc2019_64 -O D:\a\RpcView/Qt

> LINK : fatal error LNK1181: cannot open input file 'D:\a\RpcView\RpcView\Qt\5.15.2\msvc2019_64\lib\Qt5WinExtras.lib' 

The file you are looking for should be at `D:\a\RpcView\Qt\5.15.2\msvc2019_64\lib\Qt5WinExtras.lib`. Your linker is looking for it at `D:\a\RpcView\RpcView\Qt\5.15.2\msvc2019_64\lib\Qt5WinExtras.lib`.

Also, please consider using a more recent version of aqtinstall. You are using v 1.2.5, which is no longer supported.
