### ISSUE TITLE
ERROR: Detected a package name collision

### ISSUE THREAD

**Issue by vkuznetsovgn** [miurahr/aqtinstall#632]
This bug happened to me when I added `qthttpserver` to an installation. Without `qthttpserver` everything installs fine.

List cmd:
`$ aqt list-qt linux desktop --modules 6.4.2 gcc_64`
debug_info qt3d qt5compat qtcharts qtconnectivity qtdatavis3d qthttpserver qtimageformats qtlanguageserver qtlottie qtmultimedia qtnetworkauth qtpdf qtpositioning qtquick3d qtquick3dphysics qtquicktimeline qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtshadertools qtspeech qtvirtualkeyboard qtwaylandcompositor qtwebchannel qtwebengine qtwebsockets qtwebview

Install cmd:
`$ aqt install-qt -O /opt/Qt linux desktop 6.4.2 gcc_64 --m qt5compat qtcharts qthttpserver qtimageformats qtlottie qtmultimedia qtquicktimeline qtspeech qtwebchannel qtwebsockets qthttpserver`

INFO    : aqtinstall(aqt) v3.1.0 on Python 3.10.6 [CPython GCC 11.3.0]
WARNING : Specified Qt version is unknown: 6.4.2.
ERROR   : Detected a package name collision
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aqt/installer.py", line 177, in run
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/aqt/installer.py", line 400, in run_install_qt
    qt_archives: QtArchives = retry_on_bad_connection(
  File "/usr/local/lib/python3.10/dist-packages/aqt/helper.py", line 165, in retry_on_bad_connection
    return function(base_url)
  File "/usr/local/lib/python3.10/dist-packages/aqt/installer.py", line 401, in <lambda>
    lambda base_url: QtArchives(
  File "/usr/local/lib/python3.10/dist-packages/aqt/archives.py", line 300, in __init__
    self._get_archives()
  File "/usr/local/lib/python3.10/dist-packages/aqt/archives.py", line 365, in _get_archives
    self._get_archives_base(f"qt{self.version.major}_{self._version_str()}{self._arch_ext()}", self._target_packages())
  File "/usr/local/lib/python3.10/dist-packages/aqt/archives.py", line 361, in _target_packages
    target_packages.add(module, package_names)
  File "/usr/local/lib/python3.10/dist-packages/aqt/archives.py", line 94, in add
    assert package_name not in self._packages_to_modules, "Detected a package name collision"
AssertionError: Detected a package name collision
ERROR   : aqtinstall(aqt) v3.1.0 on Python 3.10.6 [CPython GCC 11.3.0]
Working dir: `/`
Arguments: `['/usr/local/bin/aqt', 'install-qt', '-O', '/opt/Qt', 'linux', 'desktop', '6.4.2', 'gcc_64', '--m', 'qt5compat', 'qtcharts', 'qthttpserver', 'qtimageformats', 'qtlottie', 'qtmultimedia', 'qtquicktimeline', 'qtspeech', 'qtwebchannel', 'qtwebsockets', 'qthttpserver']` Host: `uname_result(system='Linux', node='4a4d7c6111e3', release='5.15.0-53-generic', version='#59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022', machine='x86_64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues
Please remember to include a copy of this program's output in your report.

**Comment by ddalcino** [comment]
This is definitely a CLI bug, but there's an easy workaround. You have the module `qthttpserver` listed twice in your command. If you remove one of the duplicates, your command should work properly.

**Comment by ddalcino** [comment]
#633 should fix this, if you want to try it. You should be able to put `qthttpserver` into the module list as many times as you want and it should still work.

The CI runs are failing right now due to an issue with tox; I'm not sure what the problem is, but it exists in the master branch as well.

**Comment by vkuznetsovgn** [comment]
Hi!
I tried the fix and yes it is working now.
