### ISSUE TITLE
Allow changing paths of qt installation 

### ISSUE THREAD

**Issue by asdf8dfafjk** [miurahr/aqtinstall#635]
Currently an installation cannot be moved.

Possible solution:

Keep a .aqtinstall directory and a file patched_files that lists all files that have been patched. This work would be done at installation. 

Now a command line switch `--update_prefix` and `--base_path` would cause aqtinatall to read `.aqtinstall/patches_files` from base_path and update prefix to argument of `update_prefix` for all such files in the list.

Arguably not a frequent use case but just wanted to throw it around

**Comment by miurahr** [comment]
FYI: "Qt  is relocatable"
https://www.qt.io/blog/qt-is-relocatable

>As of version 5.14.0 Qt is relocatable, i.e. it is possible to move the Qt installation to a different directory without breaking functionality or loading of plugins.

**Comment by asdf8dfafjk** [comment]
Thank you. So i wrote this comment after i relocated "knowing" that like earlier things won't work. But they did and i didn't bother to investigate :-)
