### ISSUE TITLE
Support for version 5.15.8

### ISSUE THREAD

**Issue by loikki** [miurahr/aqtinstall#636]
Hi,

Thanks for this amazing software. It is so much better than what Qt is able to provide :)

**Is your feature request related to a problem? Please describe.**
I am currently trying to develop an app for android using pyqtdeploy which supports only qt 5. Unfortunately, there is a bug that prevents running on android in 5.15.2 (https://bugreports.qt.io/browse/QTBUG-71590?focusedCommentId=687317). 

**Describe the solution you'd like**
Could it be possible to add support for Qt 5.15.8?

**Describe alternatives you've considered**
I tried to use Qt 6 but unfortunately pyqtdeploy is not compatible.

**Comment by ddalcino** [comment]
> Could it be possible to add support for Qt 5.15.8?

Unfortunately not. Qt 5.15.3 - 5.15.8 are paid software, and binaries are not available from the repositories that `aqtinstall` uses at https://download.qt.io/online/qtsdkrepository/ . If you wish to build from source, the source code for these versions is available at https://download.qt.io/official_releases/qt/5.15/ , but `aqtinstall` cannot help you do that.

If you need more recent bug fixes than 5.15.2, you could try using 5.12.12. Qt 5.12 is past end-of-life, but the most recent bugfix is dated November 2021 (5.15.2 was released in November 2020).

Good luck with Python Qt development for Android. I know very little about the subject, but it sounds quite difficult.

**Comment by loikki** [comment]
Thanks a lot for the information. It is a shame that Qt does not provide a better support to the open source community. 

Riverbank has done a good job on enabling PyQt for android but unfortunately it seems that they lack some man power to make it easy. Anyway, I will move another project to C++, it will be more easy.

Thanks a lot again for your software, I will clearly continue to use it :)
Best regards,

**Comment by Kidev** [comment]
#878

**Comment by loikki** [comment]
Thanks!

**Comment by Kidev** [comment]
Supported as of [v3.2.0](https://github.com/miurahr/aqtinstall/releases/tag/v3.2.0)
