### ISSUE TITLE
Install Qt on github CI

### ISSUE THREAD

**Issue by ghost** [miurahr/aqtinstall#644]
**Describe the bug**
Installing qt5 on github actions

**To Reproduce**
use the module with the following parameters:

- name: Installation Qt 5 Linux
          uses: jurplel/install-qt-action@v3
          with:
            version: '5.15.2'
            host: 'linux'
            target: 'desktop'
            arch: 'gcc_64'
            modules: 'Qt Charts for gcc 64-bit Qt Data Visualization for gcc 64-bit Qt Lottie Animation for gcc 64-bit Qt Network Authorization for gcc 64-bit Qt Purchasing for gcc 64-bit Qt Quick 3D for gcc 64-bit Qt Quick Timeline for gcc 64-bit Qt Script for gcc 64-bit Qt Virtual Keyboard for gcc 64-bit Qt Wayland Compositor for gcc 64-bit Qt WebEngine for Desktop gcc 64-bit Qt WebGL Streaming Plugin for gcc 64-bit'
            dir: '${{ github.workspace }}/src/'
            install-deps: 'true'
            archives: 'qtbase qtsvg'
            cache: 'false'
            cache-key-prefix: 'install-qt-action'
            setup-python: 'true'
            tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
            set-env: 'true'
            tools-only: 'false'
            aqtversion: '==3.1.0'
            py7zrversion: '>=0.20.2'
            extra: '--external 7z'

**`aqt` output**
Add program output to help explain your problem.

```
INFO    : aqtinstall(aqt) v3.1.0 on Python 3.11.1 [CPython GCC 11.3.0]
WARNING : Some of specified modules are unknown.
ERROR   : Detected a package name collision
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/installer.py", line 177, in run
    args.func(args)
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/installer.py", line [400](https://github.com/SebMeloni59/Testci/actions/runs/4142893166/jobs/7164103571#step:4:404), in run_install_qt
    qt_archives: QtArchives = retry_on_bad_connection(
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/helper.py", line 165, in retry_on_bad_connection
    return function(base_url)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/installer.py", line [401](https://github.com/SebMeloni59/Testci/actions/runs/4142893166/jobs/7164103571#step:4:405), in <lambda>
    lambda base_url: QtArchives(
                     ^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/archives.py", line 300, in __init__
    self._get_archives()
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/archives.py", line 365, in _get_archives
    self._get_archives_base(f"qt{self.version.major}_{self._version_str()}{self._arch_ext()}", self._target_packages())
                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/archives.py", line 361, in _target_packages
    target_packages.add(module, package_names)
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/archives.py", line 94, in add
    assert package_name not in self._packages_to_modules, "Detected a package name collision"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Detected a package name collision
ERROR   : aqtinstall(aqt) v3.1.0 on Python 3.11.1 [CPython GCC 11.3.0]
Working dir: `/home/runner/work/Testci/Testci`
Arguments: `['/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/__main__.py', 'install-qt', 'linux', 'desktop', '5.15.2', 'gcc_64', '--outputdir', '/home/runner/work/Testci/Testci/src//Qt', '--modules', 'Qt', 'Charts', 'for', 'gcc', '64-bit', 'Qt', 'Data', 'Visualization', 'for', 'gcc', '64-bit', 'Qt', 'Lottie', 'Animation', 'for', 'gcc', '64-bit', 'Qt', 'Network', 'Authorization', 'for', 'gcc', '64-bit', 'Qt', 'Purchasing', 'for', 'gcc', '64-bit', 'Qt', 'Quick', '3D', 'for', 'gcc', '64-bit', 'Qt', 'Quick', 'Timeline', 'for', 'gcc', '64-bit', 'Qt', 'Script', 'for', 'gcc', '64-bit', 'Qt', 'Virtual', 'Keyboard', 'for', 'gcc', '64-bit', 'Qt', 'Wayland', 'Compositor', 'for', 'gcc', '64-bit', 'Qt', 'WebEngine', 'for', 'Desktop', 'gcc', '64-bit', 'Qt', 'WebGL', 'Streaming', 'Plugin', 'for', 'gcc', '64-bit', '--archives', 'qtbase', 'qtsvg', '--external', '7z']` Host: `uname_result(system='Linux', node='fv-az563-273', release='5.15.0-1031-azure', version='#38-Ubuntu SMP Mon Jan 9 12:49:59 UTC 20...
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues
Please remember to include a copy of this program's output in your report.
Error: Error: The process '/opt/hostedtoolcache/Python/3.11.1/x64/bin/python3' failed with exit code 254
[CompleteLog.txt](https://github.com/miurahr/aqtinstall/files/10706278/CompleteLog.txt)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1
 - `aqt` version 3.1.0
 - py7zrversion = 0.20.2

**Additional context**

**Comment by ddalcino** [comment]
Duplicate #632.

Also, please be careful with the list of modules; that doesn't look like valid input for aqtinstall.

**Comment by miurahr** [comment]
I'd like to release the next ASAP.

**Comment by miurahr** [comment]
@SebMeloni59  could you retry with  v3.1.1?  I think You will get different result.

**Comment by ddalcino** [comment]
This might be a leap in logic, but I think this issue might be a result of https://github.com/ddalcino/aqt-list-server/issues/10. That project automatically builds an `install-qt-action` yaml step for you, and it has a bug right now that populates the `modules:` section improperly when you click the "Check all modules" button.

This is the only reason I can think of that anyone would mistakenly write the descriptions of the modules in the "modules" section instead of the actual module names. I messed up, sorry about that!

**Comment by ddalcino** [comment]
> This might be a leap in logic, but I think this issue might be a result of [ddalcino/aqt-list-server#10](https://github.com/ddalcino/aqt-list-server/issues/10). That project automatically builds an `install-qt-action` yaml step for you, and it has a bug right now that populates the `modules:` section improperly when you click the "Check all modules" button.

@SebMeloni59, if you were using [aqt-list-server](https://ddalcino.github.io/aqt-list-server/) to generate this `install-qt-action` yaml step, please try using [aqt-list-server](https://ddalcino.github.io/aqt-list-server/) again. [ddalcino/aqt-list-server#10](https://github.com/ddalcino/aqt-list-server/issues/10) is now fixed.

**Comment by ddalcino** [comment]
@miurahr, it looks like the OP's user account was deleted. I don't think they are going to come back here to update this issue. Since this is a duplicate anyway, should we close the issue?
