### ISSUE TITLE
Feature: make the message about "unknown" Qt versions and modules more friendly and easy to understand

### ISSUE THREAD

**Issue by pzhlkj6612** [miurahr/aqtinstall#646]
**Is your feature request related to a problem? Please describe.**

Like jurplel/install-qt-action#172, there are some users who are afraid of installing unknown Qt stuff to the CI environment or their computers. To reduce confusion, we'd better make the message more friendly and easy to understand.

**Describe the solution you'd like**

Just monkey-typing:

```diff
- Specified Qt version is unknown: 6.4.5.
+ Specified Qt version "6.4.5" may be released after this version of aqtinstall. We will try our best.
```

```diff
- Some of specified modules are unknown.
+ Specified modules "foo", "bar" and "baz" may be released after this version of aqtinstall. We will try our best.
```

**Describe alternatives you've considered**

Be polite, be gentle. :)

**Additional context**

None.

/cc @ddalcino

**Comment by ddalcino** [comment]
The proposed language is already a big improvement, but I think we could go further.

I’ve noticed in other issues here and on install-Qt-action that it’s often a little difficult to know exactly what aqtinstall has done, for instance, what version it installed, what directory it used, what’s the path to qmake, etc. In the case of android/wasm/qt6/`--autodesktop`, it could be useful to add additional info about the desktop version installed, or expected to be installed.

We could do something like: at the end of a successful installation, log all that data with the INFO tag. Another option could be to print it in a json file with some predefined format, so the user doesn’t have to parse stdout messages that may change over time. IDK, maybe that should be a separate issue from this.

**Comment by ddalcino** [comment]
How about:

```diff
-  Specified Qt version is unknown: 6.4.5.
+  Specified Qt version "6.4.5" did not exist when this version of aqtinstall was released. We will try our best.
```

```diff
-  Some of specified modules are unknown.
+  Specified modules ["foo", "bar", "baz"] did not exist when this version of aqtinstall was released. We will try our best.
```

I don't think that `["foo", "bar", "baz"]` makes a better warning message than `"foo", "bar" and "baz"`, but I expect it will be easier to write.
