### ISSUE TITLE
QT6 tools (mingw version match)

### ISSUE THREAD

**Issue by atsju** [miurahr/aqtinstall#655]
**Is your feature request related to a problem? Please describe.**
I did some research and QT6 does not list the exact mingw used in package name or whatever you use to match. So aqt cannot download the exact version though `aqt install-tool`
See in https://wiki.qt.io/MinGW and maybe somewhere else what version is used.

**Describe the solution you'd like**
I would be great to be able to download the correct tool or at least to know the correct version of tool to use.

**Describe alternatives you've considered**
I'm new to QT and aqt, I'm open to suggestions.

**Additional context**
None

**Comment by ddalcino** [comment]
I think the documentation at https://aqtinstall.readthedocs.io/en/latest/getting_started.html should be a little more explicit about this, and updated for the newer versions of Qt 6.

You're right that Qt versions 6.2.3-6.5.0 don't make it clear which version of mingw you should be using; the architecture `win64_mingw` is not very specific. However, with the following command, it should be clear that Qt 6.2.3 `win64_mingw` was built using MinGW 11.2.0:

```console
$ python -m aqt list-qt windows desktop --long-modules 6.2.3 win64_mingw
   Module Name                 Display Name              Release Date   Download Size   Installed Size
======================================================================================================
debug_info          Desktop MinGW 11.2.0 64-bit debug    2022-01-26     909.7M          5.4G
                    information files
qt3d                Qt 3D for MinGW 11.2.0 64-bit        2022-01-26     2.6M            22.0M
qt5compat           Qt 5 Compatibility Module for        2022-01-26     552.1K          1.9M
                    MinGW 11.2.0 64-bit
qtactiveqt          Qt 3D for MinGW 11.2.0 64-bit        2022-01-26     6.0M            33.8M
qtcharts            Qt Charts for MinGW 11.2.0 64-bit    2022-01-26     730.1K          7.8M
qtconnectivity      Qt Connectivity for MinGW 11.2.0     2022-01-26     196.2K          1.5M
                    64-bit
...
```

The following commands should provide enough information to figure out how to install MinGW 11.2.0. Just don't ask why the Qt maintainers put MinGW 11.2.0 inside `tools_mingw90` and `qt.tools.win64_mingw900`; that's a mystery I'll never understand.

```console
$ python -m aqt list-tool windows desktop
... (omitted)
tools_mingw90
tools_mingw
...

$ python -m aqt list-tool windows desktop tools_mingw90 -l
 Tool Variant Name           Version          Release Date      Display Name           Description
======================================================================================================
qt.tools.win64_mingw   9.0.0-1-202203221220   2022-03-22     MinGW 11.2.0 64-bit   MinGW-builds 11.2.0
900                                                                                64-bit toolchain
                                                                                   with gcc 11.2.0
```

**Comment by atsju** [comment]
Well hidden 
I would never have found these informations without you. Thank you!
