### ISSUE TITLE
Feature: Install Modules Only

### ISSUE THREAD

**Issue by sevketcaba** [miurahr/aqtinstall#673]
**Is your feature request related to a problem? Please describe.**
When creating docker images, it's easier to start from a base and then extend the image with features. When it comes to the development environment for Qt, I'd like to have a base development environment as a docker image, and then would like to extend it with modules. This will reduce image build times significantly.

**Describe the solution you'd like**
The solution that I'd like to have is as following :

Base Dockerfile :
--
Tag : Qt6-dev-base:6.5.0
Content:
```
FROM ubuntu:22.04

.
.
.

ARG QT=6.5.0
ARG QT_HOST=linux
ARG QT_TARGET=desktop
ARG QT_ARCH=gcc_64

RUN aqt install-qt --outputdir /opt/qt ${QT_HOST} ${QT_TARGET} ${QT} ${QT_ARCH}
```

Extended Docker File:

```
FROM Qt6-dev-base:6.5.0

ARG QT=6.5.0
ARG QT_HOST=linux
ARG QT_TARGET=desktop
ARG QT_ARCH=gcc_64
ARG QT_MODULES="qtquick3d qtshadertools"

RUN aqt install-qt-modules --outputdir /opt/qt ${QT_HOST} ${QT_TARGET} ${QT} ${QT_ARCH} ${QT_MODULES}

```

**Describe alternatives you've considered**
an alternative would be as following :
```
RUN aqt install-qt --outputdir /opt/qt ${QT_HOST} ${QT_TARGET} ${QT} ${QT_ARCH} --modules-only ${QT_MODULES}
```

**Additional context**
No additional context

**Comment by ddalcino** [comment]
Please refer to the `--noarchives` option documented here: https://aqtinstall.readthedocs.io/en/latest/cli.html#cmdoption-install-qt-noarchives . Unless I am missing something, this option already does exactly what you are describing here.

**Comment by miurahr** [comment]
There is no further question or feedback.
