### ISSUE TITLE
Install fail for the qt6.5.0 of msvc 

### ISSUE THREAD

**Issue by KangLin** [miurahr/aqtinstall#675]
- Run jurplel/install-qt-action@v3
  with:
    dir: D:\a\RabbitCommon\RabbitCommon\.cache\tools\qt
    version: 6.5.0
    arch: win64_msvc2019_64
    modules: qtwebengine qtscxml qtwebengine
    target: desktop
    install-deps: true
    cache-key-prefix: install-qt-action
    setup-python: true
    set-env: true
    tools-only: false
    aqtversion: ==2.1.*
    py7zrversion: ==0.19.*
  env:
    SOURCE_DIR: D:\a\RabbitCommon\RabbitCommon\.cache\source
    TOOSL_DIR: D:\a\RabbitCommon\RabbitCommon\.cache\tools
    INSTALL_DIR: D:\a\RabbitCommon\RabbitCommon\.cache\install_msvc_x64-windows_Debug
    CMAKE_GENERATOR: Visual Studio 17 2022
    VCPKG_PLATFORM_TOOLSET: v142
    CMAKE_GENERATOR_PLATFORM: x64
    RabbitCommon_VERSION: v1.0.12
    VCPKGGITCOMMITID: 9c7c66471005cb132832786d5d65d83d2cf503ad
    qt_modules: qtwebengine qtscxml qtwebengine
    artifact_name: build_msvc
- Run actions/setup-python@v4
  with:
    python-version: 3.6.x - 3.11.x
    check-latest: false
    token: ***
    update-environment: true
    allow-prereleases: false
  env:
    SOURCE_DIR: D:\a\RabbitCommon\RabbitCommon\.cache\source
    TOOSL_DIR: D:\a\RabbitCommon\RabbitCommon\.cache\tools
    INSTALL_DIR: D:\a\RabbitCommon\RabbitCommon\.cache\install_msvc_x64-windows_Debug
    CMAKE_GENERATOR: Visual Studio 17 2022
    VCPKG_PLATFORM_TOOLSET: v142
    CMAKE_GENERATOR_PLATFORM: x64
    RabbitCommon_VERSION: v1.0.12
    VCPKGGITCOMMITID: 9c7c66471005cb132832786d5d65d83d2cf503ad
    qt_modules: qtwebengine qtscxml qtwebengine
    artifact_name: build_msvc
Installed versions
  Successfully set up CPython (3.11.3)
- Run jurplel/install-qt-action/action@v3
  with:
    assert package_name not in self._packages_to_modules, "Detected a package name collision"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Detected a package name collision
aqtinstall(aqt) v2.1.0 on Python 3.11.3 [CPython MSC v.1934 64 bit (AMD64)]
Working dir: `D:\a\RabbitCommon\RabbitCommon`
Arguments: `['C:\\hostedtoolcache\\windows\\Python\\3.11.3\\x64\\Lib\\site-packages\\aqt\\__main__.py', 'install-qt', 'windows', 'desktop', '6.5.0', 'win64_msvc2019_64', '--outputdir', 'D:\\a\\RabbitCommon\\RabbitCommon\\.cache\\tools\\qt/Qt', '--modules', 'qtwebengine', 'qtscxml', 'qtwebengine']` Host: `uname_result(system='Windows', node='fv-az449-794', release='10', version='10.0.20348', machine='AMD64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues.
Please remember to include a copy of this program's output in your report.

**Comment by ddalcino** [comment]
Duplicates #632 #644. Fixed in v3.1.1.

Please use a newer version of aqtinstall, or don't write `qtwebengine` twice in your list of modules.
