### ISSUE TITLE
QCharts

### ISSUE THREAD

**Issue by LorenzE** [miurahr/aqtinstall#68]
Is there any way to include specific modules like QCharts into the install process?

**Comment by miurahr** [comment]
In version 0.5, it try to install all of extra modules like qcharts, but not the all.

In version 0.6a1 and later, aqt has an option '-m' or '--module' that accept list of extra modules such as

```bash
$ python -m aqt install 5.14.0 linux desktop -m qcharts,qtnetworkauth
```

**Comment by LorenzE** [comment]
fantastic. works like a charm.
