### ISSUE TITLE
Missing Qt5Pdf module

### ISSUE THREAD

**Issue by alassagne-sl** [miurahr/aqtinstall#683]
Hi,
Even when enabling all the module during the installation of Qt 5.15, some are not installed, including Qt5Pdf. 
It's actually quite difficult to understand whether it's a module or not, because Qt has both modules and add-ons : https://doc.qt.io/qt-5.15/qtmodules.html

Should aqt provide an optional installation for this ?
Qt does not provide a way to download these with their installer either.

**Comment by miurahr** [comment]
Here is a document how to install QtPDF. They may not provide a binary. Link in maket place returns 404.
https://wiki.qt.io/QtPDF_Build_Instructions

**Comment by miurahr** [comment]
FYI: https://www.reddit.com/r/QtFramework/comments/prapx9/how_to_get_to_use_qtpdf/
