### ISSUE TITLE
Add support for QT 6.6.0

### ISSUE THREAD

**Issue by VocalFan** [miurahr/aqtinstall#694]
**Is your feature request related to a problem? Please describe.**
I use Install Qt for my projects, which depends on aqtinstall... This project. I've noticed that 6.6.0 seems to not be supported right now.

**Describe the solution you'd like**
Implementation of support for Qt 6.6.0

**Describe alternatives you've considered**
None that I have found so far...

**Additional context**
```
C:\hostedtoolcache\windows\Python\3.11.4\x64\python.exe -m aqt install-qt windows desktop 6.* win64_msvc2019_64 --outputdir D:\a\obliteration/Qt
INFO    : aqtinstall(aqt) v3.1.6 on Python 3.11.4 [CPython MSC v.1934 64 bit (AMD64)]
INFO    : Resolved spec '6.*' to 6.6.0
WARNING : Specified Qt version "6.6.0" did not exist when this version of aqtinstall was released. This may not install properly, but we will try our best.
ERROR   : Failed to locate XML data for Qt version '6.6.0'.
==============================Suggested follow-up:==============================
* Please use 'aqt list-qt windows desktop' to show versions available.
Error: Error: The process 'C:\hostedtoolcache\windows\Python\3.11.4\x64\python.exe' failed with exit code 1
```

**Comment by miurahr** [comment]
6.6.0-Beta2 Release is in 14.07.2023 and final release is in 10.10.2023.
The bug ticket is raised in 14, Jul when the Qt Foundation published the 6.6.0-Beta2.
This may be happended The Qt Foundation wrongly made a folder for 6.6.0 for beta2 then unhappily aqtinstall catch it.
