### ISSUE TITLE
potential security issue in tar extraction

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#700]
Synk warned

> Calling extractall to extract all files from a tar file without sanitization. This may result files outside destination directory to be overwritten, resulting in an arbitrary file write.
https://github.com/miurahr/aqtinstall/blob/ebc8175deb13eb24bf8acf57533038ec21dd0c77/aqt/installer.py#L1229

python `tarfile` provide filter function for sanitization. it can be

```
  tar_archive.extractall(path=base_dir, filter='tar') 
```

**Comment by miurahr** [comment]
the `filter` parameter is introduced since most recent python 3.11.4

**Comment by ddalcino** [comment]
Great idea!

Docs on available extraction filters:
https://docs.python.org/3/library/tarfile.html#extraction-filters

Guidance on how to implement this in a way that won't break on older versions of Python:
https://docs.python.org/3/library/tarfile.html#supporting-older-python-versions

example:
```python
if hasattr(tarfile, 'data_filter'):
    my_tarfile.extractall(filter='data')
else:
    # remove this when no longer needed
    warn_the_user('Extracting may be unsafe; consider updating Python')
    my_tarfile.extractall()
```

I'm not too sure about what extraction filter setting we should be using here, or if we would want to make it user-settable. According to the docs, `'tar'` sounds like a good default setting. I imagine some users may want to use the more restrictive `'data'` setting, but I don't know enough about the tar files on download.qt.io to know that it won't break anything. IIRC, the tar files are used in "source/doc/examples" installations; I thought those were mostly text files.
