### ISSUE TITLE
Failed to install or list Qt IFW

### ISSUE THREAD

**Issue by igormironchik** [miurahr/aqtinstall#709]
**Describe the bug**
Failed to install or list Qt IFW.

**To Reproduce**

1. Run `aqt list-tool linux desktop tools_ifw -l`.
2. See error:
    ```
    ERROR   : Failed to download checksum for the file 'Updates.xml' from mirrors '['https://download.qt.io']
    ==============================Suggested follow-up:==============================
    * Check your internet connection
    * Consider modifying `requests.max_retries_to_retrieve_hash` in settings.ini
    * Consider modifying `mirrors.trusted_mirrors` in settings.ini (see https://aqtinstall.readthedocs.io/en/stable/configuration.html#configuration)
    ```

**Desktop (please complete the following information):**
 - OS: [Linux, Windows]
 - `aqt` version [`aqtinstall(aqt) v3.1.7 on Python 3.10.12 [CPython GCC 11.4.0]`]

**Comment by ddalcino** [comment]
Duplicate #578. Try it again tomorrow. That command won't work until the server generates the sha256 hash, and that typically happens around 24 hrs after the release of a new version.

**Comment by igormironchik** [comment]
You are right! Everything is fine now...
