### ISSUE TITLE
Support python 3.11 & 3.9

### ISSUE THREAD

**Issue by nrbnlulu** [miurahr/aqtinstall#712]
Support python 3.11 and 3.9 the workflows only run for 3.10 <s>and I can't install on 3.11</s>

**Comment by ddalcino** [comment]
Works OK for me on python 3.8, 3.9, 3.10, and 3.11.

If you're trying to report a bug, we can't help without more information. The 'bug report' template exists for a reason, and I suggest you use it.

**Comment by nrbnlulu** [comment]
Never said that there is a bug. I said it didn't worked for me and the workflows doesn't cover python 3.8 3.11

**Comment by pzhlkj6612** [comment]
@nrbnlulu 

> it didn't worked for me...

To you, that's exactly a bug, isn't it?

I think you should post the error message here or in a new issue with the ['bug report' template](https://github.com/miurahr/aqtinstall/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=).

**Comment by nrbnlulu** [comment]
I already fixed that. Though this doesn't mean that aqtinstall "*supports*" anything other than 3.10.

**Comment by pzhlkj6612** [comment]
> > To you, that's exactly a bug, isn't it?
> 
> I already fixed that.

OK, good to hear that.

---

It seems that the Azure Pipeline tests Python 3.9: https://github.com/miurahr/aqtinstall/blob/4f2bdda951910cec08037a58f23c503257b38111/azure-pipelines.yml

As @nrbnlulu said, the GitHub Actions workflow doesn't cover python 3.8, 3.9 and 3.11. Adding them to "workflows/test-install-qt.yml" looks OK. Opinions?

**Comment by nrbnlulu** [comment]
> It seems that the Azure Pipeline tests Python 3.9: https://github.com/miurahr/aqtinstall/blob/4f2bdda951910cec08037a58f23c503257b38111/azure-pipelines.yml

Thanks. so, this is closeable. Sorry for the redundant issue.

**Comment by pzhlkj6612** [comment]
Well, please wait. Python 3.8 & 3.11 are indeed not covered by our CI and we (including you) could discuss it in this issue, so you can keep this issue open. @nrbnlulu

**Comment by miurahr** [comment]
I can accept PR to add python 3.8 and 3.11 in CI.
It depends only on free tier service cpu time on Azure-Pipelines or Github Actions.
