### ISSUE TITLE
Support jom installation

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#72]
Suggestioned here.
https://github.com/jurplel/install-qt-action/pull/10

**Comment by miurahr** [comment]
Here is a download url: https://download.qt.io/official_releases/jom/
All the other tools are downloaded and managed under https://download.qt.io/online/qtsdkrepository/

jom don't have a repository db as same as other Qt tool chains.
It is a way that just download zip file and extract it.

**Comment by LorenzE** [comment]
Hey, would love to help out here. @miurahr Can you point me to the right direction where to start?

**Comment by miurahr** [comment]
Here is my idea.

There are several files to be changed.

* Add command line option: https://github.com/miurahr/aqtinstall/blob/master/aqt/cli.py#L190
   aqtinstall uses python standard [argparse](https://docs.python.org/3/library/argparse.html)

* Add class to represent jom archive: https://github.com/miurahr/aqtinstall/blob/master/aqt/archives.py#L138

   Each class inherit QtArchive class which hold archive file name and link URL. Eg. JomArchive class

* Logic to specify download link: https://github.com/miurahr/aqtinstall/blob/master/aqt/cli.py#L143
   and create  JomArchive object and pass it to QtInstaller object.

* [QtInstaller](https://github.com/miurahr/aqtinstall/blob/master/aqt/installer.py#L81) class assumes package are compressed with 7-Zip.
   jom uses PkZip. so you need to detect or specify file format and use python standard [zipfile](https://docs.python.org/3/library/zipfile.html) to extract it.

**Comment by miurahr** [comment]
If you are ready to propose, please give us a Pull-Request.

**Comment by LorenzE** [comment]
actions/virtual-environments#135 might take care of this after all :)

**Comment by miurahr** [comment]
OK, then there is no obvious requirement for here.
I'd like to close.
