### ISSUE TITLE
Add macOS pre-build to releases

### ISSUE THREAD

**Issue by Steveice10** [miurahr/aqtinstall#721]
**Is your feature request related to a problem? Please describe.**

I use aqtinstall as part of a build script to download Qt on Windows and macOS for compiling against. For Windows it's very convenient to just download the pre-build from the latest release, whereas for macOS we have to rely on the system Python and PIP being available and compatible.

**Describe the solution you'd like**

I'd like to see macOS pre-builds be provided in the releases as well. It would save us the trouble of having to rely on the system Python and reduce the dependencies required for running our build script.

My understanding is this wouldn't be too difficult to do since PyInstaller already supports emitting a single UNIX-style binary for macOS.

**Describe alternatives you've considered**

Alternative would be to continue on like we are, but having that extra dependency in our build script on system Python (and potentially p7zip) can be rather inconvenient.

**Additional context**

Recently we had an issue where GitHub runners updated to Python 3.12 which broke installing aqtinstall from PIP due to some dependencies that wouldn't compile properly. One of the reasons I'm filing this is we could avoid this problem by not needing to rely on the system Python to use aqtinstall on macOS.

**Comment by miurahr** [comment]
> Additional context
> 
> Recently we had an issue where GitHub runners updated to Python 3.12 which broke installing aqtinstall from PIP due to some dependencies that wouldn't compile properly. One of the reasons I'm filing this is we could avoid this problem by not needing to rely on the system Python to use aqtinstall on macOS.

Could you gently raise another issue with a detailed log message? I would like to put requests on dependency projects.

**Comment by Steveice10** [comment]
> Could you gently raise another issue with a detailed log message? I would like to put requests on dependency projects.

Sure, I'll open something with the errors I saw from `pip install aqtinstall` in the GitHub runner.

**Comment by miurahr** [comment]
v3.1.9 released with macOS binary. @Steveice10  could you check it?

**Comment by Steveice10** [comment]
Works great, thanks!
