### ISSUE TITLE
'pip install --target <directory> aqtinstall' failing with Python 3.12 on GitHub runners

### ISSUE THREAD

**Issue by Steveice10** [miurahr/aqtinstall#723]
**Describe the bug**

Recently I started seeing failures running `pip install --target <directory> aqtinstall` in GitHub Actions runners. Specifically, this happens whenever GitHub selects their updated base image that includes Python 3.12.

You can see a run that fails here: https://github.com/citra-emu/citra/actions/runs/6740101684/job/18323989454
And compare it to a passing run here: https://github.com/citra-emu/citra/actions/runs/6740101684/job/18323989626

With Python 3.12, it tries to also build wheels for `inflate64`, `pybcj`, and `pyppmd`. For some reason these all fail with the same weird compile error (example from `pyppmd`):
```
      In file included from src/ext/_ppmdmodule.c:9:
      /Library/Frameworks/Python.framework/Versions/3.12/include/python3.12/Python.h:23:12: fatal error: 'stdlib.h' file not found
      #  include <stdlib.h>
                 ^~~~~~~~~~
      1 error generated.
```

If I manually force using Python 3.11 using PATH on the same image, the build succeeds, so it's definitely a 3.12 related issue.

Not sure if this is an error with the dependencies or an issue with the GitHub runner image, I opened another issue to GitHub here: https://github.com/actions/runner-images/issues/8709

**To Reproduce**

1. Spin up a GitHub runner `macos-13` runner. Not sure if reproducible on a local machine.
2. Inside the runner, run `pip install --target <some directory> aqtinstall`.

**Expected behavior**

I expect aqtinstall to install successfully from pip.

**`aqt` output**

N/A as aqt is not run.

**Desktop (please complete the following information):**
 - OS: macOS 13
 - `aqt` version: N/A as not installed successfully; trying to install latest from pip.

**Comment by miurahr** [comment]
- https://codeberg.org/miurahr/pyppmd/issues/118
- https://codeberg.org/miurahr/inflate64/issues/10

**Comment by miurahr** [comment]
https://codeberg.org/miurahr/pybcj/issues/2

**Comment by miurahr** [comment]
https://github.com/miurahr/py7zr/pull/541

**Comment by miurahr** [comment]
All above have been released.
Could you try with py7zr v0.20.7?

**Comment by Steveice10** [comment]
Seems to be working now, thanks! On a GitHub runner image with Python 3.12.0, aqtinstall installs from pip and runs successfully.
