### ISSUE TITLE
Question: does it work with Travis/Windows ? Any samples on how to use aqtinstall with such a configuration?

### ISSUE THREAD

**Issue by ElderOrb** [miurahr/aqtinstall#73]
Update: current state of aqt on travis/windows is here: https://travis-ci.org/ElderOrb/QtTravisTest

**Comment by miurahr** [comment]
I don't have an experience using Travis-CI with Windows configuration, but in generally speaking, you can do it like as followings:

```
os: windows

before_install:
  - choco install python
  - pip install aqtinstall
  - python -m aqt install 5.14.0 windows desktop win64_msvc2017

script:
  - qmake <your project source>
  - make -j3

test:
  - <run your test>
```

**Comment by ElderOrb** [comment]
Thank you for quick response. I've tried something similar but got this; 

`The command "python -m aqt install 5.14.0 windows desktop win64_msvc2017" failed and exited with 1 during .
`

Maybe I'm using too old version of aqt? if this is the case - what is the right sequence for installing aqt from sources?

**Comment by miurahr** [comment]
Please don't remove log which has a true reason. No one can not comment.
Put your all log here.

**Comment by miurahr** [comment]
Log said

```
[0K$ python -m aqt install 5.13.1 windows desktop win64_msvc2017
[KFinished installation
Specified target combination is not valid: windows desktop win64_msvc2017
Specified target combination is not valid: windows desktop win64_msvc2017
```

For version Qt 5.13.1, Following combinations are supported
- win64_msvc2017_x64
- win64_msvc2015_x64
- win32_msvc2017

see
https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5131/

**Comment by miurahr** [comment]
You can see valid combinations which the  tool knows here
https://github.com/miurahr/aqtinstall/blob/master/aqt/combinations.json

**Comment by ElderOrb** [comment]
ah, got it, thanks

**Comment by ElderOrb** [comment]
Now I'm getting 

$ qmake -v
The command "qmake -v" exited with 127.

Seems like qmake is not in PATH. Where does aqt installs Qt? Or maybe it is possible to make aqt to update PATH?

**Comment by miurahr** [comment]
The aqtinstall does not update a path. You need to specify full path you specify or to update a path environment variable.
