### ISSUE TITLE
list_* commands ignore base url setting

### ISSUE THREAD

**Issue by comargo** [miurahr/aqtinstall#731]
https://github.com/miurahr/aqtinstall/blob/d47adb88b0ae78bfc091298d37224ee0106e4fd5/aqt/metadata.py#L524C31-L524C31

Since Python assigns default values as soon as it imports corresponding module (executes `def func():` line), and Settings file has not been read yet, the MetadataFactory.__init__ receives default (fallback) value as base_url.

Additionally, the list_* commands doesn't support baseurl argument

**Comment by miurahr** [comment]
v3.1.10 released with the fix.
