### ISSUE TITLE
Configuration file ignored

### ISSUE THREAD

**Issue by martinrotter** [miurahr/aqtinstall#736]
1. Create configuration file `aqt/settings.ini`.
2. Run arbitrary `aqt` commands.

Configuration file was created deliberately with unreachable "baseurl" to test the behavior.

* When launched without `-c` switch, then the settings file is apparently not used because `aqt` uses some internal working Qt mirror.
* When launched **with** `-c` switch, then downloading of Qt archives fails as expected.

Sample config:
```
[aqt]
concurrency: 8
baseurl: https://notfoundbro

[mirrors]
trusted_mirrors:
    https://download.qt.io
blacklist:

fallbacks:

```

**Comment by miurahr** [comment]
pls use report template.

**Comment by miurahr** [comment]
duplicated with #731
