### ISSUE TITLE
QT plugin update breaks installation

### ISSUE THREAD

**Issue by sbjartmar** [miurahr/aqtinstall#737]
**Describe the bug**
[tools_cmake/](https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_cmake/) got updated today (23.11.2023) and aqt install-tool can't install it. 

**To Reproduce**
1. Run `aqt install-qt --outputdir $QTPATH linux desktop 6.2.4 gcc_64 -m all`
2. Run `aqt install-tool --outputdir $QTPATH linux desktop tools_cmake` 

**Expected behavior**
tools_cmake is installed

**`aqt` output**
```
+ aqt install-tool --outputdir /qt linux desktop tools_cmake
INFO    : aqtinstall(aqt) v3.1.10 on Python 3.10.13 [CPython GCC 11.2.0]
ERROR   : Failed to locate XML data for the tool 'tools_cmake'.
==============================Suggested follow-up:==============================
* Please use 'aqt list-tool linux desktop' to check what tools are available.
FATAL:   While performing build: while running engine: exit status 1
```
**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - `aqt` version: aqtinstall(aqt) v3.1.10 on Python 3.10.13 [CPython GCC 11.2.0]

**Comment by sbjartmar** [comment]
Seems... fixed? Somebody at QT uploaded a broken XML?

**Comment by pzhlkj6612** [comment]
Hi.

> Seems... fixed? Somebody at QT uploaded a broken XML?

Yes. The files on their server are not always correct within a short period of time after the update.

<br>

In addition, this website may help you before installing Qt: [aqt list-qt server](https://ddalcino.github.io/aqt-list-server/)

**Comment by miurahr** [comment]
You can find  https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_cmake/
files are updated around 23-Nov-2023 14:58. 
Your report here at 23-Nov-2023

You encounter error when Qt Download site maintainance. Please retry after a day.
