### ISSUE TITLE
Extra modules

### ISSUE THREAD

**Issue by EndrII** [miurahr/aqtinstall#75]
How to install desktop qt with all extra modules?

I want to install the full version of qt with all the additional modules that it has at the moment.

example:
``` bash
aqt install --outputdir /opt 5.14.0 linux desktop -m all
or 
aqt install --outputdir /opt 5.14.0 linux desktop -m *
```

Thanks.

**Comment by miurahr** [comment]
v0.6a2 released include suggested  option "-m all". Any feedback?

**Comment by EndrII** [comment]
@miurahr  Thanks.
I will check it later. within a week.
thanks for you work.
