### ISSUE TITLE
Failed to locate XML data for the tool 'tools_openssl_x64'

### ISSUE THREAD

**Issue by jamesstidard** [miurahr/aqtinstall#761]
**Describe the bug**
When running `python.exe -m aqt install-tool windows desktop tools_openssl_x64 --outputdir D:\a\src/Qt` I get the error: `Failed to locate XML data for the tool 'tools_openssl_x64'`

**To Reproduce**
1. install `aqt` using this command
`python.exe -m pip install aqtinstall==3.1.*`
2. run `aqt` with this command
`python.exe -m aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 --outputdir D:\a\src/Qt`
`python.exe -m aqt install-tool windows desktop tools_openssl_x64 --outputdir D:\a\src/Q`
3. See error
```
INFO    : aqtinstall(aqt) v3.1.11 on Python 3.11.8 [CPython MSC v.1937 64 bit (AMD64)]
ERROR   : Failed to locate XML data for the tool 'tools_openssl_x64'.
==============================Suggested follow-up:==============================
* Please use 'aqt list-tool windows desktop' to check what tools are available.
Error: Error: The process 'C:\hostedtoolcache\windows\Python\3.11.8\x64\python.exe' failed with exit code 1
```

**Desktop (please complete the following information):**
 - OS: Windows
 - `aqt` version: v3.1.11

**Additional context**
This is being run via a GitHub action using https://github.com/jurplel/install-qt-action/tree/v3/, with the QT version of '5.15.2'.

When I looked at the aqt source code that produces this error, it looks like a network request, based on the exception name, so maybe it's just a broken url or some downtime for the host? Though I'm not very familiar with the QT or its build processes, so was hoping someone could confirm that.

Thanks

**Comment by miurahr** [comment]
You can read the error message.
`* Please use 'aqt list-tool windows desktop' to check what tools are available.`

```
python -m aqt list-tool windows desktop | grep ssl
tools_opensslv3_x64
tools_opensslv3_src

```

**Comment by jamesstidard** [comment]
Thanks @miurahr, I had assume the name was correct as it's some CI pipeline that had otherwise been working for a year or so previously. I guess things got renamed. Thanks, I'll give that a try.
