### ISSUE TITLE
pip package is missing for 3.1.14

### ISSUE THREAD

**Issue by szigetics** [miurahr/aqtinstall#783]
**Describe the bug**
The pip package is missing for the 3.1.14 release

The relevant build has failed : 
https://github.com/miurahr/aqtinstall/actions/runs/8863120682

Could you please publish the new release?

**Comment by pzhlkj6612** [comment]
It seems that the 930eb2b59806303e18093bb4c36ccd7a8afb7149 commit makes a bunch of case conversion in the "pyproject.toml" file. Is that intentional?  @miurahr

**Comment by miurahr** [comment]
> It seems that the [930eb2b](https://github.com/miurahr/aqtinstall/commit/930eb2b59806303e18093bb4c36ccd7a8afb7149) commit makes a bunch of case conversion in the "pyproject.toml" file. Is that intentional? @miurahr

@pzhlkj6612 It is not intentional. Thank you for notified. I've revert it and push v3.1.15.

**Comment by miurahr** [comment]
https://pypi.org/project/aqtinstall/#history
There is v3.1.15 release on pypi.org
