### ISSUE TITLE
Bluetooth Module Missing in Qt 6.6.2

### ISSUE THREAD

**Issue by kebekus** [miurahr/aqtinstall#787]
Dear all,

Thank you for all your work on this project! Recently, I found that the Qt Bluetooth Module is missing for Qt 6.6.2, for numerous combinations of architectures and platforms. Would it be possible to add those?

Thanks again · Best wishes,

Stefan.

**Comment by miurahr** [comment]
Please fill template.

**To Reproduce**

**Expected behavior**

**Desktop**
 - OS: 
 - python version
 - `aqt` version 

**Additional context**

**Comment by pcolby** [comment]
> I found that the Qt Bluetooth Module is missing for Qt 6.6.2

I have no issues using Qt 6.6.2's Bluetooth library via aqt on Linux, macOS and Windows.

Just in case it helps, there is no separate Bluetooth module for Qt6 - it's part of the `qtconnectivity` module, eg:

```
aqt install-qt linux desktop 6.6.2 gcc_64 -m qtconnectivity
```

**Comment by kebekus** [comment]
As Paul guessed, I was unaware that Bluetooth is part of the qtconnectivity module. Following Paul's advice, I solved the issue.

@miurahr Thanks for maintaining this wonderful project!
@pcolby Thank you for your help!
