### ISSUE TITLE
[Bug]: v3.1.17 fails for Qt 6.8 docs; ie repeat of issue #775

### ISSUE THREAD

**Issue by pcolby** [miurahr/aqtinstall#809]
### Bug description

> [!TIP]
> I'm pretty sure this is the same issue as #775, but for Qt 6.8 this time, instead of Qt 6.7.

aqtinstall v3.1.17 added support for Qt 6.8.0; this seems to be working fine for installing the Qt libraries themselves.  However, attempting to install the Qt docs fails.

For example:

```
aqt install-doc linux 6.8.0 --outputdir /home/runner/work/dokit/Qt --archives qtcore --modules qtbluetooth
```

Results in error:

```
WARNING : Failed to download checksum for the file 'Updates.xml'. This may happen on unofficial mirrors.
ERROR   : Failed to locate XML data for Qt version '6.8.0'.
```

Cheers.

### Expected behavior

Expected the Qt docs to be installed.

### aqt and python version

aqtinstall(aqt) v3.1.17 on Python 3.10.4 [CPython GCC 13.2.0]

### Operating System

Linux/Unix, MacOS, Windows

### Relevant log output

```shell
$ aqt install-doc linux 6.8.0 --outputdir /home/runner/work/dokit/Qt --archives qtcore --modules qtbluetooth
INFO    : aqtinstall(aqt) v3.1.17 on Python 3.10.4 [CPython GCC 13.2.0]
WARNING : Specified Qt version "6.8.0" did not exist when this version of aqtinstall was released. This may not install properly, but we will try our best.
WARNING : Failed to download checksum for the file 'Updates.xml'. This may happen on unofficial mirrors.
ERROR   : Failed to locate XML data for Qt version '6.8.0'.
==============================Suggested follow-up:==============================
* Please use 'aqt list-qt all_os qt' to show versions available.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by miurahr** [comment]
When install doc for 6.8.0  aqt need to look `https://download.qt.io/online/qtsdkrepository/all_os/qt/qt6_680_src_doc_examples/`  to download `Updates.xml`

When observe `archives.py:L372` variable `name` become `'qt6_680/qt6_680_src_doc_examples'` which looks good.
And steps forward to `archives.py:L402` , variable `update_xml_url` become `'online/qtsdkrepository/all_os/qt/qt6_680/qt6_680_src_doc_examples/Updates.xml'` which has redundant `qt6_680`.

**Comment by miurahr** [comment]
Does v3.1.18 work for you?

**Comment by pcolby** [comment]
Yes, I've confirmed v3.1.18 works fine for Linux and macOS 👍🏼

I expect it'll work fine on Windows too, but I'm just implementing a workaround for https://github.com/jurplel/install-qt-action/issues/250 before I can verify that one.

Thanks!

**Comment by pcolby** [comment]
Yep, confirmed working fine on Windows too. Thanks!b😊
