### ISSUE TITLE
Split tools by platform

### ISSUE THREAD

**Issue by EndrII** [miurahr/aqtinstall#83]
The problem is that I need to install qif for 3 platforms (win linux and mac). Once installed, mac rewrites linux files.

This is qif after installing from all platforms. But there are no Linux files because they were installed first.
![image](https://user-images.githubusercontent.com/12465465/72705346-4cd8ba00-3b6c-11ea-8613-6012fb387142.png)

**Comment by miurahr** [comment]
why not adding --outputdir <directory> option?

**Comment by EndrII** [comment]
hm. maybe you're right.
okay I will use the --outputdir option
