### ISSUE TITLE
QT 6.8.0 Windows

### ISSUE THREAD

**Issue by Edgars-Cirulis** [miurahr/aqtinstall#831]
Please uprev

**Comment by ddalcino** [comment]
Duplicate #778

If you can't wait, please just `python -m pip install git+https://github.com/miurahr/aqtinstall@master` instead. Releasing a new version before it's ready doesn't help anyone.

**Comment by Edgars-Cirulis** [comment]
> Duplicate #778
> 
> If you can't wait, please just `python -m pip install git+https://github.com/miurahr/aqtinstall@master` instead. Releasing a new version before it's ready doesn't help anyone.

You miss understood.  The main issue that this repo even on latest commit qt 6.7.3 is the latest not 6.8.0

**Comment by Edgars-Cirulis** [comment]
Its 6.7.3 target for Windows

https://github.com/miurahr/aqtinstall/commit/bdf8b4b1f99795d3733bee4b4d0eeaa629637af1#diff-8d9ca758e1c5c08710f62271f0b0c3f7a5e19a484f790d5e4b0e713f032ca7d9R28

**Comment by miurahr** [comment]
> Its 6.7.3 target for Windows
> 
> [bdf8b4b#diff-8d9ca758e1c5c08710f62271f0b0c3f7a5e19a484f790d5e4b0e713f032ca7d9R28](https://github.com/miurahr/aqtinstall/commit/bdf8b4b1f99795d3733bee4b4d0eeaa629637af1#diff-8d9ca758e1c5c08710f62271f0b0c3f7a5e19a484f790d5e4b0e713f032ca7d9R28)

This is the change of CI test target. We can not test all the versions on the CI.
