### ISSUE TITLE
[Bug]: Unable to install QtWebEngine

### ISSUE THREAD

**Issue by Poldraunic** [miurahr/aqtinstall#833]
### Bug description

It seems with the release of Qt 6.8, QtWebEngine module has been moved to a different directory. Now, command `aqt -c aqt.conf install-qt linux desktop 6.8.0 linux_gcc_64 -m qtwebengine qtwebchannel qtpositioning` will fail to install `qtwebengine` with error `ERROR   : The packages ['qtwebengine'] were not found while parsing XML of package information!`

For example:
* 6.7.3 Mirror: https://mirrors.ocf.berkeley.edu/qt/online/qtsdkrepository/windows_x86/desktop/qt6_673/. `qtwebengine` is present. 
* 6.8.0 Mirror: https://mirrors.ocf.berkeley.edu/qt/online/qtsdkrepository/windows_x86/desktop/qt6_680/qt6_680/. `qtwebengine` is missing. However, it is now present here: https://mirrors.ocf.berkeley.edu/qt/online/qtsdkrepository/windows_x86/extensions/qtwebengine/680/msvc2022_64/.

Same behaviour on both Windows and Linux. I suppose, MacOS is no different, but I am unable to test this right now.

### Expected behavior

I expect it work the same way as it did for previous versions. The `--extensions` flag is deprecated and I am unable to use it.

### aqt and python version

v3.1.18 on Python 3.12.3 [CPython GCC 13.2.0]

### Operating System

Linux/Unix, MacOS, Windows

### Relevant log output

```shell
gitlab-runner@gitrunner-ubuntu:~/qt$ gitlab-runner@gitrunner-ubuntu:~/qt$ aqt -c aqt.conf install-qt linux desktop 6.8.0 linux_gcc_64 -m qtwebengine qtwebchannel qtpositioning
INFO    : aqtinstall(aqt) v3.1.18 on Python 3.12.3 [CPython GCC 13.2.0]
WARNING : Specified Qt version "6.8.0" did not exist when this version of aqtinstall was released. This may not install properly, but we will try our best.
WARNING : Specified modules ['qtpositioning', 'qtwebchannel', 'qtwebengine'] did not exist when this version of aqtinstall was released. This may not install properly, but we will try our best.
ERROR   : The packages ['qtwebengine'] were not found while parsing XML of package information!
==============================Suggested follow-up:==============================
* Please use 'aqt list-qt linux desktop --modules 6.8.0 <arch>' to show modules available.

gitlab-runner@gitrunner-ubuntu:~/qt$ aqt -c aqt.conf list-qt linux desktop --modules 6.8.0 linux_gcc_64
debug_info qt3d qt3d.debug_information qt5compat qt5compat.debug_information qtcharts qtcharts.debug_information qtconnectivity qtconnectivity.debug_information qtdatavis3d qtdatavis3d.debug_information qtgraphs qtgraphs.debug_information qtgrpc qtgrpc.debug_information qthttpserver qthttpserver.debug_information qtimageformats qtimageformats.debug_information qtlanguageserver qtlocation qtlocation.debug_information qtlottie qtlottie.debug_information qtmultimedia qtmultimedia.debug_information qtnetworkauth qtnetworkauth.debug_information qtpositioning qtpositioning.debug_information qtquick3d qtquick3d.debug_information qtquick3dphysics qtquick3dphysics.debug_information qtquickeffectmaker qtquickeffectmaker.debug_information qtquicktimeline qtquicktimeline.debug_information qtremoteobjects qtremoteobjects.debug_information qtscxml qtscxml.debug_information qtsensors qtsensors.debug_information qtserialbus qtserialbus.debug_information qtserialport qtserialport.debug_information qtshadertools qtshadertools.debug_information qtspeech qtspeech.debug_information qtvirtualkeyboard qtvirtualkeyboard.debug_information qtwaylandcompositor qtwaylandcompositor.debug_information qtwebchannel qtwebchannel.debug_information qtwebsockets qtwebsockets.debug_information qtwebview qtwebview.debug_information
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by miurahr** [comment]
Duplicated with #803 ?

**Comment by Poldraunic** [comment]
Yup, definitely.
