### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kevinhendricks** [miurahr/aqtinstall#834]
### Bug description

Failure for current master to install Qt 6.8.0 for linux for desktop because of change in directory structure of https://download.qt.io/online/qtsdkrepository/qt6_680 to now include a sudirectoty qt6_680.

This is true for all mirrors I have tested so far.

Log message: 

2024-10-25 10:52:57,690 - aqt.helper - DEBUG - helper 140597967510400 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_680/Updates.xml.sha256
2024-10-25 10:52:58,481 - aqt.main - ERROR - installer 140597967510400 Failed to locate XML data for Qt version '6.8.0'.

This is a result of a new nested folder being used in qt6_680.  Check out this link and compare it against all others:

https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_680/

Now leads to a new nested folder qt6_680 instead of the Updates.xml file.  The Updates.xml file is found here instead:

https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_680/qt6_680/

### Expected behavior

It works the same as it does for qt 6.7.3

### aqt and python version

latest on Manjaro stable, and with master

### Operating System

Linux/Unix

### Relevant log output

```shell
See above.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pzhlkj6612** [comment]
Hi. 

Title suggestion: _Qt 6.8.0 nested folder is unsupported_

> This is true for all mirrors I have tested so far.

Nice try, and they are the same because they are the mirrors.

**Comment by kevinhendricks** [comment]
Understood but not all mirrors were updated previously with this change.
Did you follow the manual links.  Do you understand the issue or do you need more info?

**Comment by kevinhendricks** [comment]
I checked out master and saw the proper code in archives.py to handle the qt6_680 special case change.   I then found that my test Manjaro stable system had an older python-aqtinstall.  I removed that.  So my guess is the older aqt was being found before the local copy I was trying to test.

So I am closing this as I am pretty sure this is now user error on my part.  I should have looked to see if an out of date python-aqtinstall Manjaro package was in place before creating the bug report.

My bad. Sorry

**Comment by pzhlkj6612** [comment]
> Do you understand the issue or do you need more info?

Yes, I understand the issue. Qt guys always change their file structure, so...

It seems that we have already applied some fixes: #800, did you try that? Is your "master" updated?

**Comment by pzhlkj6612** [comment]
> My bad. Sorry

No problem. 

> Title suggestion: _Qt 6.8.0 nested folder is unsupported_

I think you can help us rewrite a new title of this issue to make search more effective.
