### ISSUE TITLE
Qt  change of download policy may break aqtinstall 

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#84]
Qt ask valid ID for downloading binaries, it may break aqtinstall.

https://lwn.net/Articles/810652/

**Comment by EndrII** [comment]
Why did you decide that this should affect your utility?
 After all, qt does not close open source, but only transfers the contents of lts to the commercial repository.  You just need to add flags to authorize qt accounts.

**Comment by miurahr** [comment]
> You just need to add flags to authorize qt accounts.

Why you can say 'just need'?  What is a 'flag'?

   I do not know what is going to be required because online installation procedure and specifications are not disclosed. Aqtinstall is realized through observation of  installed files, web site URLs, and watching metadata files.  I have empirically understood a specification.
 
  A Qt Online Installer is a proprietary software and the Qt company may change it and download site configurations. Current installer allow skip account registration but it may become mandatory in Feb. according to news. It is unclear what are  further changes.

**Comment by EndrII** [comment]
"flags" are options options

As for the utility, I agree with you, it is too early to talk about it. But I beg you not to abandon the project. He is very useful to me.

**Comment by LorenzE** [comment]
I agree with @EndrII, your tool is very helpful!

**Comment by miurahr** [comment]
There may be some configuration changes in download.qt.io, but there become not a big issue.
I'd like to close here.
