### ISSUE TITLE
[Bug]: Fails to install-src for Qt 6.8.1 on Linux

### ISSUE THREAD

**Issue by Matthew-McRaven** [miurahr/aqtinstall#843]
### Bug description

When attempting to install the source code for Qt 6.8.1 on Linux, it fails to find the Update.xml file.

I am working inside a fresh docker container with python (e.g., `docker run -it python /bin/bash`). Inside the container, I execute `pip install aqtinstall` followed by `aqt install-src linux 6.8.1`, which leads to the error message reported below.

This might be related to #810?

### Expected behavior

Installing source code for Qt 6.8.1 should not cause an error.

### aqt and python version

v3.1.19 with Python 3.12.4

### Operating System

Linux/Unix

### Relevant log output

```shell
root@43354294a782:/# aqt install-src -O /build-qt linux 6.8.1
INFO    : aqtinstall(aqt) v3.1.19 on Python 3.12.4 [CPython GCC 12.2.0]
WARNING : Failed to download checksum for the file 'Updates.xml'. This may happen on unofficial mirrors.
ERROR   : Failed to locate XML data for Qt version '6.8.1'.
==============================Suggested follow-up:==============================
* Please use 'aqt list-qt all_os qt' to show versions available.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ddalcino** [comment]
That’s an input validation bug. Aqt should tell you that you’re missing a ‘target’ argument; I’m not sure why it isn’t.

Try running `aqt install-src linux desktop 6.8.1` instead; that should work better.

**Comment by ddalcino** [comment]
The qt repo directory structure changed again for 6.8.1; source/docs /examples are now at https://download.qt.io/online/qtsdkrepository/all_os/qt/qt6_681_windows_line_endings_src/ and https://download.qt.io/online/qtsdkrepository/all_os/qt/qt6_681_unix_line_endings_src/
