### ISSUE TITLE
[Bug]: Failed to download checksum for the file 'Updates.xml'

### ISSUE THREAD

**Issue by bjorn** [miurahr/aqtinstall#851]
### Bug description

Since updating to aqtinstall 3.1.20, I always get an error when trying to install Qt 6.8.1 for Windows (see relevant log output).

Same error happens for Qt 6.8.0, but Qt 6.7.3 works fine. However, aqtinstall 3.1.19 could install 6.8.0 and 6.8.1 fine, so there appears to be a regression. The problem seems specific to Windows, at least I can install Qt 6.8.1 for Linux and macOS just fine also with aqtinstall 3.1.20.

### Expected behavior

I expect to be able to install Qt 6.8.1 for Windows.

### aqt and python version

aqtinstall(aqt) v3.1.20 on Python 3.13.0 [CPython GCC 14.2.1 20240912 (Red Hat 14.2.1-3)]

### Operating System

Linux/Unix, Windows

### Relevant log output

```shell
$ aqt install-qt windows desktop 6.8.1 win64_mingw
INFO    : aqtinstall(aqt) v3.1.20 on Python 3.13.0 [CPython GCC 14.2.1 20240912 (Red Hat 14.2.1-3)]
WARNING : Failed to download checksum for the file 'Updates.xml'. This may happen on unofficial mirrors.
ERROR   : Failed to locate XML data for Qt version '6.8.1'.
==============================Suggested follow-up:==============================
* Please use 'aqt list-qt windows desktop' to show versions available.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jdpurcell** [comment]
I tried installing Qt 6.8.1 for Windows and can confirm, `win64_msvc2022_64` is the only one that didn't regress in 3.1.20.

| arch | aqt 3.1.19 | aqt 3.1.20 |
| --- | --- | --- |
| win64_msvc2022_64 | ✔ | ✔ |
| win64_msvc2022_arm64_cross_compiled | ✔ | ❌ |
| win64_mingw | ✔ | ❌ |
| win64_llvm_mingw | ✔ | ❌ |

**Comment by jdpurcell** [comment]
@tsteven4 Tagging you in case you'd like to volunteer.
