### ISSUE TITLE
FileNotFoundError on macos-latest

### ISSUE THREAD

**Issue by LorenzE** [miurahr/aqtinstall#89]
I get an error on GithubAction runner macos-latest trying to instal Qt 5.14.0.

> FileNotFoundError: [Errno 2] No such file or directory: 'qtwebsockets-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z'

Qt5.10.1 works fine for Mac though. Win and Linux are running fine for 5.10.1 and 5.14.0. I am using the Instal Qt Github Action. You can check the build log [here](https://github.com/mne-tools/mne-cpp/pull/484/checks?check_run_id=442646222).

Just out of curiosity: There is a redirect happening to an URL at berkley. Any idea why? Is this already in place to bypass the new Qt offerings situation?

Any help would be greatly appreciated :)

**Comment by miurahr** [comment]
>Just out of curiosity: There is a redirect happening to an URL at berkley. Any idea why? Is this already in place to bypass the new Qt offerings situation?

Mirror server is specified by https://download.qt.io/ through HTTP 1.1 redirect response.
aqtinstall catch a redirect request and check against blacklist, where unstable mirror site, 
then logging it for debugging purpose.

When you want to fix mirror site, aqtinstall has an option "--base" which specify mirror site.
ex. -b http://mirrors.ocf.berkeley.edu/qt/

**Comment by LorenzE** [comment]
From the logs it seems the download is working just fine, also after the redirect. The file is getting extracted:

> 2020-02-13 02:21:59,162 - aqt - INFO - -Extracting qtwebsockets-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z...

Do you have any idea why I get the FileNotFoundError? Thanks

**Comment by miurahr** [comment]
I found installed aqtinstall version is 0.7.1.  Then I recognize a release automation process in 0.7.2 is failed, and has not released on PyPI yet.
On current master seems working on MacOS with Qt 5.14.0,  so release 0.7.3 may help.

Now I'd like to move release automation process to Github Actions to be more robust.

**Comment by LorenzE** [comment]
thank you for looking into this. We will wait for 0.7.3 to be release. I cannot easily change to 0.7.3 right now since the install qt github action has the aqt install implemented like this:

https://github.com/jurplel/install-qt-action/blob/30ce7dbe1521dd7e380e8b438eb93f88354b04b2/src/main.ts#L21

**Comment by LorenzE** [comment]
I saw you backrolled releases. Our Github Qt installer is now stuck when downloading Qt via aqt. See log here: https://github.com/mne-tools/mne-cpp/runs/446438190
